import type { LeadClassificationConfig, LeadLevelTier } from './lead-classification.types';

export const DEFAULT_LEVEL_TIERS: LeadLevelTier[] = [
  {
    id: 'vip',
    label: 'VIP',
    emoji: '🔴',
    description: 'Siêu nóng, ưu tiên tuyệt đối',
    sla_label: '< 2 phút',
    min_score: 90,
    max_score: 100,
    enabled: true,
    sort_order: 1,
  },
  {
    id: 'hot',
    label: 'HOT',
    emoji: '🟠',
    description: 'Nóng, cần liên hệ ngay',
    sla_label: '< 5 phút',
    min_score: 75,
    max_score: 89,
    enabled: true,
    sort_order: 2,
  },
  {
    id: 'warm_plus',
    label: 'WARM+',
    emoji: '🟡',
    description: 'Ấm tốt, có tiềm năng cao',
    sla_label: '< 30 phút',
    min_score: 55,
    max_score: 74,
    enabled: true,
    sort_order: 3,
  },
  {
    id: 'warm',
    label: 'WARM',
    emoji: '🟢',
    description: 'Ấm thường, cần nurturing',
    sla_label: 'Trong ngày',
    min_score: 35,
    max_score: 54,
    enabled: true,
    sort_order: 4,
  },
  {
    id: 'cold_plus',
    label: 'COLD+',
    emoji: '🔵',
    description: 'Lạnh nhưng có tiềm năng',
    sla_label: 'Trong tuần',
    min_score: 15,
    max_score: 34,
    enabled: true,
    sort_order: 5,
  },
  {
    id: 'cold',
    label: 'COLD',
    emoji: '⚫',
    description: 'Lạnh, cần nuôi dưỡng dài hạn',
    sla_label: 'Automation',
    min_score: 0,
    max_score: 14,
    enabled: true,
    sort_order: 6,
  },
];

export const DEFAULT_LEAD_CLASSIFICATION_CONFIG: LeadClassificationConfig = {
  default_flow_kind: 'b2b_prospect',
  flows: {
    b2b_prospect: {
      level_tiers: DEFAULT_LEVEL_TIERS.map((t) => ({ ...t })),
      default_inbound_score: 75,
    },
    spa_operational: {
      level_tiers: DEFAULT_LEVEL_TIERS.map((t) => ({ ...t })),
      default_inbound_score: 75,
    },
  },
  routing_rules: [
    {
      id: 'meta-no-client-b2b',
      label: 'Meta/Facebook không gắn client → B2B',
      channel: 'meta',
      source: '*',
      requires_client: false,
      flow_kind: 'b2b_prospect',
      priority: 100,
      enabled: true,
    },
    {
      id: 'facebook-no-client-b2b',
      label: 'Facebook không gắn client → B2B',
      channel: 'facebook',
      source: '*',
      requires_client: false,
      flow_kind: 'b2b_prospect',
      priority: 99,
      enabled: true,
    },
    {
      id: 'client-spa',
      label: 'Lead gắn client → CSKH vận hành',
      channel: '*',
      source: '*',
      requires_client: true,
      flow_kind: 'spa_operational',
      priority: 90,
      enabled: true,
    },
    {
      id: 'meta-with-client-spa',
      label: 'Meta gắn client → CSKH vận hành',
      channel: 'meta',
      source: '*',
      requires_client: true,
      flow_kind: 'spa_operational',
      priority: 80,
      enabled: true,
    },
  ],
};
