export const DEFAULT_STAFF_LEVELS: Array<Record<string, unknown>> = [
  {
    id: 's',
    code: 'S',
    label: 'CHUYÊN GIA',
    emoji: '💎',
    experience: '> 3 năm kinh nghiệm',
    quantitative: [],
    skills: [],
    suitable_leads: [],
    max_leads_min: 10,
    max_leads_max: 15,
    priority_note: 'Ưu tiên nhận: HOT + VIP trước tiên',
    enabled: true,
    sort_order: 1,
  },
  {
    id: 'a',
    code: 'A',
    label: 'SENIOR',
    emoji: '🥇',
    experience: '1–3 năm kinh nghiệm',
    quantitative: [],
    skills: [],
    suitable_leads: [],
    max_leads_min: 8,
    max_leads_max: 12,
    priority_note: '',
    enabled: true,
    sort_order: 2,
  },
  {
    id: 'b',
    code: 'B',
    label: 'JUNIOR',
    emoji: '🥈',
    experience: '6 tháng – 1 năm',
    quantitative: [],
    skills: [],
    suitable_leads: [],
    max_leads_min: 5,
    max_leads_max: 10,
    priority_note: '',
    enabled: true,
    sort_order: 3,
  },
  {
    id: 'c',
    code: 'C',
    label: 'TRAINEE',
    emoji: '🥉',
    experience: '< 6 tháng',
    quantitative: [],
    skills: [],
    suitable_leads: [],
    max_leads_min: 3,
    max_leads_max: 6,
    priority_note: '',
    enabled: true,
    sort_order: 4,
  },
];

export const DEFAULT_COMPETENCY_CONFIG: Record<string, unknown> = {
  metrics: [
    {
      id: 'close_rate_pct',
      label: 'Tỷ lệ chốt từ lead (%)',
      weight: 25,
      bands: [],
    },
  ],
  classifications: [
    { id: 'cls_s', min_score: 85, max_score: 100, level_id: 's', label: 'Level S', emoji: '💎', sort_order: 1 },
    { id: 'cls_a', min_score: 65, max_score: 84, level_id: 'a', label: 'Level A', emoji: '🥇', sort_order: 2 },
    { id: 'cls_b', min_score: 45, max_score: 64, level_id: 'b', label: 'Level B', emoji: '🥈', sort_order: 3 },
    { id: 'cls_c', min_score: 0, max_score: 44, level_id: 'c', label: 'Level C', emoji: '🥉', sort_order: 4 },
  ],
};

export const COMPETENCY_METRIC_OPTIONS = [
  { id: 'close_rate_pct', label: 'Tỷ lệ chốt từ lead (%)' },
  { id: 'kpi_achievement_pct', label: 'Doanh số so với KPI tháng (%)' },
  { id: 'avg_deal_value_billion', label: 'Giá trị TB mỗi deal (tỷ VNĐ)' },
  { id: 'avg_response_minutes', label: 'Tốc độ phản hồi TB (phút)' },
  { id: 'lead_coverage_pct', label: 'Tỷ lệ lead không bỏ sót (%)' },
  { id: 'appointment_conversion_pct', label: 'Tỷ lệ chuyển lead → lịch hẹn (%)' },
  { id: 'customer_rating', label: 'Điểm đánh giá KH sau tư vấn (/10)' },
  { id: 'referrals_per_month', label: 'Số KH giới thiệu / tháng' },
];
