import type { AlertLevel, HubQualityRule } from '../kpi-hub.types';

const now = '2026-09-04T08:45:00+07:00';

/** P2-W4 default DQ rules (14) — FR-DQ seed catalog. */
export function seedKpiHubQualityRules(): HubQualityRule[] {
  return [
    {
      id: 'qr-p2-001',
      name: 'Lead_ID not null',
      connection_id: 'src-crm',
      connection_name: 'CRM Leads & Deals',
      check_type: 'COMPLETENESS',
      severity: 'CRITICAL' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-002',
      name: 'Lead duplicate phone+campaign+day',
      connection_id: 'src-crm',
      connection_name: 'CRM Leads & Deals',
      check_type: 'UNIQUENESS',
      severity: 'WARNING' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-003',
      name: 'is_valid boolean',
      connection_id: 'src-crm',
      connection_name: 'CRM Leads & Deals',
      check_type: 'VALIDITY',
      severity: 'WARNING' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-004',
      name: 'campaign_id → UTM map',
      connection_id: 'src-sharepoint',
      connection_name: 'SharePoint Campaign Mapping',
      check_type: 'CONSISTENCY',
      severity: 'WARNING' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-005',
      name: 'Spend ≥ 0',
      connection_id: 'src-meta',
      connection_name: 'Meta Ads Insights',
      check_type: 'ACCURACY',
      severity: 'CRITICAL' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-006',
      name: 'Sync within SLA — CRM',
      connection_id: 'src-crm',
      connection_name: 'CRM Leads & Deals',
      check_type: 'FRESHNESS',
      severity: 'WARNING' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-007',
      name: 'Sync within SLA — Meta Ads',
      connection_id: 'src-meta',
      connection_name: 'Meta Ads Insights',
      check_type: 'FRESHNESS',
      severity: 'WARNING' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-008',
      name: 'Sync within SLA — SharePoint',
      connection_id: 'src-sharepoint',
      connection_name: 'SharePoint Campaign Mapping',
      check_type: 'FRESHNESS',
      severity: 'CRITICAL' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-009',
      name: 'Email completeness',
      connection_id: 'src-crm',
      connection_name: 'CRM Leads & Deals',
      check_type: 'COMPLETENESS',
      severity: 'WARNING' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-010',
      name: 'Phone format validity',
      connection_id: 'src-crm',
      connection_name: 'CRM Leads & Deals',
      check_type: 'VALIDITY',
      severity: 'WARNING' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-011',
      name: 'Deal amount > 0',
      connection_id: 'src-crm',
      connection_name: 'CRM Leads & Deals',
      check_type: 'ACCURACY',
      severity: 'CRITICAL' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-012',
      name: 'Invoice amount consistency',
      connection_id: 'src-erp',
      connection_name: 'ERP Finance',
      check_type: 'CONSISTENCY',
      severity: 'WARNING' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-013',
      name: 'GA4 connector available',
      connection_id: 'src-ga4',
      connection_name: 'Google Analytics 4',
      check_type: 'AVAILABILITY',
      severity: 'INFO' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
    {
      id: 'qr-p2-014',
      name: 'ERP sync freshness',
      connection_id: 'src-erp',
      connection_name: 'ERP Finance',
      check_type: 'FRESHNESS',
      severity: 'CRITICAL' as AlertLevel,
      enabled: true,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
  ].map((r) => ({ ...r, last_run_at: r.last_run_at ?? now }));
}

export const KPI_HUB_QUALITY_RULE_WEIGHTS: Record<string, number> = {
  COMPLETENESS: 15,
  UNIQUENESS: 10,
  VALIDITY: 10,
  CONSISTENCY: 10,
  ACCURACY: 15,
  FRESHNESS: 20,
  AVAILABILITY: 5,
};
