#!/usr/bin/env bash
# Email Gate A — full automated cutover gate (EM-5): handoff §13 + phase5 prod pilot.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
PYTHON="${PYTHON:-python3}"
export PYTHONPATH="$ROOT${PYTHONPATH:+:$PYTHONPATH}"
export PTT_ARTIFACTS_DIR="${PTT_ARTIFACTS_DIR:-$ROOT/.local-dev}"
export DATABASE_URL="${DATABASE_URL:-postgresql://ptt:ptt_dev@127.0.0.1:5432/ptt_agency}"
export PTT_EMAIL_ENABLED="${PTT_EMAIL_ENABLED:-1}"
export PTT_EMAIL_SEND_ENABLED="${PTT_EMAIL_SEND_ENABLED:-1}"
export PTT_EMAIL_JOURNEYS_ENABLED="${PTT_EMAIL_JOURNEYS_ENABLED:-0}"
export PTT_EMAIL_PORTAL_ENABLED="${PTT_EMAIL_PORTAL_ENABLED:-0}"
export EM5_EXPECT_EMAIL_ENABLED="${EM5_EXPECT_EMAIL_ENABLED:-1}"
export EM5_EXPECT_SEND_ENABLED="${EM5_EXPECT_SEND_ENABLED:-1}"
export EM5_EXPECT_JOURNEYS_ENABLED="${EM5_EXPECT_JOURNEYS_ENABLED:-0}"
export EM5_EXPECT_PORTAL_ENABLED="${EM5_EXPECT_PORTAL_ENABLED:-0}"
export EM5_SKIP_SOAK="${EM5_SKIP_SOAK:-1}"
export EM5_SKIP_NEST_SMOKE="${EM5_SKIP_NEST_SMOKE:-1}"
export EM5_SKIP_BUILD="${EM5_SKIP_BUILD:-1}"
export EM5_SKIP_PRIOR_REPORTS="${EM5_SKIP_PRIOR_REPORTS:-1}"
export EM5_INCLUDE_WAVE_GATES="${EM5_INCLUDE_WAVE_GATES:-0}"
export EMAIL_HANDOFF_SKIP_E2E="${EMAIL_HANDOFF_SKIP_E2E:-1}"

echo "==> Email Gate A cutover gate (EM-5)"
echo "==> §13 handoff gate (ops-web QA)"
bash "$ROOT/scripts/email_handoff_gate.sh"
echo "==> EM-5 prod pilot gate pack"
bash "$ROOT/scripts/phase5_email_prod_pilot_gate.sh"
echo "OK  Email Gate A cutover gate — see .local-dev/wave-gates/email_handoff_gate_report.json and phase5-email-pilot-gate-report.json"
