#!/usr/bin/env python3
"""Export scripts/data/rnosai_handover_rbac_seed.sql for psql apply (no psycopg2)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "scripts/data/rnosai_handover_rbac_grants.json"
CATALOG = ROOT / "services/ptt-crm-api/src/staff-permissions/rbac-admin-catalog.json"
OUT = ROOT / "scripts/data/rnosai_handover_rbac_seed.sql"
CODES = ("CEO", "AE", "ACM", "CE", "MEP", "GD", "MKL", "PD")


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> int:
    doc = json.loads(DOC.read_text(encoding="utf-8"))
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    lines = ["BEGIN;", "-- generated by scripts/export_rnosai_handover_rbac_sql.py"]

    super_rows: list[tuple[str, str]] = []
    for sid, acts in (catalog.get("section_actions") or {}).items():
        for a in acts:
            super_rows.append((sid, str(a).lower()))
    for btn in catalog.get("ui_buttons") or []:
        bid = btn.get("id")
        req = str(btn.get("requires_action") or "").lower()
        if bid and req:
            super_rows.append((str(bid), req))

    lines.append(
        """
-- SUPER-ADMIN
DELETE FROM staff_section_permissions WHERE position_id = (
  SELECT id FROM crm_positions WHERE lower(trim(code)) = 'super-admin' AND active LIMIT 1
);
INSERT INTO staff_section_permissions (position_id, section_id, action)
SELECT p.id, v.section_id, v.action
FROM crm_positions p
CROSS JOIN (VALUES
"""
    )
    lines.append(
        ",\n".join(
            f"  ({sql_str(sid)}, {sql_str(act)})" for sid, act in sorted(set(super_rows))
        )
    )
    lines.append(
        """
) AS v(section_id, action)
WHERE lower(trim(p.code)) = 'super-admin' AND p.active
ON CONFLICT (position_id, section_id, action) DO NOTHING;
UPDATE crm_positions SET grants_customized = TRUE, updated_at = NOW()
WHERE lower(trim(code)) = 'super-admin';
"""
    )

    for code in CODES:
        grants = doc["grants_by_position"][code]
        rows = [(sid, str(a).lower()) for sid, acts in grants.items() for a in acts]
        lines.append(f"\n-- {code}")
        lines.append(
            f"""
DELETE FROM staff_section_permissions WHERE position_id = (
  SELECT id FROM crm_positions WHERE lower(trim(code)) = lower({sql_str(code)}) AND active LIMIT 1
);
INSERT INTO staff_section_permissions (position_id, section_id, action)
SELECT p.id, v.section_id, v.action
FROM crm_positions p
CROSS JOIN (VALUES
"""
        )
        lines.append(
            ",\n".join(f"  ({sql_str(sid)}, {sql_str(act)})" for sid, act in sorted(set(rows)))
        )
        lines.append(
            f"""
) AS v(section_id, action)
WHERE lower(trim(p.code)) = lower({sql_str(code)}) AND p.active
ON CONFLICT (position_id, section_id, action) DO NOTHING;
UPDATE crm_positions SET grants_customized = TRUE, updated_at = NOW()
WHERE lower(trim(code)) = lower({sql_str(code)});
INSERT INTO staff_permission_audit (actor_email, position_id, diff_json)
SELECT 'seed_rnosai_handover_rbac.sql', p.id,
  jsonb_build_object('source','rnosai_handover_rbac_grants.json','position_code', p.code)
FROM crm_positions p
WHERE lower(trim(p.code)) = lower({sql_str(code)}) AND p.active
LIMIT 1;
"""
        )

    lines.append("COMMIT;")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
