"""Manual BA use-case details — SEO/AEO Enterprise (SEO-UC-001 … SEO-UC-014)."""
from __future__ import annotations

from rnosai_ba_detail_helpers import uc_detail

SEO_USE_CASE_DETAILS: dict[str, dict] = {
    "SEO-UC-001": uc_detail(
        "SEO-UC-001",
        "Onboard client SEO workspace",
        screens="SCR-SEO-001, SCR-AGENCY-001",
        actor="SEO Strategist / AM",
        goal="Tạo SEO workspace gắn client_id sẵn sàng OAuth",
        trigger="HĐ có gói SEO/AEO SYS-UC-001",
        pre="Customer active; PTT_SEO_ENABLED=1",
        post="Workspace ready; hub tile visible /seo/hub",
        priority="P0",
        wave="Wave R1",
        trace="SYS-001",
        api="POST /seo/workspaces · /seo/hub client tile",
        main=[
            [1, "Tạo SEO workspace gắn client_id"],
            [2, "Nhập primary domain, locale, competitors"],
            [3, "Assign strategist owner"],
            [4, "Hub /seo/hub hiển thị client tile"],
            [5, "Enable OAuth steps SEO-UC-002/003 on checklist"],
        ],
        alt=[
            ["E1", "Domain mismatch later → block GSC sync SEO-UC-002"],
        ],
        io_in="client_id, domain, locale, competitor list",
        io_out="workspace_id, hub tile config",
        rules=["BR-SEO-001", "BR-SVC-002"],
    ),
    "SEO-UC-002": uc_detail(
        "SEO-UC-002",
        "OAuth GSC & sync",
        screens="SCR-SEO-001",
        actor="SEO Strategist / Tracking-Tech",
        goal="Google Search Console OAuth + daily sync queries/pages",
        trigger="Workspace created; strategist connects GSC",
        pre="Domain verification aligned with workspace domain",
        post="GSC data in warehouse; sync status on hub",
        priority="P0",
        wave="Wave R1",
        api="GSC OAuth callback · sync job daily",
        main=[
            [1, "Initiate Google Search Console OAuth"],
            [2, "Select property matching workspace domain"],
            [3, "Worker sync queries, pages, coverage daily"],
            [4, "Hub shows sync status + last run timestamp"],
            [5, "Errors surfaced on hub health widget"],
        ],
        alt=[
            ["E1", "Property mismatch → block sync; fix domain verification"],
            ["E2", "Token revoked → re-auth banner"],
        ],
        io_in="workspace_id, gsc_property_id, oauth tokens",
        io_out="sync_state, gsc metrics rows[], error log",
        rules=["BR-SEO-002"],
    ),
    "SEO-UC-003": uc_detail(
        "SEO-UC-003",
        "OAuth GA4 & sync",
        screens="SCR-SEO-001",
        actor="SEO Strategist",
        goal="GA4 OAuth + sync sessions, landing pages, conversions",
        trigger="GSC connected; strategist links GA4",
        pre="GA4 property access granted",
        post="GA4 linked; combined GSC+GA4 reports available",
        priority="P0",
        wave="Wave R1",
        api="GA4 OAuth · analytics sync worker",
        main=[
            [1, "Initiate GA4 OAuth flow"],
            [2, "Select property matching client site"],
            [3, "Worker sync sessions, landing pages, conversions"],
            [4, "Combine GSC+GA4 attribution on hub reports"],
            [5, "Display sync health on /seo/hub"],
        ],
        alt=[
            ["E1", "Property access denied → 403 with setup guide"],
        ],
        io_in="workspace_id, ga4_property_id, oauth tokens",
        io_out="analytics sync rows[], combined report datasets",
        rules=["BR-SEO-003"],
    ),
    "SEO-UC-004": uc_detail(
        "SEO-UC-004",
        "Research → import keywords",
        screens="SCR-SEO-003",
        actor="SEO Strategist",
        goal="Import keyword set với intent, cluster, priority",
        trigger="Research brief ready",
        pre="SEO workspace active",
        post="Keyword set versioned; pipeline topics assigned",
        priority="P0",
        wave="Wave R1",
        api="POST /seo/keywords/import · /seo/research",
        main=[
            [1, "Keyword research tool export hoặc CSV import"],
            [2, "Tag intent, cluster, priority per keyword"],
            [3, "Assign keywords to content pipeline topics"],
            [4, "Capture baseline rank SEO-UC-011"],
            [5, "Version keyword set per import batch"],
        ],
        alt=[
            ["E1", "CSV invalid columns → row-level error report"],
        ],
        io_in="CSV/research export, tagging metadata",
        io_out="keyword set version id, pipeline assignments",
        rules=["BR-SEO-004"],
    ),
    "SEO-UC-005": uc_detail(
        "SEO-UC-005",
        "Content pipeline stage advance",
        screens="SCR-SEO-002, SCR-PORTAL-006",
        actor="SEO Strategist / Content Writer",
        goal="Advance content Brief → Draft → Review → Client approval → Published",
        trigger="Content item created or stage action",
        pre="Content item exists in pipeline",
        post="Audit trail per stage; SLA tracked",
        priority="P0",
        wave="Wave R1",
        api="PATCH /seo/content/:id/stage · pipeline API",
        main=[
            [1, "Create content item: Brief → Draft → Review"],
            [2, "Advance stage with checklist per transition"],
            [3, "Submit client approval portal PORTAL-UC-007"],
            [4, "Governance check SEO-UC-006 before publish"],
            [5, "Scheduled → Published via SEO-UC-009 webhook"],
        ],
        alt=[
            ["E1", "Client reject → return Draft with comment"],
            ["E2", "Governance fail → block advance to Scheduled"],
        ],
        io_in="content_id, target_stage, checklist confirmations",
        io_out="stage audit[], SLA timestamps, approval status",
        rules=["BR-SEO-005", "BR-SEO-006", "BR-PORTAL-007"],
    ),
    "SEO-UC-006": uc_detail(
        "SEO-UC-006",
        "Governance block publish",
        screens="SCR-SEO-006, SCR-SEO-002",
        actor="Compliance / System",
        goal="Pre-publish evaluation block thin content, banned terms, E-E-A-T",
        trigger="Content advance to Scheduled/Publish",
        pre="Governance rules active per client vertical",
        post="No publish without pass or admin override",
        priority="P0",
        wave="Wave R1",
        api="POST governance evaluate · /seo/governance rules CRUD",
        main=[
            [1, "Pre-publish evaluation job runs on content item"],
            [2, "Check: thin content, missing meta, banned terms, E-E-A-T flags"],
            [3, "Block → writer must fix; log evaluation result"],
            [4, "Pass → allow CMS publish SEO-UC-009"],
            [5, "Admin override with audit reason optional pilot"],
        ],
        alt=[
            ["E1", "Rule update mid-flight → re-evaluate on next advance"],
        ],
        io_in="content_id, governance rule set version",
        io_out="evaluation pass/fail, violation list[], override audit?",
        rules=["BR-SEO-006"],
    ),
    "SEO-UC-007": uc_detail(
        "SEO-UC-007",
        "Technical audit & issue fix",
        screens="SCR-SEO-004",
        actor="SEO Strategist / Tracking-Tech",
        goal="Crawl audit → issue backlog → fix verify re-crawl",
        trigger="Scheduled crawl or manual audit run",
        pre="Site domain reachable from crawler",
        post="Issue backlog prioritized P0/P1/P2; closed issues verified",
        priority="P0",
        wave="Wave R1",
        api="POST /seo/technical/audit · issue fix workflow",
        main=[
            [1, "Run technical crawl audit on primary domain"],
            [2, "Generate issue list: 404, canonical, CWV, indexation"],
            [3, "Assign fix to dev/client owner"],
            [4, "Track status Open → In progress → Fixed"],
            [5, "Re-crawl verify closed; update hub health score"],
        ],
        alt=[
            ["E1", "Crawl blocked robots.txt → warn strategist"],
        ],
        io_in="domain, crawl config, issue assignments",
        io_out="audit report id, issue backlog[], fix verification",
        rules=["BR-SEO-007"],
    ),
    "SEO-UC-008": uc_detail(
        "SEO-UC-008",
        "AEO scan & coverage",
        screens="SCR-SEO-007",
        actor="SEO Strategist",
        goal="Scan AI answer surfaces; gap analysis vs competitors",
        trigger="AEO targets defined; periodic scan schedule",
        pre="AEO module enabled; competitor list from workspace",
        post="Coverage score visible; action items in hub",
        priority="P1",
        wave="Wave R2",
        api="POST /seo/aeo/scan · coverage reports",
        main=[
            [1, "Define AEO target queries and competitor set"],
            [2, "Run scan SGE/snippets/AI answer surfaces"],
            [3, "Gap analysis vs competitors on hub"],
            [4, "Generate action items linked content pipeline"],
            [5, "Track coverage score trend over time"],
        ],
        alt=[
            ["E1", "Scan API limit → queue retry"],
        ],
        io_in="target queries[], competitors[], scan scope",
        io_out="coverage score, gap report, action items[]",
        rules=["BR-SEO-008"],
    ),
    "SEO-UC-009": uc_detail(
        "SEO-UC-009",
        "CMS publish webhook",
        screens="SCR-SEO-002",
        actor="System",
        goal="Publish content to client CMS via webhook connector",
        trigger="Content stage Scheduled → publish time reached",
        pre="CMS webhook configured; governance pass SEO-UC-006",
        post="Published URL stored; freshness queue SEO-UC-010",
        priority="P1",
        wave="Wave R2",
        api="CMS connector webhook · publish confirm callback",
        main=[
            [1, "Scheduler triggers publish at scheduled_at"],
            [2, "Webhook POST to client CMS WordPress/custom"],
            [3, "Confirm HTTP 200 from CMS"],
            [4, "Update content status Published + live URL"],
            [5, "Optional sitemap ping; trigger freshness tracking"],
        ],
        alt=[
            ["E1", "CMS 5xx → retry 3x; alert strategist"],
            ["E2", "Partial publish → rollback status Draft"],
        ],
        io_in="content_id, CMS endpoint, payload HTML/markdown",
        io_out="published_url, publish audit, CMS response",
        rules=["BR-SEO-009", "BR-SEO-006"],
    ),
    "SEO-UC-010": uc_detail(
        "SEO-UC-010",
        "Freshness queue refresh",
        screens="SCR-SEO-002",
        actor="SEO Strategist",
        goal="Queue stale URLs >90d; track refresh before/after metrics",
        trigger="Daily job flags stale content",
        pre="Published URLs with last_updated metadata",
        post="Refresh queue populated; metrics tracked post-refresh",
        priority="P1",
        wave="Wave R2",
        api="GET /seo/content/freshness-queue · refresh workflow",
        main=[
            [1, "Job flag URLs stale >90 days without meaningful update"],
            [2, "Strategist reviews freshness queue on /seo/content"],
            [3, "Suggest refresh actions per URL"],
            [4, "Assign writer → advance pipeline refresh branch"],
            [5, "Track before/after GSC/GA4 metrics"],
        ],
        alt=[
            ["E1", "URL removed → mark archived skip refresh"],
        ],
        io_in="stale url list, refresh plan, assigned writer",
        io_out="refresh tasks[], metric delta report",
        rules=["BR-SEO-010"],
    ),
    "SEO-UC-011": uc_detail(
        "SEO-UC-011",
        "Rank tracker capture",
        screens="SCR-SEO-001, SCR-SEO-003",
        actor="System / SEO Strategist",
        goal="Daily rank pull for keyword set; delta alerts",
        trigger="Cron daily rank job",
        pre="Keywords tracked from SEO-UC-004",
        post="Rank history stored; charts on workspace",
        priority="P1",
        wave="Wave R2",
        api="rank tracker job · keyword detail charts",
        main=[
            [1, "Daily job pull ranks for tracked keyword set"],
            [2, "Store rank history per keyword URL pair"],
            [3, "Compute delta vs prior day/week"],
            [4, "Alert strategist on significant drop >N positions"],
            [5, "Render charts on /seo/hub client drill-down"],
        ],
        alt=[
            ["E1", "Rank provider timeout → retry slice"],
        ],
        io_in="keyword ids[], locale, device type",
        io_out="rank snapshots[], alert events[]",
        rules=["BR-SEO-011"],
    ),
    "SEO-UC-012": uc_detail(
        "SEO-UC-012",
        "Executive hub drill-down",
        screens="SCR-SEO-001",
        actor="GDKD / AM",
        goal="Hub client health drill ≤3 clicks SYS-UC-007",
        trigger="Executive opens /seo/hub",
        pre="Hub data synced GSC/GA4/content/issues",
        post="PO spec F5 satisfied; drill path audited",
        priority="P0",
        wave="Wave R1",
        trace="SYS-007, TC-SEO-01",
        api="GET /seo/hub · drill-down routes",
        main=[
            [1, "Mở /seo/hub executive tiles client health"],
            [2, "Click client tile → client workspace summary"],
            [3, "Drill issues / content / rank in ≤3 clicks total"],
            [4, "Export snapshot CSV optional"],
            [5, "Link portal SEO summary PORTAL-UC-004 read-only subset"],
        ],
        alt=[
            ["E1", "Stale sync → yellow badge on tile"],
        ],
        io_in="hub filters, client_id drill path",
        io_out="drill views[], export CSV",
        rules=["BR-SEO-012", "BR-SYS-007"],
    ),
    "SEO-UC-013": uc_detail(
        "SEO-UC-013",
        "Client PDF report export",
        screens="SCR-SEO-005, SCR-PORTAL-006",
        actor="SEO Strategist / AM",
        goal="Generate client PDF traffic/ranks/content for period",
        trigger="Reporting period closed SYS-UC-005",
        pre="GSC/GA4/rank data available for period",
        post="PDF on portal/email; download logged PORTAL-UC-010",
        priority="P0",
        wave="Wave R1",
        trace="SYS-005",
        api="POST /seo/reports/pdf · PDF worker · portal artifact",
        main=[
            [1, "Select reporting period on /seo/reports"],
            [2, "Preview metrics: traffic, ranks, content delivered"],
            [3, "Generate PDF client-safe template"],
            [4, "Upload to portal /seo or settings exports"],
            [5, "Optional email notify client viewer"],
        ],
        alt=[
            ["E1", "Incomplete data period → footnote in PDF"],
        ],
        io_in="client_id, period, report template options",
        io_out="PDF file URL, delivery audit",
        rules=["BR-SEO-013", "BR-SYS-005", "BR-PORTAL-010"],
    ),
    "SEO-UC-014": uc_detail(
        "SEO-UC-014",
        "ClickHouse BI export",
        screens="SCR-SEO-005",
        actor="Admin / BI / Data team",
        goal="Export SEO events to ClickHouse for Grafana dashboards",
        trigger="BI pipeline scheduled or manual export",
        pre="ClickHouse connected; export policy approved",
        post="BI export scheduled; status endpoint green",
        priority="P1",
        wave="Wave R3",
        api="ClickHouse pipeline · BI status endpoint · Grafana links",
        main=[
            [1, "Configure ClickHouse destination + table schema"],
            [2, "Export SEO events: content stages, ranks, audits"],
            [3, "Schedule incremental sync job"],
            [4, "Verify BI status endpoint returns healthy"],
            [5, "Link Grafana dashboards for agency leadership"],
        ],
        alt=[
            ["E1", "Schema migration → versioned export job"],
        ],
        io_in="export config, date watermark, event types[]",
        io_out="CH row counts, job run id, Grafana dashboard URLs",
        rules=["BR-SEO-014"],
    ),
}
