"""Deep SCR UI/API overrides — Portal module (portal-web)."""

PORTAL_SCR_OVERRIDES: dict[str, dict] = {
    "SCR-PORTAL-002": {
        "module_key": "PORTAL",
        "api": "POST /api/v1/portal/auth/login",
        "pre": "Public page — email/password hợp lệ",
        "post": "JWT saved → redirect /dashboard; archived tenant → /archived",
        "purpose": "Client portal login — scoped JWT + forgot password link",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "LoginCard", "Layout", "Có", "Centered card Client Portal MVP"],
            [2, "ResetSuccessBanner", "Alert", "Không", "?reset=ok post password reset"],
            [3, "EmailPasswordFields", "Form", "Có", "Required username/password"],
            [4, "SubmitButton", "Button", "Có", "Đăng nhập — loading state"],
            [5, "ForgotPasswordLink", "Link", "Có", "→ SCR-PORTAL-011"],
            [6, "ErrorMessage", "Alert", "Không", "Failed login inline"],
        ],
        "rules": ["BR-PORTAL-001", "BR-PLAT-003"],
    },
    "SCR-PORTAL-003": {
        "module_key": "PORTAL",
        "api": "GET /api/v1/portal/performance?channel=meta · export CSV/PDF",
        "pre": "Authenticated portal session; archived → /archived",
        "post": "Performance summary + table for T-7/T-30 window",
        "purpose": "Meta performance read-only — spend, leads, CPL, CSV export",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "Branding · nav · user role · logout"],
            [2, "SessionWarningBadge", "Badge", "Không", "Phiên sắp hết hạn"],
            [3, "PerformancePanelHeader", "Header", "Có", "Meta Performance subtitle"],
            [4, "WindowToggles", "Button", "Có", "T-7 / T-30"],
            [5, "GroupByToggles", "Button", "Có", "Theo ngày / Theo chiến dịch"],
            [6, "ExportButtons", "Button", "Có", "CSV + PDF export"],
            [7, "SummaryGrid", "KPI", "Có", "Spend · leads · CPL · unmapped spend"],
            [8, "PerformanceTable", "Table", "Có", "Rows + PortalAttributionFooter"],
        ],
        "rules": ["BR-PORTAL-003", "BR-META-013"],
    },
    "SCR-PORTAL-004": {
        "module_key": "PORTAL",
        "api": "GET pending/history creatives · POST approve/reject",
        "pre": "Authenticated; approve/reject cần role approver",
        "post": "Creative decision recorded with optional reject note",
        "purpose": "Creative approval inbox — Meta + Zalo assets",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "Pending count badge on nav"],
            [2, "TabBar", "Tabs", "Có", "Chờ duyệt · Lịch sử 30 ngày"],
            [3, "ViewerNotice", "Alert", "Không", "Viewer read-only on pending tab"],
            [4, "CreativeInbox", "List", "Có", "Preview · approve · reject modal"],
            [5, "CreativeHistoryList", "List", "Có", "Status badge · reviewer · note"],
            [6, "EmptyStates", "Alert", "Không", "No pending / no history"],
        ],
        "rules": ["BR-PORTAL-006", "BR-PORTAL-009"],
    },
    "SCR-PORTAL-005": {
        "module_key": "PORTAL",
        "api": "GET portalEmailDashboard · portalMe",
        "pre": "Token + portalMe; email_enabled workspace flag",
        "post": "Email KPI widgets + recent campaigns list",
        "purpose": "Email stats hub — metrics + link to approvals (approver)",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "Email nav when enabled"],
            [2, "DashboardHeader", "Header", "Có", "EM-4 label · Approval inbox link (approver)"],
            [3, "FeatureDisabledError", "Alert", "Không", "email_enabled off"],
            [4, "EmailWidgetsPanel", "KPI", "Có", "Pending/sent/open rate/revenue"],
            [5, "RecentCampaignsList", "List", "Có", "Links → SCR-PORTAL-015"],
        ],
        "rules": ["BR-PORTAL-005", "BR-EM-007"],
    },
    "SCR-PORTAL-006": {
        "module_key": "PORTAL",
        "api": "GET portalSeoSummary · portalMe",
        "pre": "Token; seo_enabled + mapped via usePortalSeoNav",
        "post": "SEO widget metrics + quick links rendered",
        "purpose": "SEO summary hub — sparkline widgets + drill-down links",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "SEO/AEO/reports/content when enabled"],
            [2, "FeatureDisabledError", "Alert", "Không", "SEO not enabled"],
            [3, "SeoWidgetsPanel", "KPI", "Có", "Dynamic metrics + sparkline SVG"],
            [4, "QuickLinks", "Nav", "Có", "→ reports · content review"],
        ],
        "rules": ["BR-PORTAL-004", "BR-SEO-013"],
    },
    "SCR-PORTAL-007": {
        "module_key": "PORTAL",
        "api": "GET portal performance channel=zalo · export",
        "pre": "Authenticated portal session",
        "post": "Zalo KPI table + CSV/PDF export",
        "purpose": "Zalo Ads performance read-only — CPL KPI + export",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "Standard shell"],
            [2, "PerformancePanel", "Panel", "Có", "channel=zalo · T-7/T-30 · group-by"],
            [3, "ExportButtons", "Button", "Có", "CSV/PDF Z3-6"],
            [4, "SummaryGrid", "KPI", "Có", "Spend · leads · CPL"],
            [5, "PerformanceTable", "Table", "Có", "Zalo-specific rows"],
        ],
        "rules": ["BR-PORTAL-013", "BR-ZALO-005"],
    },
    "SCR-PORTAL-008": {
        "module_key": "PORTAL",
        "api": "GET portal performance channel=google",
        "pre": "Authenticated portal session",
        "post": "Google ads summary displayed (in progress v0.9)",
        "purpose": "Google Ads performance read-only summary",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "Standard shell"],
            [2, "PerformancePanel", "Panel", "Có", "channel=google"],
            [3, "WindowGroupExport", "Toolbar", "Có", "Same as Meta/Zalo pattern"],
            [4, "SummaryGrid", "KPI", "Có", "Google spend/leads metrics"],
            [5, "PerformanceTable", "Table", "Có", "Campaign/day breakdown"],
        ],
        "rules": ["BR-PORTAL-015"],
    },
    "SCR-PORTAL-009": {
        "module_key": "PORTAL",
        "api": "GET notifications · PATCH mark read · mark all read",
        "pre": "Authenticated portal session",
        "post": "Notifications filtered; read state updated",
        "purpose": "Notification center — milestones + pending approvals",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "Unread badge count"],
            [2, "FilterToggles", "Tabs", "Có", "Tất cả · Chưa đọc"],
            [3, "MarkAllReadButton", "Button", "Không", "When unread > 0"],
            [4, "NotificationCardList", "List", "Có", "Category badge · title · body · timestamp"],
            [5, "ItemActions", "Button", "Có", "Mở link_url · Đã đọc"],
            [6, "TableNotReadyNotice", "Alert", "Không", "When table_ready false"],
        ],
        "rules": ["BR-PORTAL-010"],
    },
    "SCR-PORTAL-010": {
        "module_key": "PORTAL",
        "api": "GET/PATCH portal settings · POST change password",
        "pre": "Authenticated; branding edit approver only",
        "post": "Settings saved; password changed",
        "purpose": "Profile settings — branding (approver) + change password (all)",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "Standard shell"],
            [2, "BrandingSection", "Form", "Không", "Display name · logo URL · AM contact — approver"],
            [3, "ViewerRestrictionNotice", "Alert", "Không", "Viewer cannot edit branding"],
            [4, "SaveSettingsButton", "Button", "Không", "Approver only"],
            [5, "ChangePasswordSection", "Form", "Có", "Current/new/confirm min 8 chars — all roles"],
            [6, "PdfExportStubNote", "Alert", "Không", "Phase 4 placeholder"],
        ],
        "rules": ["BR-PORTAL-010", "BR-PORTAL-012"],
    },
    "SCR-PORTAL-011": {
        "module_key": "PORTAL",
        "api": "POST portalForgotPassword",
        "pre": "Public — valid email",
        "post": "Reset email queued; dev may show reset_url",
        "purpose": "Self-serve forgot password — GAP-P0-02",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "ForgotPasswordCard", "Layout", "Có", "Centered card"],
            [2, "EmailInput", "Input", "Có", "Required email"],
            [3, "SubmitButton", "Button", "Có", "Gửi link đặt lại"],
            [4, "SuccessErrorMessages", "Alert", "Có", "API response display"],
            [5, "BackToLoginLink", "Link", "Có", "→ SCR-PORTAL-002"],
        ],
        "rules": ["BR-PORTAL-011", "BR-PLAT-003"],
    },
    "SCR-PORTAL-012": {
        "module_key": "PORTAL",
        "api": "GET validate reset token · POST reset password",
        "pre": "Public — valid ?token= query",
        "post": "Password updated → /login?reset=ok",
        "purpose": "Tokenized password reset completion",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "ResetPasswordCard", "Layout", "Có", "Centered card"],
            [2, "TokenValidationLoader", "Alert", "Có", "Đang kiểm tra link…"],
            [3, "NewPasswordFields", "Form", "Có", "New + confirm min 8 chars"],
            [4, "InvalidTokenPanel", "Alert", "Không", "Expired/used + request new link"],
            [5, "SubmitButton", "Button", "Có", "Lưu mật khẩu mới"],
        ],
        "rules": ["BR-PORTAL-011"],
    },
    "SCR-PORTAL-013": {
        "module_key": "PORTAL",
        "api": "None — clearSession only",
        "pre": "Redirect after archived tenant login error",
        "post": "Session cleared; user can re-login",
        "purpose": "Archived client offboard landing page",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "ArchivedCard", "Layout", "Có", "Badge Client archived"],
            [2, "ExplanationText", "Alert", "Có", "Portal đã đóng message"],
            [3, "PrimaryCta", "Button", "Có", "Về trang đăng nhập — clears session"],
            [4, "SecondaryLoginLink", "Link", "Không", "Đăng nhập tài khoản khác"],
        ],
        "rules": ["BR-PORTAL-001", "BR-SYS-006"],
    },
    "SCR-PORTAL-014": {
        "module_key": "PORTAL",
        "api": "GET pending approvals · POST approve/reject · GET preview HTML",
        "pre": "Authenticated; approve/reject approver role",
        "post": "Campaign approval decision recorded",
        "purpose": "Email campaign approval inbox EM-8b P-EMAIL-02",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "Approvals nav approver only"],
            [2, "InboxHeader", "Header", "Có", "EM-8b P-EMAIL-02 label"],
            [3, "ApproverNotice", "Alert", "Không", "Viewer read-only list"],
            [4, "EmailApprovalCardList", "List", "Có", "Preview · approve · reject per campaign"],
            [5, "PreviewModal", "Modal", "Không", "HTML email preview"],
            [6, "RejectModal", "Modal", "Không", "Note textarea + confirm"],
        ],
        "rules": ["BR-PORTAL-008", "BR-EM-007"],
    },
    "SCR-PORTAL-015": {
        "module_key": "PORTAL",
        "api": "GET portalEmailCampaignStats(campaignId)",
        "pre": "Authenticated; email module enabled",
        "post": "Campaign stats grid displayed",
        "purpose": "Email campaign metrics drill-down EM-4 P-EMAIL-03",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "Campaign performance title"],
            [2, "BackLink", "Link", "Có", "← /email"],
            [3, "CampaignTitle", "Header", "Có", "campaign_name heading"],
            [4, "StatusBadge", "Badge", "Có", "Campaign status"],
            [5, "StatsGrid", "KPI", "Có", "Audience/sent/opens/clicks/rates/revenue"],
        ],
        "rules": ["BR-PORTAL-005"],
    },
    "SCR-PORTAL-016": {
        "module_key": "PORTAL",
        "api": "GET portalSeoExecutiveReport(tab)",
        "pre": "Authenticated; seo_enabled; ?tab= query",
        "post": "Report sections loaded read-only",
        "purpose": "SEO/AEO executive reports — PDF-style tabs",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "SEO reports link"],
            [2, "ReportTabNav", "Tabs", "Có", "Executive/SEO/AEO/Kỹ thuật/Nội dung"],
            [3, "GscStatGrid", "KPI", "Có", "Clicks/impressions/CTR/queries"],
            [4, "AeoCoverageStat", "KPI", "Có", "Coverage % visible/total"],
            [5, "ContentPipelineList", "List", "Có", "Status → count"],
            [6, "TechnicalIssuesTable", "Table", "Không", "URL/type/severity/status"],
            [7, "AiMentionsList", "List", "Không", "30d citation counts"],
        ],
        "rules": ["BR-PORTAL-004", "BR-SEO-013"],
    },
    "SCR-PORTAL-017": {
        "module_key": "PORTAL",
        "api": "GET portalSeoPendingContent",
        "pre": "Authenticated; seo enabled; approver for actions on detail",
        "post": "Pending client_review content list",
        "purpose": "SEO content approval queue — link to detail",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "Content review badge"],
            [2, "SectionHeader", "Header", "Có", "Nội dung chờ duyệt client review"],
            [3, "ViewerNotice", "Alert", "Không", "Viewer — chỉ xem"],
            [4, "PendingContentList", "List", "Có", "Title links → SCR-PORTAL-018"],
            [5, "EmptyState", "Alert", "Không", "Không có nội dung chờ duyệt"],
        ],
        "rules": ["BR-PORTAL-007"],
    },
    "SCR-PORTAL-018": {
        "module_key": "PORTAL",
        "api": "GET content detail · POST portalSeoReviewContent",
        "pre": "Authenticated; approve/reject approver + status client_review",
        "post": "Approval decision recorded; redirect to list",
        "purpose": "SEO content preview + client approve/reject PORTAL-UC-007",
        "app": "portal-web (portal.pttads.vn)",
        "ui": [
            [1, "PortalNav", "Navigation", "Có", "Standard SEO nav"],
            [2, "ContentHeader", "Header", "Có", "Title · workflow status · content type"],
            [3, "MetaBriefBlock", "Panel", "Có", "Meta title/description from brief"],
            [4, "BodyHtmlPreview", "Preview", "Có", "Rendered body_html container"],
            [5, "ApprovalTimeline", "Timeline", "Có", "Stage/status/actor list"],
            [6, "ApproveRejectButtons", "Button", "Không", "Optional notes prompt — approver only"],
        ],
        "rules": ["BR-PORTAL-007", "BR-SEO-006"],
    },
}
