"""Manual BA use-case details — Agency Service Delivery (SVC-UC-001 … SVC-UC-012)."""
from __future__ import annotations

from rnosai_ba_detail_helpers import uc_detail

SVC_USE_CASE_DETAILS: dict[str, dict] = {
    "SVC-UC-001": uc_detail(
        "SVC-UC-001",
        "Workflow lifecycle 7 stage",
        screens="SCR-SVC-004, SCR-AGENCY-001",
        actor="AM / PM",
        actor_secondary="Strategist, Finance",
        goal="Theo dõi lifecycle client 7 giai đoạn agency",
        trigger="Customer convert / HĐ active",
        pre="Customer record exists; service line selected from HĐ",
        post="Stage history immutable log; badge visible on agency hub",
        priority="P0",
        wave="Wave R1",
        api="GET/PATCH /agency/clients/:id/lifecycle · lifecycle API",
        main=[
            [1, "System khởi tạo lifecycle: Prospect → Onboard → Deliver → Optimize → Handover → Retain → Offboarding"],
            [2, "AM chuyển stage manual hoặc auto khi checklist gate pass"],
            [3, "Mỗi stage có gate items (SVC-UC-002…004)"],
            [4, "Hub /agency/clients/[id] hiển thị stage badge"],
            [5, "Audit mọi stage transition với actor + timestamp"],
        ],
        alt=[
            ["E1", "Skip stage pilot → Admin override + audit reason bắt buộc"],
            ["E2", "Deliver blocked nếu onboard incomplete BR-SVC-001"],
        ],
        io_in="client_id, target_stage, override_reason?",
        io_out="lifecycle_state, stage_history[]",
        rules=["BR-SVC-001", "BR-SVC-002"],
    ),
    "SVC-UC-002": uc_detail(
        "SVC-UC-002",
        "Onboard checklist client",
        screens="SCR-AGENCY-001, SCR-AGENCY-002",
        actor="AM / Tracking-Tech",
        goal="Hoàn tất onboard checklist trước go-live module",
        trigger="Lifecycle stage = Onboard",
        pre="New client record created SYS-UC-001",
        post="100% required items pass; gate cleared for Deliver",
        priority="P0",
        wave="Wave R1",
        trace="SYS-001",
        api="GET/PATCH onboard checklist · /agency/clients/new wizard",
        main=[
            [1, "Mở onboard checklist template theo service bundle"],
            [2, "Items: legal docs, billing, ad account, pixel, GSC, email domain, portal users"],
            [3, "Mark done per item; attach evidence links"],
            [4, "Orchestrator deep-links per module (Meta, Zalo, SEO, EM)"],
            [5, "Complete onboard khi 100% required items pass"],
        ],
        alt=[
            ["E1", "Optional item skip → yellow state with AM sign-off"],
        ],
        io_in="client_id, checklist item statuses[], evidence URLs",
        io_out="checklist completion audit, module enable flags",
        rules=["BR-SVC-002", "BR-SYS-001"],
    ),
    "SVC-UC-003": uc_detail(
        "SVC-UC-003",
        "Deliver stage — TMMT chính thức",
        screens="SCR-SVC-004",
        actor="AM / PM / Media Buyer",
        goal="Publish TMMT và go-live campaign đầu tiên",
        trigger="Onboard complete; first campaign ready",
        pre="SVC-UC-002 complete; Launch QA eligible",
        post="Client officially in delivery; TMMT versioned; hypercare clock start",
        priority="P0",
        wave="Wave R1",
        api="TMMT doc store · PATCH lifecycle stage Deliver",
        main=[
            [1, "AM chuyển lifecycle → Deliver"],
            [2, "Publish TMMT (tài liệu mục tiêu marketing) trên client workspace"],
            [3, "Launch QA SVC-UC-005 + first campaign SYS-UC-003"],
            [4, "Hypercare clock start SYS-UC-012"],
            [5, "Notify client portal milestone optional"],
        ],
        alt=[
            ["E1", "TMMT revision → version bump v2, v3…"],
        ],
        io_in="client_id, TMMT document, campaign launch refs",
        io_out="TMMT version id, deliver milestone audit",
        rules=["BR-SVC-003", "BR-SVC-005", "BR-SYS-003"],
    ),
    "SVC-UC-004": uc_detail(
        "SVC-UC-004",
        "Handover → Retain + finance gate",
        screens="SCR-CRM-018, SCR-CRM-019, SCR-AGENCY-001",
        actor="AM / Finance",
        goal="Handover pack + finance verify → Retain steady-state",
        trigger="Deliver period end; KPI stable",
        pre="Delivery complete; billing data synced RNOS-25",
        post="Retain playbook active; AM primary contact documented",
        priority="P0",
        wave="Wave R1",
        trace="RNOS-25",
        api="GET/POST /crm/orders · /crm/invoices · handover forms",
        main=[
            [1, "AM compile handover pack: reports, SOP, contacts"],
            [2, "Finance verify billing current CRM-UC-011; check invoice overdue"],
            [3, "Stage → Handover → client sign-off meeting recorded"],
            [4, "Create/update crm_orders + crm_invoices if pending RNOS-25"],
            [5, "Stage → Retain — steady-state SLA playbook"],
        ],
        alt=[
            ["E1", "Outstanding invoice → block Handover until paid"],
            ["E2", "Partial handover → retain with open finance ticket"],
        ],
        io_in="client_id, handover checklist, invoice status",
        io_out="lifecycle Retain, order/invoice records, sign-off audit",
        rules=["BR-SVC-004", "BR-CRM-011"],
    ),
    "SVC-UC-005": uc_detail(
        "SVC-UC-005",
        "Launch QA checklist",
        screens="SCR-SVC-001",
        actor="Media Buyer / Creative Lead",
        goal="Pre-launch QA gate: UTM, pixel, LP, creative, budget",
        trigger="Pre-launch campaign trên Meta/Zalo/Google",
        pre="Campaign draft ready; creative approved path",
        post="QA record linked to campaign write job",
        priority="P0",
        wave="Wave R1",
        trace="SYS-003",
        api="GET/PATCH /crm/launch-qa · Launch QA API · export PDF sign-off",
        main=[
            [1, "Mở /crm/launch-qa cho client/campaign"],
            [2, "Verify: UTM, pixel, landing page, creative spec, budget cap, audience"],
            [3, "Pass/Fail per item; block launch on critical fail (configurable)"],
            [4, "Export QA sign-off PDF"],
            [5, "Link QA record → META-UC-007 / ZALO launch path"],
        ],
        alt=[
            ["E1", "Critical fail → block campaign write queue submit"],
            ["E2", "Waive fail → GDKD override with reason"],
        ],
        io_in="client_id, campaign_id, QA checklist items[]",
        io_out="QA pass/fail record, PDF artifact, gate flag",
        rules=["BR-SVC-005", "BR-META-007"],
    ),
    "SVC-UC-006": uc_detail(
        "SVC-UC-006",
        "Creative Hub upload & review",
        screens="SCR-SVC-003, SCR-PORTAL-004",
        actor="Creative Lead",
        actor_secondary="Client Approver",
        goal="Upload creative assets + internal review + client approval",
        trigger="Brief approved; creative production start",
        pre="Client/campaign context set",
        post="Approved assets available in Ads wizard; version control",
        priority="P0",
        wave="Wave R1",
        api="POST /crm/creatives · asset API · portal approval PORTAL-UC-006",
        main=[
            [1, "Upload assets image/video/copy → Creative Hub /crm/creatives"],
            [2, "Tag client, campaign, format 1:1, 9:16, …"],
            [3, "Internal review → status Approved internal"],
            [4, "Submit client approval portal /creatives PORTAL-UC-006"],
            [5, "Approved assets unlock META-UC-007 / ZALO-UC-008 wizard"],
        ],
        alt=[
            ["E1", "Client reject → revision loop with comment PORTAL-UC-009"],
            ["E2", "Asset expiry date optional flag on version"],
        ],
        io_in="creative files[], metadata tags, review notes",
        io_out="creative version ids, approval status, audit trail",
        rules=["BR-SVC-006", "BR-PORTAL-006"],
    ),
    "SVC-UC-007": uc_detail(
        "SVC-UC-007",
        "Campaign Write queue approval",
        screens="SCR-SVC-002, SCR-META-004",
        actor="Media Buyer / GDKD",
        goal="Governance queue trước Meta API create/edit",
        trigger="Submit campaign create/edit wizard",
        pre="Launch QA passed for create; policy rules configured",
        post="Audit submitter, approvers, Meta API response ids",
        priority="P0",
        wave="Wave R1",
        api="/crm/campaign-writes · Temporal PLAT-UC-008 · Meta Marketing API",
        main=[
            [1, "Buyer submit ads-ops wizard → job Campaign Write queue"],
            [2, "Policy check: budget threshold → GDKD approve required"],
            [3, "Temporal workflow orchestrate approval steps"],
            [4, "Approved → Meta API execute create/edit"],
            [5, "Failed → retry/alert buyer; audit response ids"],
        ],
        alt=[
            ["E1", "Meta API error → job status failed; buyer fix resubmit"],
            ["E2", "Reject → comment to buyer; draft remains editable"],
        ],
        io_in="write job payload, budget, approver chain",
        io_out="job status, Meta external ids, approval audit",
        rules=["BR-SVC-007", "BR-META-008", "BR-PLAT-008"],
    ),
    "SVC-UC-008": uc_detail(
        "SVC-UC-008",
        "Map channel account (Meta/Google)",
        screens="SCR-META-001, SCR-GOOGLE-001, SCR-AGENCY-001",
        actor="AM / Tracking-Tech",
        goal="Link Meta/Google ad account → client unique mapping",
        trigger="Onboard channel step or settings update",
        pre="OAuth credentials available",
        post="client_id ↔ ad_account_id mapping unique; sync workers enabled",
        priority="P0",
        wave="Wave R1",
        api="POST /clients/:id/channel-accounts · META-UC-001 · Google sync",
        main=[
            [1, "Agency client settings → Channel accounts tab"],
            [2, "Link Meta ad account id / Google Ads customer id"],
            [3, "OAuth flow → verify token valid"],
            [4, "Enable sync workers insights daily"],
            [5, "Hub reflects connected status green"],
        ],
        alt=[
            ["E1", "Token invalid → red status + re-auth banner"],
            ["E2", "Account already mapped other client → 409 conflict"],
        ],
        io_in="client_id, channel, external_account_id, oauth tokens",
        io_out="channel_account row, sync enable flag",
        rules=["BR-SVC-008", "BR-META-001"],
    ),
    "SVC-UC-009": uc_detail(
        "SVC-UC-009",
        "Agency ingest monitor",
        screens="SCR-AGENCY-004",
        actor="Admin / DevOps / Tracking-Tech",
        goal="Monitor webhook volume, error rate, lag per channel",
        trigger="DevOps daily check or incident SYS-UC-008",
        pre="Webhooks configured PLAT-UC-004/005/006",
        post="Failed payloads replayable; SLA visible",
        priority="P1",
        wave="Wave R2",
        api="GET /agency/ingest · webhook metrics · replay API",
        main=[
            [1, "Mở /agency/ingest dashboard"],
            [2, "View volume, error rate, lag per channel Meta/Zalo/Email"],
            [3, "Drill failed payload sample (no PII prod log)"],
            [4, "Replay failed webhook with audit"],
            [5, "Alert if SLA breach → SYS-UC-008 incident"],
        ],
        alt=[
            ["E1", "Replay duplicate → idempotency skip"],
        ],
        io_in="channel filter, time range, failed job ids",
        io_out="metrics dashboard, replay results, incident tickets",
        rules=["BR-SVC-009", "BR-SYS-008", "BR-PLAT-004"],
    ),
    "SVC-UC-010": uc_detail(
        "SVC-UC-010",
        "KPI definitions agency-wide",
        screens="SCR-AGENCY-003",
        actor="Admin / GDKD",
        goal="Define KPI formulas agency-wide consumed by hub widgets",
        trigger="Admin configure KPI catalog",
        pre="KPI dictionary seed available",
        post="Hub/reports use consistent CPL, ROAS, rank delta formulas",
        priority="P1",
        wave="Wave R2",
        api="KPI config admin · kpi-dictionary-seed.sql",
        main=[
            [1, "Admin mở agency hub KPI settings"],
            [2, "Define formulas: CPL, ROAS, rank delta, SLA breach rate"],
            [3, "Assign KPI visibility per role"],
            [4, "Hub widgets Meta/Zalo/SEO consume definitions"],
            [5, "Version KPI config changes with audit"],
        ],
        alt=[
            ["E1", "Invalid formula → validation error on save"],
        ],
        io_in="KPI code, formula expression, role visibility",
        io_out="KPI catalog version, widget binding",
        rules=["BR-SVC-010"],
    ),
    "SVC-UC-011": uc_detail(
        "SVC-UC-011",
        "SOP & marketing plan",
        screens="SCR-SVC-004, SCR-AGENCY-001",
        actor="AM / Strategist",
        goal="Upload SOP + quarterly marketing plan linked lifecycle Optimize",
        trigger="Client enter Optimize stage or quarterly planning",
        pre="Client active in Deliver/Optimize",
        post="Documents versioned on client workspace",
        priority="P1",
        wave="Wave R2",
        api="client workspace documents API",
        main=[
            [1, "Upload SOP per client service line"],
            [2, "Fill quarterly marketing plan template"],
            [3, "Link documents to lifecycle stage Optimize"],
            [4, "AM review with client optional portal share"],
            [5, "Track plan vs actual KPI on hub"],
        ],
        alt=[
            ["E1", "Plan overdue → reminder task to AM"],
        ],
        io_in="client_id, document files, plan period, KPI targets",
        io_out="document version ids, plan status",
        rules=["BR-SVC-011"],
    ),
    "SVC-UC-012": uc_detail(
        "SVC-UC-012",
        "Offboarding SOP",
        screens="SCR-AGENCY-001",
        actor="AM / Admin",
        goal="Offboard checklist: revoke access, export data, archive",
        trigger="HĐ terminate SYS-UC-006",
        pre="Offboard request approved",
        post="All tokens revoked; client read-only archive",
        priority="P1",
        wave="Wave R2",
        trace="SYS-006",
        api="offboarding checklist · token revoke · archive API",
        main=[
            [1, "Trigger lifecycle → Offboarding"],
            [2, "Checklist: revoke OAuth, portal users, webhook endpoints"],
            [3, "Export client data package for compliance"],
            [4, "Final report deliver to client"],
            [5, "Stage → Archived; read-only retention policy"],
        ],
        alt=[
            ["E1", "Outstanding legal hold → delay archive"],
        ],
        io_in="client_id, offboard reason, checklist completions",
        io_out="archive state, export bundle URL, revoke audit",
        rules=["BR-SVC-012", "BR-SYS-006"],
    ),
}
