"""Deep SCR UI/API overrides — SEO module."""

SEO_SCR_OVERRIDES: dict[str, dict] = {
    "SCR-SEO-002": {
        "api": "GET /api/v1/seo/content/pipeline",
        "pre": "canViewSeoContent (crm_seo.view or section view)",
        "post": "Kanban 10 columns loaded for client/view filter",
        "purpose": "Content pipeline Kanban 10 cột — stage advance, overdue badge",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar SEO"],
            [2, "PageHeader", "Header", "Có", "Pipeline + links Research/Hub"],
            [3, "ClientFilter", "Select", "Có", "?customer_id= sync"],
            [4, "ViewFilter", "Select", "Có", "Full/Review only/Cần refresh ?view="],
            [5, "KanbanBoard", "Board", "Có", "10 columns horizontal scroll"],
            [6, "PipelineCard", "Card", "Có", "Title link → detail · status · due · overdue"],
            [7, "EmptyColumn", "Alert", "Không", "Trống per column"],
        ],
        "rules": ["BR-SEO-005", "BR-SEO-006"],
    },
    "SCR-SEO-003": {
        "api": "GET research console · POST keywords/questions/clusters · import CSV · brief preview · GSC sync · SERP capture",
        "pre": "canViewSeoResearch; write actions cần canWriteSeo",
        "post": "Research data imported/created; brief → pipeline",
        "purpose": "Research console 7-tab — keywords, AEO questions, SERP, pages",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "FilterToolbar", "Toolbar", "Có", "Client · search · intent (keywords tab)"],
            [3, "ResearchTabBar", "Tabs", "Có", "7 tabs Keywords→Opportunities"],
            [4, "WriteActionButtons", "Toolbar", "Không", "Import CSV · +Keyword · Capture SERP · Sync GSC"],
            [5, "KeywordsTable", "Table", "Có", "phrase/volume/KD/intent · → Brief"],
            [6, "QuestionsTable", "Table", "Có", "AEO questions · → Brief"],
            [7, "BriefPreviewModal", "Modal", "Không", "JSON brief · Tạo content → Pipeline"],
        ],
        "rules": ["BR-SEO-004"],
    },
    "SCR-SEO-004": {
        "api": "GET technical issues/CWV/crawl · PATCH issue · import CSV · upsert crawl schedule",
        "pre": "canViewSeoTechnical; write cần canWriteSeoTechnical",
        "post": "Issues updated; CWV captured; crawl schedule saved",
        "purpose": "Technical console S-09 — issues matrix, CWV, crawl webhook Gate E2",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "FilterToolbar", "Toolbar", "Có", "Client · severity · status · Import CSV"],
            [3, "SeverityMatrix", "KPI", "Có", "Count per severity + total"],
            [4, "CwvPanel", "Panel", "Có", "Capture CWV + URL table LCP/INP/CLS"],
            [5, "CrawlConnectorPanel", "Form", "Không", "Webhook URL/secret/frequency Gate E2"],
            [6, "IssuesTable", "Table", "Có", "URL/type/severity/status · action buttons"],
        ],
        "rules": ["BR-SEO-007"],
    },
    "SCR-SEO-005": {
        "api": "GET dashboard/schedules/alerts/attribution · download export CSV",
        "pre": "canViewSeoReports",
        "post": "KPI/charts loaded per dashboard type; CSV export",
        "purpose": "Reporting center S-12 — executive dashboards + schedules + alerts",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "DashboardTypeSelect", "Select", "Có", "Executive/SEO/Content/Technical/AEO/Ops"],
            [3, "KpiCardsGrid", "KPI", "Có", "GSC clicks/impressions · AEO · alerts · content"],
            [4, "SeoGscTrendChart", "Chart", "Có", "28-day GSC trend line"],
            [5, "BarCharts", "Chart", "Không", "Content by status · issues by severity"],
            [6, "AttributionPanel", "Panel", "Không", "GA4 organic sessions/conversions/revenue"],
            [7, "ReportSchedulesTable", "Table", "Không", "Cadence · recipients · next run"],
            [8, "OpenAlertsList", "List", "Không", "Severity + message + deep link"],
        ],
        "rules": ["BR-SEO-013", "BR-SEO-012"],
    },
    "SCR-SEO-006": {
        "api": "GET governance status/policies/compliance",
        "pre": "canViewSeoGovernance (settings configure OR approve)",
        "post": "Compliance KPI 7d visible per client",
        "purpose": "Governance hub S-14 — policies + compliance pass rate",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "ClientFilter", "Select", "Có", "Client scope"],
            [3, "GovernanceStatusBadge", "Badge", "Có", "ON/OFF per client"],
            [4, "ComplianceKpiCards", "KPI", "Có", "Evaluations/passed/failed/pass rate 7d"],
            [5, "PoliciesTable", "Table", "Có", "Key/name/rule type/severity/active"],
            [6, "InfoCard", "Alert", "Có", "Runs on content status transitions"],
        ],
        "rules": ["BR-SEO-006"],
    },
    "SCR-SEO-007": {
        "api": "GET AEO console · POST query · enqueue/sync scan",
        "pre": "canViewSeoAeo; write cần canWriteSeo",
        "post": "Queries tracked; scan queued/synced",
        "purpose": "AEO console S-10 — coverage % + query visibility scan",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "CoverageBar", "KPI", "Có", "visible/total coverage %"],
            [3, "ScanButtons", "Button", "Không", "Batch scan queue · Scan sync stub"],
            [4, "AddQueryForm", "Form", "Không", "Query + brand name — write only"],
            [5, "QueriesTable", "Table", "Có", "visible ✓/— · citation · last scan"],
        ],
        "rules": ["BR-SEO-008"],
    },
    "SCR-SEO-008": {
        "api": "GET rank keywords · POST track · capture ranks · import CSV",
        "pre": "canViewSeoRanks; write cần canWriteSeo",
        "post": "Keywords tracked; SOV summary updated",
        "purpose": "Rank tracker S-17 — SOV % + SERP position history",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "SovSummary", "KPI", "Có", "SOV % · in-top-N / tracked"],
            [3, "CaptureImportToolbar", "Toolbar", "Không", "Capture ranks stub · Import CSV"],
            [4, "TrackKeywordForm", "Form", "Không", "Phrase + Track keyword"],
            [5, "KeywordsTable", "Table", "Có", "Phrase · position · date · target URL"],
        ],
        "rules": ["BR-SEO-011"],
    },
    "SCR-SEO-009": {
        "api": "GET freshness queue · POST rescore",
        "pre": "canViewSeoFreshness; rescore cần canWriteSeo",
        "post": "Queue sorted by decay; rescore recomputes",
        "purpose": "Freshness queue — decay score priority refresh",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "PriorityFilter", "Select", "Có", "All/Low+/Medium+/High+/Urgent"],
            [3, "RescoreButton", "Button", "Không", "Rescore all — write cap"],
            [4, "QueueTable", "Table", "Có", "Title link · decay · priority · age · status"],
            [5, "EmptyState", "Alert", "Không", "Queue trống — chạy rescore"],
        ],
        "rules": ["BR-SEO-010"],
    },
    "SCR-SEO-010": {
        "api": "GET bi status/dashboard/parity · GET attribution · POST clickhouse export",
        "pre": "canViewSeoBi (settings configure OR reports view)",
        "post": "BI parity sample + GSC trend; export queued",
        "purpose": "SEO BI Gate D — ClickHouse export + Grafana path + parity",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "InfraStatusPanel", "Panel", "Có", "ClickHouse/BI/CWV/SERP flags"],
            [3, "ExportFactsButton", "Button", "Không", "exportSeoClickhouse"],
            [4, "GscTrendPanel", "Table", "Có", "28d totals + daily rows"],
            [5, "BiParityPanel", "Panel", "Không", "7-day sample JSON totals"],
            [6, "AttributionJsonPanel", "Panel", "Không", "Organic attribution per client"],
        ],
        "rules": ["BR-SEO-014"],
    },
    "SCR-SEO-011": {
        "api": "GET/POST cms target · GET jobs · POST test webhook",
        "pre": "canViewSeoCms (settings OR technical write)",
        "post": "CMS target saved; webhook tested; jobs listed",
        "purpose": "CMS auto-publish pilot Gate E5 — webhook + job history",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "ClientSelect", "Select", "Có", "Per-client CMS config"],
            [3, "CmsTargetForm", "Form", "Có", "CMS type · webhook URL · Active"],
            [4, "SaveTestButtons", "Button", "Có", "Save target · Test webhook"],
            [5, "PublishJobsTable", "Table", "Có", "content_id · status · remote URL"],
        ],
        "rules": ["BR-SEO-009"],
    },
    "SCR-SEO-012": {
        "api": "GET /api/v1/seo/clients",
        "pre": "canViewSeoHub",
        "post": "Client roster with health/settings status",
        "purpose": "Danh sách SEO client workspaces — health tier drill-down",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "BreadcrumbCard", "Nav", "Có", "SEO clients · back Hub"],
            [3, "ClientsTable", "Table", "Có", "ID/name/domains/tier/settings/health"],
            [4, "WorkspaceLink", "Link", "Có", "→ SCR-SEO-017"],
            [5, "SettingsButton", "Button", "Không", "→ workspace settings tab"],
        ],
        "rules": ["BR-SEO-001"],
    },
    "SCR-SEO-013": {
        "api": "GET OKR tree · POST goal/KPI · refresh KPIs from metrics",
        "pre": "canViewSeoStrategy; write/configure caps for mutations",
        "post": "OKR tree updated; KPI values refreshed",
        "purpose": "Strategy OKR S-05 — goals → KPIs → initiatives",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "OkrToolbar", "Toolbar", "Có", "+ Goal · + KPI · Refresh KPIs"],
            [3, "KpiFormCard", "Form", "Không", "Goal select · metric key/target · Create/Update"],
            [4, "GoalCards", "Card", "Có", "Nested KPI table + initiatives"],
            [5, "UnlinkedInitiatives", "List", "Không", "Initiatives without goal"],
        ],
        "rules": ["BR-SEO-004"],
    },
    "SCR-SEO-014": {
        "api": "GET gate-a status/readiness · GET signoff template",
        "pre": "canViewSeoGateA (settings configure OR crm_agency.configure)",
        "post": "Readiness report refreshed; template downloaded",
        "purpose": "Gate A go-live SEO/AEO — soak evidence + staged flags",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "SignoffTemplateButton", "Button", "Có", "Download JSON sign-off"],
            [3, "ReadinessPanel", "Panel", "Có", "Ready/Not ready + notes"],
            [4, "StagedFlagsTable", "Table", "Có", "Env keys ON/OFF per step"],
            [5, "SoakEvidencePanel", "Panel", "Có", "Required days · samples · failures"],
            [6, "QaHandoffChecklist", "Checklist", "Có", "§12 items status"],
            [7, "OpsRoutesPanel", "Nav", "Có", "Clickable canonical /seo/* routes"],
        ],
        "rules": ["BR-SYS-009"],
    },
    "SCR-SEO-015": {
        "api": "GET authority signals · import CSV",
        "pre": "canViewSeoAuthority; import cần canWriteSeo",
        "post": "Signals imported; summary KPI updated",
        "purpose": "Authority console S-11 — backlinks/citations/mentions E-E-A-T",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "ImportCsvButton", "Button", "Không", "Hidden file input — write"],
            [3, "SummaryKpiBar", "KPI", "Có", "Total · backlinks · citations · avg DR"],
            [4, "SignalsTable", "Table", "Có", "Type · domain · URL · DR · status"],
        ],
        "rules": ["BR-SEO-007"],
    },
    "SCR-SEO-016": {
        "api": "GET content detail/versions/checklist · PATCH status/title · POST approve · save version",
        "pre": "canViewSeoContent; write/approve caps separate",
        "post": "Version saved; approval stage recorded",
        "purpose": "Content detail staff — brief/body/versions + approval timeline",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "ContentHeader", "Header", "Có", "Title · client · keyword · status dropdown"],
            [3, "ContentTabs", "Tabs", "Có", "Brief JSON · Body HTML · Versions"],
            [4, "BodySaveVersion", "Form", "Có", "Textarea + Save version"],
            [5, "ApprovalTimeline", "Timeline", "Có", "seo/aeo/technical/client_review"],
            [6, "ApproveRejectPanel", "Panel", "Không", "Approve/Reject + notes — approve cap"],
            [7, "AeoChecklistSidebar", "Sidebar", "Không", "Checklist score + SEO/AEO scores"],
        ],
        "rules": ["BR-SEO-005", "BR-SEO-006"],
    },
    "SCR-SEO-017": {
        "api": "GET workspace/tasks · PATCH settings · OAuth GSC/GA4 · POST sync",
        "pre": "canViewSeoClientWorkspace; settings/OAuth cần canConfigureSeoSettings",
        "post": "OAuth connected; sync triggered; settings saved",
        "purpose": "Client workspace S-03 — overview/tasks/settings + OAuth",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "SeoClientWorkspaceNav", "Tabs", "Có", "Overview · Tasks · Settings"],
            [3, "OverviewKpiCards", "KPI", "Có", "Health · AEO · GSC clicks · critical issues"],
            [4, "ContentDeliveryCounts", "KPI", "Có", "Writing/review/overdue/published"],
            [5, "IntegrationsStatus", "Status", "Có", "GSC/GA4 connected + property IDs"],
            [6, "SyncRunsTable", "Table", "Có", "Source · status · rows · started"],
            [7, "TasksTabLists", "List", "Không", "Service tasks + technical issues links"],
            [8, "SettingsForm", "Form", "Không", "Domains/markets/tier · OAuth · Save/Sync"],
        ],
        "rules": ["BR-SEO-001", "BR-SEO-002", "BR-SEO-003"],
    },
    "SCR-SEO-018": {
        "api": "GET automations/status · POST run-alert-checks",
        "pre": "canViewSeoAutomations; run checks cần canConfigureSeoSettings",
        "post": "Alert checks queued; dashboard refreshed",
        "purpose": "Automations S-13 — sync runs, jobs, open alerts",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "ClientFilter", "Select", "Có", "All or ?customer_id="],
            [3, "RunAlertChecksButton", "Button", "Không", "Manual alert trigger"],
            [4, "SummaryKpiBar", "KPI", "Có", "Failed sync 7d · open alerts · pending jobs"],
            [5, "SyncRunsTable", "Table", "Có", "Source · status · started · rows"],
            [6, "SeoJobsTable", "Table", "Có", "Job type · status · created"],
            [7, "OpenAlertsList", "List", "Có", "Message + alert type"],
        ],
        "rules": ["BR-SEO-011"],
    },
    "SCR-SEO-019": {
        "api": "GET experiments status/list · POST create experiment",
        "pre": "canViewSeoExperiments + PTT_SEO_EXPERIMENTS_ENABLED=1",
        "post": "Draft experiment created for selected client",
        "purpose": "Experiments S-16 — hypothesis drafts per client (flag-gated)",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "FeatureDisabledBanner", "Alert", "Không", "When flag off"],
            [3, "ClientSelector", "Select", "Có", "Required before list load"],
            [4, "CreateDraftForm", "Form", "Không", "Title + Create draft — write cap"],
            [5, "ExperimentsTable", "Table", "Có", "title · type · status · updated_at"],
        ],
        "rules": ["BR-SEO-004"],
    },
}
