"""Manual BA use-case details — AI Revenue OS (AI-UC-001 … AI-UC-020)."""
from __future__ import annotations

from rnosai_ba_detail_helpers import uc_detail

AI_USE_CASE_DETAILS: dict[str, dict] = {
    "AI-UC-001": uc_detail(
        "AI-UC-001",
        "Lead score async sau ingest",
        screens="SCR-CRM-001, SCR-CRM-002",
        actor="System (worker, scoring engine)",
        actor_secondary="CSKH (consumer UI)",
        goal="Tính score 0–100 + explainability sau lead ingest",
        trigger="Lead mới created hoặc tenant.lead.created",
        pre="DDL applied; AiIntelligenceModule registered; pilot flag on",
        post="ai_scores có bản ghi; audit run id traceable ≤30s",
        priority="P0",
        wave="Wave R1",
        trace="RNOS-04, RNOS-08",
        api="POST /api/v1/ai/score/lead · GET /api/v1/ai/scores",
        main=[
            [1, "Lead ingest hoàn tất (CRM-UC-001, PLAT-UC-004/005)"],
            [2, "Outbox emit tenant.lead.created (RNOS-08)"],
            [3, "Worker consume → POST /api/v1/ai/score/lead"],
            [4, "Rules engine tính score + explainability[] (+/− factors)"],
            [5, "Persist ai_scores + ai_agent_runs"],
            [6, "Copilot panel refresh score ≤30s (poll/SSE)"],
        ],
        alt=[
            ["E1", "Duplicate score 5 phút → idempotency skip/update same row"],
            ["E2", "Thiếu attribution → score chạy; flag − Chưa map campaign"],
            ["E3", "Job fail → retry 3x; UI Score đang cập nhật"],
        ],
        io_in="lead_id, tenant_id, source metadata, timeline snapshot",
        io_out="score 0–100, explainability[], run_id",
        rules=["BR-AI-001", "BR-AI-009"],
    ),
    "AI-UC-002": uc_detail(
        "AI-UC-002",
        "Copilot — Lead brief",
        screens="SCR-CRM-002",
        actor="CSKH / Sales",
        goal="Tóm tắt nhanh lead 5 bullet tiếng Việt trên copilot panel",
        trigger="Mở lead detail hoặc bấm Tóm tắt nhanh",
        pre="Copilot PTT_AI_COPILOT_ENABLED=1; user owner hoặc GDKD",
        post="Brief hiển thị; không auto thay CRM core fields",
        priority="P0",
        wave="Wave R1",
        trace="RNOS-06",
        api="POST /api/v1/ai/summarize (context=lead_brief)",
        main=[
            [1, "CSKH mở /crm/leads/[id]"],
            [2, "Sidebar AI Copilot load score card (AI-UC-005)"],
            [3, "Bấm Tóm tắt nhanh → gather lead fields, last 5 activities, timeline, meta_json"],
            [4, "LLM trả 5 bullet: who, need, source, risk, next step"],
            [5, "User Copy hoặc Dismiss; ghi ai_agent_runs + ai_insights type=lead_brief"],
        ],
        alt=[
            ["E1", "Lead mới không activity → brief từ form fields + source"],
            ["E2", "Rate limit 429 → toast thử lại sau 1 phút"],
            ["E3", "Non-owner CSKH → 403 (BR-AI-004)"],
        ],
        io_in="lead_id, activities[], timeline[], meta_json",
        io_out="brief bullets[], run_id, confidence",
        rules=["BR-AI-001", "BR-AI-004", "BR-AI-009"],
    ),
    "AI-UC-003": uc_detail(
        "AI-UC-003",
        "Copilot — Summarize activity",
        screens="SCR-CRM-002",
        actor="CSKH",
        goal="Tóm tắt activity dài thành summary có cấu trúc",
        trigger="Chọn activity timeline hoặc paste note vào copilot",
        pre="Activity text ≥50 ký tự hoặc user paste note",
        post="Summary hiển thị; activity gốc không overwrite",
        priority="P0",
        wave="Wave R1",
        trace="RNOS-03, RNOS-06",
        api="POST /api/v1/ai/summarize",
        main=[
            [1, "CSKH chọn activity trên timeline hoặc paste vào copilot textarea"],
            [2, "Bấm Tóm tắt → POST /api/v1/ai/summarize"],
            [3, "Response: summary + extracted intent/objections/next_action"],
            [4, "User chấp nhận → copy summary vào note mới (optional one-click)"],
            [5, "Audit ai_agent_runs; P95 ≤5s staging"],
        ],
        alt=[
            ["E1", "Summary sai → user edit thủ công; dismiss không bắt buộc reason"],
            ["E2", "Empty text → validation 400"],
            ["E3", "confidence < 0.6 → banner BR-AI-003"],
        ],
        io_in="entity_type=lead, entity_id, text",
        io_out="summary, extracted fields, run_id",
        rules=["BR-AI-001", "BR-AI-003", "BR-AI-009"],
    ),
    "AI-UC-004": uc_detail(
        "AI-UC-004",
        "Follow-up draft + approve",
        screens="SCR-CRM-002",
        actor="CSKH",
        goal="Sinh draft follow-up; user duyệt trước khi dùng — KHÔNG auto-send",
        trigger="Bấm Soạn follow-up trên copilot panel",
        pre="Lead context B1/B2+; BR-AI-01 enforced",
        post="ai_recommendations status accepted|dismissed; không outbound send",
        priority="P0",
        wave="Wave R1",
        trace="RNOS-06, RNOS-07",
        api="POST /api/v1/ai/recommendation · PATCH /api/v1/ai/recommendations/:id",
        main=[
            [1, "CSKH bấm Soạn follow-up → chọn kênh gợi ý Zalo/email/note"],
            [2, "POST /api/v1/ai/recommendation type=follow_up_draft"],
            [3, "LLM trả draft message → textarea editable"],
            [4, "CSKH chỉnh sửa nội dung"],
            [5, "Duyệt → PATCH accepted → copy activity/clipboard — không gửi API outbound"],
            [6, "Hoặc Bỏ → dismissed + reason (AI-UC-007)"],
        ],
        alt=[
            ["E1", "Low confidence → banner BR-AI-02 trước duyệt"],
            ["E2", "Approve ≠ Send — audit accepted_by timestamp"],
        ],
        io_in="lead_id, channel_hint, tone preference",
        io_out="draft_text, recommendation_id, confidence, run_id",
        rules=["BR-AI-001", "BR-AI-004", "BR-AI-007"],
    ),
    "AI-UC-005": uc_detail(
        "AI-UC-005",
        "Xem score + explainability",
        screens="SCR-CRM-002, SCR-AI-001",
        actor="CSKH / GDKD",
        goal="Hiển thị score 0–100 + explainability factors trên copilot",
        trigger="Mở lead detail copilot panel",
        pre="Score đã chạy (AI-UC-001) hoặc pending",
        post="User hiểu vì sao score cao/thấp (≥3 factors khi đủ data)",
        priority="P0",
        wave="Wave R1",
        trace="RNOS-04, RNOS-06",
        api="GET /api/v1/ai/scores?entity_type=lead&entity_id=",
        main=[
            [1, "Panel hiển thị score 0–100 + label hot/warm/cold"],
            [2, "Chips explain: + Meta mapped, − Chưa gọi (2h), …"],
            [3, "GET scores trả history; latest highlighted"],
            [4, "Tooltip confidence %; banner nếu < 0.6"],
            [5, "Link Xem lịch sử score (optional drawer)"],
        ],
        alt=[
            ["E1", "Chưa có score → skeleton + Đang tính… ≤30s"],
            ["E2", "Override active → badge GDKD điều chỉnh (AI-UC-006)"],
        ],
        io_in="entity_type, entity_id",
        io_out="score, explainability_json[], history[]",
        rules=["BR-AI-003", "BR-AI-005"],
    ),
    "AI-UC-006": uc_detail(
        "AI-UC-006",
        "Manager override score",
        screens="SCR-CRM-002",
        actor="GDKD / Head Sales",
        goal="GDKD điều chỉnh score thủ công có audit",
        trigger="Score sai nghiệp vụ; cần ưu tiên thủ công",
        pre="Cap crm_gdkd hoặc admin; score hiện tại visible",
        post="Override traceable; không xóa score history",
        priority="P1",
        wave="Wave R1",
        trace="UI-R1-08",
        api="POST /api/v1/ai/score/lead/override",
        main=[
            [1, "GDKD mở lead copilot → Điều chỉnh score"],
            [2, "Nhập score mới 0–100 + lý do bắt buộc ≥10 ký tự"],
            [3, "API tạo ai_scores source=manual_override, overridden_by, override_reason"],
            [4, "UI badge override; explainability giữ factors gốc + note"],
            [5, "Audit ai_agent_runs action=override"],
        ],
        alt=[
            ["E1", "Admin revert → restore auto score từ rules engine"],
            ["E2", "Reason <10 chars → validation 400"],
        ],
        io_in="lead_id, new_score, override_reason, overridden_by",
        io_out="ai_scores override row, audit run_id",
        rules=["BR-AI-006", "BR-AI-009"],
    ),
    "AI-UC-007": uc_detail(
        "AI-UC-007",
        "Dismiss recommendation + reason",
        screens="SCR-CRM-002, SCR-AI-001",
        actor="CSKH",
        goal="Dismiss draft/brief/summary không hữu ích với preset reason",
        trigger="User bấm Bỏ trên recommendation card",
        pre="Recommendation exists status=pending",
        post="Recommendation archived; metrics adoption dismiss rate",
        priority="P1",
        wave="Wave R2",
        trace="RNOS-29",
        api="PATCH /api/v1/ai/recommendations/:id",
        main=[
            [1, "User bấm Bỏ trên copilot recommendation card"],
            [2, "Modal chọn preset reason: sai tone / sai fact / không cần / khác"],
            [3, "PATCH status=dismissed, dismiss_reason"],
            [4, "Card ẩn khỏi pending list"],
            [5, "Aggregate dismiss analytics trên SCR-AI-001"],
        ],
        alt=[
            ["E1", "Optional skip reason pilot → default other"],
        ],
        io_in="recommendation_id, dismiss_reason preset",
        io_out="updated recommendation, analytics event",
        rules=["BR-AI-007", "BR-AI-009"],
    ),
    "AI-UC-008": uc_detail(
        "AI-UC-008",
        "Timeline enrich cho AI context",
        screens="SCR-CRM-009, SCR-CRM-002",
        actor="System",
        actor_secondary="Platform worker",
        goal="Ghi customer_timeline_events phục vụ AI context builder",
        trigger="Activity log, webhook meta, status change",
        pre="Phase 0 data gate ≥70% timeline completeness target",
        post="Copilot context đầy đủ; score explainability chính xác hơn",
        priority="P0",
        wave="Wave R1",
        trace="RNOS-16",
        api="customer_timeline_events DDL · domain event consumers",
        main=[
            [1, "CRM activity create → ghi customer_timeline_events"],
            [2, "Webhook lead meta → event lead.ingested + attribution snapshot"],
            [3, "Status change → event payload from/to"],
            [4, "AI context builder đọc timeline khi summarize/score/brief"],
            [5, "Metric: % lead có ≥1 timeline event trong 24h"],
        ],
        alt=[
            ["E1", "Backfill job one-time từ crm_activities legacy"],
        ],
        io_in="entity events: activity, webhook, status",
        io_out="timeline_event rows[], completeness metric",
        rules=["BR-AI-008", "BR-AI-009"],
    ),
    "AI-UC-009": uc_detail(
        "AI-UC-009",
        "AI audit / agent run trace",
        screens="SCR-ADMIN-001",
        actor="Admin / Compliance",
        actor_secondary="Tech lead",
        goal="100% AI calls auditable qua ai_agent_runs",
        trigger="Tra cứu incident, nghiệm thu G5 gate R1",
        pre="AiIntelligenceModule logging enabled",
        post="Filter/search runs by request_id, entity, user",
        priority="P0",
        wave="Wave R1",
        trace="RNOS-09",
        api="GET /admin/ai/runs · table ai_agent_runs",
        main=[
            [1, "Mỗi AI call → insert ai_agent_runs model, tokens, latency, status, request_id"],
            [2, "Admin mở /admin/ai/runs"],
            [3, "Filter entity_id, date, user, action type"],
            [4, "Drill-down: không hiển thị prompt PII prod (AI_LOG_PROMPTS=0)"],
            [5, "Cross-link lead detail run id debug staging only"],
        ],
        alt=[
            ["E1", "Missing run → incident P1 AI pipeline down"],
        ],
        io_in="filter: request_id, entity_id, date_range, action",
        io_out="run list[], run detail metadata",
        rules=["BR-AI-009"],
    ),
    "AI-UC-010": uc_detail(
        "AI-UC-010",
        "Pilot gate / feature flag",
        screens="SCR-ADMIN-002, SCR-CRM-002",
        actor="Super Admin / Product",
        actor_secondary="CSKH pilot cohort",
        goal="Pilot copilot isolated cohort; rollback safe",
        trigger="Tuần 11–12 go-live pilot",
        pre="Env flags configured; cohort user ids defined",
        post="Pilot metrics G2–G6 collected; non-pilot unaffected",
        priority="P0",
        wave="Wave R1",
        trace="RNOS-39, RNOS-40",
        api="PTT_AI_COPILOT_ENABLED env · tenant feature flags",
        main=[
            [1, "Set PTT_AI_COPILOT_ENABLED=1 + cohort 5–8 CSKH user ids"],
            [2, "Non-pilot: copilot panel hidden; API 403/404"],
            [3, "Monitor DAU, error rate, acceptance rate tuần 12"],
            [4, "Rollback flag off → CRM core unaffected (RNOS-40 runbook)"],
            [5, "Gate R1 sign-off §8.3"],
        ],
        alt=[
            ["E1", "Partial rollout → per-tenant flag"],
        ],
        io_in="feature flag config, cohort user_ids[]",
        io_out="pilot metrics dashboard, gate evidence",
        rules=["BR-AI-010", "BR-AI-009"],
    ),
    "AI-UC-011": uc_detail(
        "AI-UC-011",
        "NBA trên deal stalled",
        screens="SCR-CRM-013, SCR-CRM-002",
        actor="AM / Sales",
        actor_secondary="System (Pipeline Risk Agent), GDKD",
        goal="Next-best-action khi deal stalled ≥7 ngày",
        trigger="Daily scan RNOS-23 hoặc stage change detect stall",
        pre="Timeline có data; deal score optional (AI-UC-012)",
        post="Task CRM created hoặc recommendation dismissed",
        priority="P0",
        wave="Wave R2",
        trace="RNOS-10, RNOS-29",
        api="POST ai_recommendations type=nba · playbook RAG RNOS-12",
        main=[
            [1, "Daily job detect stall → ai_recommendations type=nba"],
            [2, "NBA card trên /crm/sales pipeline drawer hoặc copilot"],
            [3, "Gợi ý: gọi lại / gửi proposal / escalate GDKD + cite playbook"],
            [4, "Sales Chấp nhận → tạo task CRM + activity template"],
            [5, "Bỏ → reason → RNOS-29 feedback loop"],
        ],
        alt=[
            ["E1", "Low confidence → banner BR-AI-02; vẫn cho accept"],
            ["E2", "Deal vừa Won → không emit NBA"],
        ],
        io_in="deal_id, stall_days, pipeline context",
        io_out="nba recommendation, task_id?, status",
        rules=["BR-AI-011", "BR-AI-007", "BR-AI-009"],
    ),
    "AI-UC-012": uc_detail(
        "AI-UC-012",
        "Deal score",
        screens="SCR-CRM-013",
        actor="Sales / GDKD",
        goal="Score deal 0–100 trên pipeline Kanban",
        trigger="Pipeline stage advance / quote created",
        pre="Deal in pipeline with activity history",
        post="Score visible on Kanban card + deal drawer",
        priority="P1",
        wave="Wave R2",
        trace="RNOS-09",
        api="POST /api/v1/ai/score/deal",
        main=[
            [1, "Stage change hoặc proposal attach trigger score job"],
            [2, "POST /api/v1/ai/score/deal"],
            [3, "Score + explain: aging, activity count, quote value, ads touch"],
            [4, "Kanban card mini-bar trên /crm/sales"],
            [5, "GDKD override pattern AI-UC-006"],
        ],
        alt=[
            ["E1", "New deal no history → default warm score + flag"],
        ],
        io_in="deal_id, stage, quote_value, activity_count",
        io_out="deal score, explainability[], run_id",
        rules=["BR-AI-012", "BR-AI-006", "BR-AI-009"],
    ),
    "AI-UC-013": uc_detail(
        "AI-UC-013",
        "Forecast commit",
        screens="SCR-CRM-006",
        actor="GDKD / Finance",
        goal="Commit forecast snapshot immutable cho planning",
        trigger="Daily 07:00 ICT job hoặc cuối tháng planning",
        pre="Pipeline data synced; Forecast Agent ran",
        post="revenue_forecast_snapshots.committed_by set; MAPE trackable",
        priority="P1",
        wave="Wave R3",
        trace="RNOS-17, RNOS-18",
        api="POST /api/v1/ai/forecast · PATCH commit snapshot",
        main=[
            [1, "Forecast Agent → POST /api/v1/ai/forecast → snapshot draft"],
            [2, "GDKD mở /crm/forecast — pipeline weighted vs AI delta"],
            [3, "Review explain factors: stage, seasonality, stall count"],
            [4, "Bấm Cam kết → ghi committed_by immutable snapshot"],
            [5, "Leadership export PDF / hub widget"],
        ],
        alt=[
            ["E1", "MAPE >20% prior month → banner cảnh báo trước commit"],
            ["E2", "Re-commit → new snapshot row; prior preserved"],
        ],
        io_in="forecast period, pipeline snapshot, AI model output",
        io_out="committed snapshot id, PDF export",
        rules=["BR-AI-013", "BR-AI-009"],
    ),
    "AI-UC-014": uc_detail(
        "AI-UC-014",
        "Renewal agent workflow",
        screens="SCR-CRM-009, SCR-AGENCY-001",
        actor="AM / System (Renewal Agent)",
        goal="Draft renewal outreach T-90/T-60/T-30 contract milestones",
        trigger="Lifecycle Retain / contract end date thresholds",
        pre="Contract exists CRM-UC-011; health score optional AI-UC-017",
        post="Renewal task created; draft reviewed by AM — no auto-send",
        priority="P1",
        wave="Wave R3",
        trace="RNOS-20",
        api="Renewal Agent workflow · retain tab /agency/clients/[id]",
        main=[
            [1, "Workflow trigger trên lifecycle Retain contract end date"],
            [2, "Renewal card trên agency client retain tab + health score ref"],
            [3, "Agent draft renewal email/Zalo → AM review (BR-AI-01)"],
            [4, "AM Duyệt → task follow-up; không auto-send"],
            [5, "Track renewal outcome Won/Lost → feedback loop"],
        ],
        alt=[
            ["E1", "Client already renewed → cancel workflow"],
        ],
        io_in="contract_id, end_date, health_score, client context",
        io_out="renewal draft, task_id, outcome",
        rules=["BR-AI-014", "BR-AI-001", "BR-AI-009"],
    ),
    "AI-UC-015": uc_detail(
        "AI-UC-015",
        "Pipeline risk & smart reminder",
        screens="SCR-CRM-013, SCR-AI-003",
        actor="System / GDKD / Sales",
        goal="Detect at-risk deals và suggest smart reminder tasks",
        trigger="Daily scan RNOS-23; SLA breach pipeline stage",
        pre="Pipeline Risk Agent configured",
        post="GDKD notified; optional task created on confirm",
        priority="P1",
        wave="Wave R2",
        trace="RNOS-23",
        api="Pipeline Risk Agent daily job · smart reminder API",
        main=[
            [1, "Pipeline Risk Agent scan → deals at-risk list"],
            [2, "Notify GDKD inbox + optional Slack"],
            [3, "Smart reminder task auto-suggest — user confirm create"],
            [4, "Link alert → deal copilot / NBA (AI-UC-011)"],
            [5, "Track reminder completion SLA"],
        ],
        alt=[
            ["E1", "User dismiss alert → tune sensitivity"],
        ],
        io_in="pipeline snapshot, risk rules, SLA config",
        io_out="at_risk_deals[], notifications, task suggestions",
        rules=["BR-AI-015", "BR-AI-009"],
    ),
    "AI-UC-016": uc_detail(
        "AI-UC-016",
        "NL analytics curated",
        screens="SCR-AI-002",
        actor="GDKD / CEO",
        goal="Curated NL query read-only — không free SQL",
        trigger="Mở /crm/ai/query hoặc Cmd+K palette",
        pre="Cap ai_analytics.query; curated catalog ~50 câu hỏi",
        post="Chart/table + narrative VN returned; CRM unchanged",
        priority="P2",
        wave="Wave R3",
        trace="RNOS-22",
        api="POST /api/v1/ai/query",
        main=[
            [1, "User chọn câu hỏi preset hoặc gõ trong whitelist intent"],
            [2, "POST /api/v1/ai/query → chart/table + narrative VN"],
            [3, "Read-only — không mutate CRM"],
            [4, "Export CSV snapshot"],
            [5, "Audit query run in ai_agent_runs"],
        ],
        alt=[
            ["E1", "Out of scope → Câu hỏi ngoài phạm vi — chọn từ danh sách"],
            ["E2", "Insufficient data → empty chart + explanation"],
        ],
        io_in="curated question id or whitelisted intent text",
        io_out="chart spec, narrative text, CSV export",
        rules=["BR-AI-016", "BR-AI-009"],
    ),
    "AI-UC-017": uc_detail(
        "AI-UC-017",
        "Churn & CS health score",
        screens="SCR-CRM-007, SCR-CRM-009",
        actor="AM / CSKH / CS Lead",
        goal="Health score churn risk per customer/account",
        trigger="Ticket spike, NPS drop, usage signal, scheduled recompute",
        pre="Customer converted; BR-AI-017 — chỉ customer post-convert",
        post="Score visible /crm/health; trigger renewal if below threshold",
        priority="P1",
        wave="Wave R3",
        trace="RNOS-19",
        api="POST /api/v1/ai/score/churn · GET /crm/health",
        main=[
            [1, "POST /api/v1/ai/score/churn per client/account"],
            [2, "Display on /crm/health + customer detail tab"],
            [3, "Explain: ticket volume, sentiment, payment delay"],
            [4, "Threshold breach → link renewal workflow AI-UC-014"],
            [5, "AM action plan task optional"],
        ],
        alt=[
            ["E1", "New customer <30d → insufficient data badge"],
        ],
        io_in="customer_id, tickets[], payment history, usage signals",
        io_out="health_score 0–100, explainability[], alerts[]",
        rules=["BR-AI-017", "BR-AI-009"],
    ),
    "AI-UC-018": uc_detail(
        "AI-UC-018",
        "Manager coach weekly digest",
        screens="SCR-AI-003",
        actor="GDKD / Head Sales",
        goal="Weekly aggregate coaching insights — no auto personnel action",
        trigger="Weekly job Thứ 2 08:00 ICT",
        pre="Team activity ≥1 week data",
        post="Email + dashboard cards delivered",
        priority="P2",
        wave="Wave R3",
        trace="RNOS-21",
        api="Manager Coach Agent cron · GET /crm/ai/coach",
        main=[
            [1, "Manager Coach Agent aggregate: SLA breach, acceptance rate, top dismiss reasons"],
            [2, "Generate digest narrative VN"],
            [3, "Email GDKD + render cards /crm/ai/coach"],
            [4, "Drill-down → lead/deal examples read-only"],
            [5, "No auto personnel action — insights only"],
        ],
        alt=[
            ["E1", "Low activity week → shortened digest"],
        ],
        io_in="team_id, week metrics, adoption stats",
        io_out="digest email, dashboard cards, run_id",
        rules=["BR-AI-018", "BR-AI-009"],
    ),
    "AI-UC-019": uc_detail(
        "AI-UC-019",
        "Channel CPL/ROAS anomaly digest",
        screens="SCR-AI-001, SCR-META-001, SCR-ZALO-001",
        actor="GDKD / Media Buyer / System",
        goal="Cross-channel anomaly narrative Meta+Zalo+Google",
        trigger="CPL spike / zero lead 24h on mapped campaigns",
        pre="Channel metrics ≥7d baseline; BR-AI-019 threshold configurable",
        post="Digest on insights + hub banners; budget recommend read-only",
        priority="P2",
        wave="Wave R4",
        trace="RNOS-28",
        api="Channel AI job · anomaly digest API",
        main=[
            [1, "Channel AI job compare Meta+Zalo+Google daily_performance"],
            [2, "Detect CPL >2σ, zero leads 24h, ROAS drop"],
            [3, "Narrative banner SCR-AI-001 anomaly panel"],
            [4, "Hub banners /meta/facebook-ads + /zalo/zalo-ads"],
            [5, "Link drill → leads affected + copilot context; budget recommend read-only"],
        ],
        alt=[
            ["E1", "Insufficient baseline → skip channel"],
            ["E2", "False positive dismiss → tune per-channel threshold"],
        ],
        io_in="channel metrics[], baselines, thresholds per channel",
        io_out="anomaly digest entries[], hub banner flags",
        rules=["BR-AI-019", "BR-META-009", "BR-ZALO-017"],
    ),
    "AI-UC-020": uc_detail(
        "AI-UC-020",
        "Workflow AI node simulate + publish",
        screens="SCR-AI-004, SCR-AI-005, SCR-ADMIN-003",
        actor="Admin / AM",
        goal="Drag AI score/summarize nodes vào automation workflow",
        trigger="Tạo/sửa workflow /crm/automation",
        pre="Workflow designer access; AI tools registered RNOS-33",
        post="AI node published; executions audited in ai_agent_runs",
        priority="P1",
        wave="Wave R2",
        trace="RNOS-13, RNOS-14, RNOS-15",
        api="POST workflow publish · simulate endpoint · playbook RAG PG vectors",
        main=[
            [1, "Admin kéo node AI score / AI summarize vào graph (RNOS-14)"],
            [2, "Simulate trên sample entity — không mutate prod (RNOS-15)"],
            [3, "Review simulate output + latency"],
            [4, "Publish workflow → live on trigger event"],
            [5, "Audit mọi AI node execution trong ai_agent_runs"],
            [6, "Playbook RAG node link SCR-AI-005 vector chunks RNOS-12"],
        ],
        alt=[
            ["E1", "Simulate fail → block publish"],
            ["E2", "Rollback workflow version → prior graph restored"],
        ],
        io_in="workflow graph JSON, sample entity_id, node config",
        io_out="published workflow version, simulate results, run audits",
        rules=["BR-AI-020", "BR-AI-009", "BR-AI-001"],
    ),
}
