"""Manual BA use-case details — Client Portal (PORTAL-UC-001 … PORTAL-UC-010)."""
from __future__ import annotations

from rnosai_ba_detail_helpers import uc_detail

PORTAL_USE_CASE_DETAILS: dict[str, dict] = {
    "PORTAL-UC-001": uc_detail(
        "PORTAL-UC-001",
        "Login portal scoped client",
        screens="SCR-PORTAL-002",
        actor="Client Viewer / Client Approver",
        goal="Portal JWT scoped single client_id + role",
        trigger="User truy cập portal.pttads.vn login",
        pre="Portal user provisioned AM SYS-UC-001; account active",
        post="Session TTL per policy; redirect /dashboard",
        priority="P0",
        wave="Wave R1",
        trace="PLAT-003, TC-PORTAL-01",
        api="POST /portal/auth/login · PLAT-UC-003 JWT",
        main=[
            [1, "User mở portal-web /login"],
            [2, "Email + password submit"],
            [3, "API issue JWT scoped client_id + role viewer|approver"],
            [4, "Set httpOnly cookie / token storage per adr-011"],
            [5, "Redirect /dashboard PORTAL-UC-002"],
        ],
        alt=[
            ["E1", "Wrong credentials → generic error no enumeration"],
            ["E2", "Cross-tenant probe → 403 empty SYS-UC-011"],
            ["E3", "Account disabled → 403 contact AM message"],
        ],
        io_in="email, password",
        io_out="JWT access+refresh, client_id scope, role caps",
        rules=["BR-PORTAL-001", "BR-PLAT-003", "BR-SYS-011"],
    ),
    "PORTAL-UC-002": uc_detail(
        "PORTAL-UC-002",
        "Dashboard KPI multi-module",
        screens="SCR-PORTAL-001",
        actor="Client Viewer",
        goal="Read-only KPI cards Meta/SEO/Email/Zalo per enabled modules",
        trigger="Post-login landing /dashboard",
        pre="Modules enabled for client; data synced",
        post="Read-only view; no internal staff PII/margin",
        priority="P0",
        wave="Wave R1",
        api="GET /portal/dashboard · aggregated KPI API",
        main=[
            [1, "Dashboard load enabled module flags"],
            [2, "Render cards: spend, leads, CPL, SEO traffic, email sends, Zalo CPL"],
            [3, "Date range selector 7d/30d/90d"],
            [4, "Attribution disclaimer footer"],
            [5, "Pending approval badge count link /creatives or /notifications"],
        ],
        alt=[
            ["E1", "Module disabled → card hidden not 404 whole page"],
            ["E2", "No data period → empty state per card"],
        ],
        io_in="JWT client_id, date_range",
        io_out="KPI card JSON, module flags",
        rules=["BR-PORTAL-002"],
    ),
    "PORTAL-UC-003": uc_detail(
        "PORTAL-UC-003",
        "Meta performance view + CSV",
        screens="SCR-PORTAL-003",
        actor="Client Viewer",
        goal="Meta tab campaign table drill metrics export CSV",
        trigger="Navigate /meta on portal",
        pre="Meta module enabled; META-UC-003 data synced",
        post="CSV export scoped client; download logged",
        priority="P0",
        wave="Wave R1",
        api="GET /portal/meta/performance · CSV export",
        main=[
            [1, "Client mở portal /meta"],
            [2, "View campaign table read-only scoped client_id"],
            [3, "Drill campaign row metrics spend/leads/CPL"],
            [4, "Select date range filter"],
            [5, "Export CSV period snapshot PORTAL-UC-010 audit"],
        ],
        alt=[
            ["E1", "Unmapped spend footnote client-safe wording"],
        ],
        io_in="date_range, campaign filter",
        io_out="performance table, CSV file",
        rules=["BR-PORTAL-003", "BR-META-003"],
    ),
    "PORTAL-UC-004": uc_detail(
        "PORTAL-UC-004",
        "SEO summary view",
        screens="SCR-PORTAL-006",
        actor="Client Viewer",
        goal="SEO tab traffic trend, top pages, content delivered count",
        trigger="Navigate portal /seo",
        pre="SEO module enabled; SEO-UC-012/013 data available",
        post="Summary read-only; link PDF if published",
        priority="P1",
        wave="Wave R2",
        api="GET /portal/seo/summary",
        main=[
            [1, "Client mở /seo summary tab"],
            [2, "View traffic trend chart GSC/GA4 aggregate"],
            [3, "Top pages table client-safe"],
            [4, "Content delivered count this period"],
            [5, "Download PDF link if SEO-UC-013 artifact exists"],
        ],
        alt=[
            ["E1", "Sync stale → last updated timestamp shown"],
        ],
        io_in="JWT client_id, date_range",
        io_out="SEO summary JSON, PDF link optional",
        rules=["BR-PORTAL-004", "BR-SEO-013"],
    ),
    "PORTAL-UC-005": uc_detail(
        "PORTAL-UC-005",
        "Email campaign stats",
        screens="SCR-PORTAL-005",
        actor="Client Viewer",
        goal="Email tab sent campaigns open/click rates aggregate",
        trigger="Navigate portal /email",
        pre="Email module enabled; campaigns sent EM-UC-006",
        post="Aggregate stats only; no subscriber PII",
        priority="P1",
        wave="Wave R2",
        api="GET /portal/email/stats",
        main=[
            [1, "Client mở /email stats tab"],
            [2, "List sent campaigns read-only"],
            [3, "View open rate, click rate, bounce aggregate"],
            [4, "Drill campaign summary detail"],
            [5, "Approval inbox link PORTAL-UC-008 for pending"],
        ],
        alt=[
            ["E1", "Campaign pending approval → stats hidden until sent"],
        ],
        io_in="JWT client_id, period filter",
        io_out="campaign stats list[], aggregates",
        rules=["BR-PORTAL-005", "BR-EM-006"],
    ),
    "PORTAL-UC-006": uc_detail(
        "PORTAL-UC-006",
        "Approval inbox Meta creative",
        screens="SCR-PORTAL-004",
        actor="Client Approver",
        goal="Approve/reject Meta creative submitted by agency",
        trigger="Staff submit creative SVC-UC-006 pending_client",
        pre="Approver role JWT; creative pending",
        post="Decision synced ops-web + SYS-UC-004",
        priority="P0",
        wave="Wave R1",
        trace="SYS-004",
        api="GET/PATCH /portal/approvals/creatives",
        main=[
            [1, "Notification → Approvals inbox /creatives"],
            [2, "Preview creative assets + ad copy"],
            [3, "Approve → notify staff; unlock launch META-UC-007"],
            [4, "Reject → PORTAL-UC-009 comment required"],
            [5, "Audit decision timestamp + approver id"],
        ],
        alt=[
            ["E1", "Viewer role → 403 on approve actions"],
        ],
        io_in="creative_id, approval_action, comment?",
        io_out="approval status, ops-web sync event",
        rules=["BR-PORTAL-006", "BR-SYS-004", "BR-SVC-006"],
    ),
    "PORTAL-UC-007": uc_detail(
        "PORTAL-UC-007",
        "Approval SEO content",
        screens="SCR-PORTAL-006",
        actor="Client Approver",
        goal="Preview SEO content draft; approve advances pipeline",
        trigger="Content submitted client approval SEO-UC-005",
        pre="Approver role; content pending review",
        post="SEO pipeline stage advances on approve",
        priority="P1",
        wave="Wave R2",
        api="PATCH /portal/approvals/seo-content",
        main=[
            [1, "Approver opens SEO content approval item"],
            [2, "Preview HTML/markdown rendered client-safe"],
            [3, "Optional section-level comments"],
            [4, "Approve → SEO-UC-005 stage advance Scheduled"],
            [5, "Reject → PORTAL-UC-009 returns Draft ops-web"],
        ],
        alt=[
            ["E1", "Governance fail post-approval → block publish SEO-UC-006"],
        ],
        io_in="content_id, approval_action, section comments",
        io_out="approval audit, pipeline stage update",
        rules=["BR-PORTAL-007", "BR-SEO-005"],
    ),
    "PORTAL-UC-008": uc_detail(
        "PORTAL-UC-008",
        "Approval email campaign",
        screens="SCR-PORTAL-005",
        actor="Client Approver",
        goal="Preview email campaign; approve unlocks send EM-UC-007",
        trigger="Email strategist submit campaign pending client",
        pre="Campaign draft ready; approver JWT",
        post="Dual approval recorded EM-UC-007; ESP send allowed",
        priority="P1",
        wave="Wave R2",
        trace="SYS-004",
        api="PATCH /portal/approvals/email-campaigns",
        main=[
            [1, "Approver opens email campaign approval item"],
            [2, "Preview template render + subject line"],
            [3, "View segment size summary aggregate only"],
            [4, "Approve → unlock ESP send path EM-UC-008"],
            [5, "Reject → PORTAL-UC-009 with comment"],
        ],
        alt=[
            ["E1", "Staff approval still required EM-UC-007 dual gate"],
        ],
        io_in="campaign_id, approval_action, comment?",
        io_out="approval status, send gate flag",
        rules=["BR-PORTAL-008", "BR-EM-007", "BR-SYS-004"],
    ),
    "PORTAL-UC-009": uc_detail(
        "PORTAL-UC-009",
        "Reject with comment",
        screens="SCR-PORTAL-004, SCR-PORTAL-005, SCR-PORTAL-006",
        actor="Client Approver",
        goal="Reject approval item với comment bắt buộc",
        trigger="Approver selects Reject on any approval UC",
        pre="Item pending approval",
        post="Rejection reason audit; item returns draft ops-web",
        priority="P0",
        wave="Wave R1",
        api="PATCH approval reject · all approval types",
        main=[
            [1, "Approver selects Reject on creative/content/email item"],
            [2, "Modal comment required min length BR-PORTAL-009"],
            [3, "PATCH status rejected + comment stored"],
            [4, "Notify staff in-app/email"],
            [5, "Item returns draft in ops-web; no auto-resubmit"],
        ],
        alt=[
            ["E1", "Empty comment → validation block submit"],
        ],
        io_in="item_id, item_type, reject_comment",
        io_out="rejected status, staff notification, audit",
        rules=["BR-PORTAL-009"],
    ),
    "PORTAL-UC-010": uc_detail(
        "PORTAL-UC-010",
        "Export & download artifact",
        screens="SCR-PORTAL-010, SCR-PORTAL-001",
        actor="Client Viewer",
        goal="Download PDF reports, CSV exports, signed URLs",
        trigger="User requests download from portal",
        pre="Artifact available for client scope",
        post="Download logged compliance; signed URL expiry",
        priority="P0",
        wave="Wave R1",
        trace="SYS-005",
        api="GET /portal/settings/exports · signed URL generator",
        main=[
            [1, "User opens /settings exports or inline download buttons"],
            [2, "List available artifacts: Meta CSV, SEO PDF, weekly reports"],
            [3, "Generate signed URL with expiry TTL"],
            [4, "Client downloads file"],
            [5, "Audit log download event client_id + artifact id"],
        ],
        alt=[
            ["E1", "Expired link → regenerate new signed URL"],
            ["E2", "Artifact not ready → 404 with retry later message"],
        ],
        io_in="artifact_id, client_id JWT",
        io_out="signed download URL, audit log entry",
        rules=["BR-PORTAL-010", "BR-SYS-005"],
    ),
    "PORTAL-UC-011": uc_detail(
        "PORTAL-UC-011",
        "Quên mật khẩu / reset",
        screens="SCR-PORTAL-002, SCR-PORTAL-011, SCR-PORTAL-012",
        actor="Client Viewer",
        goal="Self-serve password reset via email token",
        trigger="User clicks Quên mật khẩu on login",
        pre="Portal account exists and active",
        post="Password updated; user can login with new password",
        priority="P0",
        wave="Wave R1",
        trace="GAP-P0-02",
        api="POST /portal/auth/forgot-password · POST /portal/auth/reset-password",
        main=[
            [1, "Client click Quên mật khẩu on /login"],
            [2, "Enter email on /forgot-password → generic success message"],
            [3, "System send reset link /reset-password?token=…"],
            [4, "Client set new password ≥8 chars on /reset-password"],
            [5, "Redirect /login?reset=ok → login with new password"],
        ],
        alt=[
            ["E1", "Invalid/expired token → request new link flow"],
            ["E2", "Archived account → block reset contact AM"],
        ],
        io_in="email, reset token, new password",
        io_out="password hash updated, audit log",
        rules=["BR-PORTAL-011", "BR-PORTAL-001"],
    ),
    "PORTAL-UC-012": uc_detail(
        "PORTAL-UC-012",
        "Đổi mật khẩu khi đã login",
        screens="SCR-PORTAL-010",
        actor="Client Viewer",
        goal="Change password from settings while authenticated",
        trigger="User opens /settings password section",
        pre="Valid portal session JWT",
        post="Password hash updated; session remains valid",
        priority="P1",
        wave="Wave R2",
        api="POST /portal/auth/change-password",
        main=[
            [1, "Client open /settings → Đổi mật khẩu section"],
            [2, "Enter current password + new password + confirm"],
            [3, "API validate current hash and policy"],
            [4, "Success toast; optional re-login per policy"],
        ],
        alt=[
            ["E1", "Wrong current password → 401 validation error"],
        ],
        io_in="current_password, new_password",
        io_out="updated credential audit",
        rules=["BR-PORTAL-012", "BR-PORTAL-001"],
    ),
    "PORTAL-UC-013": uc_detail(
        "PORTAL-UC-013",
        "Zalo performance view + export",
        screens="SCR-PORTAL-007",
        actor="Client Viewer",
        goal="Read-only Zalo KPI + CSV/PDF export scoped client",
        trigger="Navigate /zalo or dashboard widget click",
        pre="zalo_enabled module flag; data synced T-1",
        post="Export downloaded; audit log compliance",
        priority="P0",
        wave="Wave R1",
        trace="ZALO-005, Z3-6",
        api="GET /portal/zalo/performance · CSV/PDF export",
        main=[
            [1, "Client open /zalo — KPI cards load scoped client_id"],
            [2, "Select date range T-7 / T-30"],
            [3, "View Spend, Leads, CPL read-only"],
            [4, "Export CSV or PDF period snapshot PORTAL-UC-010 audit"],
            [5, "Show CPL disclaimer if unmapped spend yellow note"],
        ],
        alt=[
            ["E1", "Module disabled → card hidden on dashboard not 404"],
        ],
        io_in="JWT client_id, date_range",
        io_out="KPI JSON, export file",
        rules=["BR-PORTAL-013", "BR-ZALO-005", "BR-PORTAL-010"],
    ),
    "PORTAL-UC-014": uc_detail(
        "PORTAL-UC-014",
        "Zalo creative approval",
        screens="SCR-PORTAL-004",
        actor="Client Approver",
        goal="Approve/reject Zalo creative before go-live",
        trigger="Creative pending_client_approval channel=zalo",
        pre="Approver role; creative in pending state",
        post="Decision audited; staff notified; launch unblocked on approve",
        priority="P1",
        wave="Wave R2",
        trace="ZALO-019",
        api="Portal approvals API · notify staff webhook",
        main=[
            [1, "Approver open /creatives filter channel=zalo"],
            [2, "Preview image/copy Zalo creative"],
            [3, "Approve with optional note OR Reject PORTAL-UC-009 comment"],
            [4, "Staff notified; SVC launch QA can proceed on approve"],
        ],
        alt=[
            ["E1", "Budget over threshold → GDKD approves on ops not portal"],
        ],
        io_in="creative_id, decision, comment?",
        io_out="approval audit, status update",
        rules=["BR-PORTAL-014", "BR-PORTAL-006", "BR-PORTAL-009", "BR-ZALO-019"],
    ),
    "PORTAL-UC-015": uc_detail(
        "PORTAL-UC-015",
        "Google performance view",
        screens="SCR-PORTAL-008",
        actor="Client Viewer",
        goal="Read-only Google Ads KPI summary on portal",
        trigger="Navigate /google when google_enabled",
        pre="Google channel mapped SVC-UC-008; sync OK",
        post="Client-safe metrics visible; no internal fields",
        priority="P1",
        wave="Wave R2",
        api="GET /portal/google/performance",
        main=[
            [1, "Client open /google when module enabled"],
            [2, "View spend/leads/CPL read-only scoped client"],
            [3, "Date range filter 7d/30d"],
            [4, "Attribution disclaimer footer"],
        ],
        alt=[
            ["E1", "Module in progress → partial data yellow banner"],
        ],
        io_in="JWT client_id, date_range",
        io_out="Google KPI summary JSON",
        rules=["BR-PORTAL-015", "BR-PORTAL-002"],
    ),
}
