"""Manual BA use-case details — Mobile Experience (MOB-UC-001 … MOB-UC-010)."""
from __future__ import annotations

from rnosai_ba_detail_helpers import uc_detail

MOB_USE_CASE_DETAILS: dict[str, dict] = {
    "MOB-UC-001": uc_detail(
        "MOB-UC-001",
        "Cài PWA staff",
        screens="SCR-MOB-001",
        actor="CSKH / Sales",
        goal="Cài ops-web lên màn hình chính — mở lead nhanh ngoài văn phòng",
        trigger="User truy cập rs.pttads.vn trên mobile browser; beforeinstallprompt",
        pre="NEXT_PUBLIC_PWA_ENABLED=1; staff JWT login thành công",
        post="App standalone; start_url /crm/leads",
        priority="P0",
        wave="RNOS-M1",
        trace="RNOS-41, TC-MOB-01",
        api="GET /manifest.webmanifest · GET /sw.js · staff auth unchanged",
        main=[
            [1, "User mở ops-web trên viewport ≤768px"],
            [2, "PwaShell hiện banner «Thêm vào màn hình chính»"],
            [3, "User chấp nhận install hoặc Add to Home Screen thủ công"],
            [4, "Service worker register ptt-ops-pwa-v1"],
            [5, "Icon shortcut mở /crm/leads MOB-UC-002"],
        ],
        alt=[
            ["E1", "PWA disabled env → banner ẩn, SW không register"],
            ["E2", "User dismiss banner → sessionStorage không hiện lại phiên này"],
            ["E3", "iOS Safari không beforeinstallprompt → hướng dẫn Share → Add to Home Screen"],
        ],
        io_in="browser install prompt, NEXT_PUBLIC_PWA_ENABLED",
        io_out="installed PWA shell, cached /crm/leads shell",
        rules=["BR-MOB-01", "BR-MOB-02", "BR-PLAT-002"],
    ),
    "MOB-UC-002": uc_detail(
        "MOB-UC-002",
        "Xem danh sách lead mobile",
        screens="SCR-MOB-002",
        actor="CSKH / Sales",
        goal="Duyệt lead dạng card trên điện thoại; tap mở chi tiết",
        trigger="Navigate /crm/leads @ viewport ≤768px",
        pre="Staff cap crm_leads.view; PWA hoặc mobile browser",
        post="Lead list filtered; tap → MOB-UC-003",
        priority="P0",
        wave="RNOS-M1",
        trace="RNOS-41, P0-1, TC-MOB-01",
        api="GET /api/v1/leads · GET /api/v1/ai/scores/batch (pilot)",
        main=[
            [1, "CSS ẩn table .crm-leads-table-wrap"],
            [2, "Render .crm-leads-cards với tên, SĐT, status, AI score"],
            [3, "Filter/search giữ nguyên desktop behavior"],
            [4, "Tap card → /crm/leads/[id]"],
            [5, "Pull refresh optional P2 — network-first list"],
        ],
        alt=[
            ["E1", "Empty list → empty state card"],
            ["E2", "Offline navigate → SW fallback cached shell + banner mạng"],
        ],
        io_in="JWT staff, filter params",
        io_out="lead card list JSON",
        rules=["BR-MOB-02", "BR-MOB-05", "BR-CRM-001"],
    ),
    "MOB-UC-003": uc_detail(
        "MOB-UC-003",
        "Xem chi tiết + AI brief lead",
        screens="SCR-MOB-003",
        actor="CSKH",
        goal="Đọc lead detail + copilot brief trên mobile; không auto-send",
        trigger="Tap lead card MOB-UC-002 hoặc deep link /crm/leads/[id]",
        pre="Lead exists; owner hoặc cap view team",
        post="Activity logged nếu user action; copilot draft copy-only",
        priority="P0",
        wave="RNOS-M1",
        trace="AI-UC-002, RNOS-41",
        api="GET /api/v1/leads/:id · POST /api/v1/ai/copilot/*",
        main=[
            [1, "Load /crm/leads/[id] — @<1024px tab bar Chi tiết/Hoạt động/AI"],
            [2, "Tab Chi tiết: DL fields + Copy SĐT/Zalo + status/assign forms"],
            [3, "Tab Hoạt động: chọn activity → tab AI summarize"],
            [4, "Tab AI: LeadCopilotPanel brief 5 bullets + follow-up draft copy-only"],
            [5, "Tablet 1024–1279: FAB → drawer copilot; desktop ≥1280 inline column"],
        ],
        alt=[
            ["E1", "Copilot offline → banner «Copilot cần kết nối mạng» trên tab AI"],
            ["E2", "Pilot flag off → copilot hidden CRM core OK"],
        ],
        io_in="lead_id, staff JWT",
        io_out="lead detail, AI brief JSON",
        rules=["BR-MOB-04", "BR-AI-001", "BR-AI-002", "BR-MOB-05"],
    ),
    "MOB-UC-004": uc_detail(
        "MOB-UC-004",
        "Offline đọc lead đã cache",
        screens="SCR-MOB-002, SCR-MOB-003",
        actor="CSKH",
        goal="Đọc shell lead list/detail đã precache khi mất mạng",
        trigger="Navigate offline sau khi đã visit /crm/leads online",
        pre="SW installed; /crm/leads cached navigate once",
        post="Read-only view; POST/PATCH blocked with banner",
        priority="P1",
        wave="RNOS-M1",
        trace="RNOS-41",
        api="Không cache /api/* — chỉ shell + static",
        main=[
            [1, "SW navigate network-first fail"],
            [2, "Fallback cache /crm/leads hoặc /login"],
            [3, "Hiển thị cached HTML shell"],
            [4, "Banner «Cần mạng để cập nhật» trên mọi write action"],
            [5, "Reconnect → auto refresh list"],
        ],
        alt=[
            ["E1", "Chưa từng online → 503 text/plain VN"],
        ],
        io_in="cached Request navigate",
        io_out="cached page or 503",
        rules=["BR-MOB-02"],
    ),
    "MOB-UC-005": uc_detail(
        "MOB-UC-005",
        "Cài PWA portal",
        screens="SCR-MOB-005",
        actor="Client Approver",
        goal="Cài portal.pttads.vn PWA — duyệt creative nhanh",
        trigger="Approver mở portal mobile; beforeinstallprompt",
        pre="NEXT_PUBLIC_PWA_ENABLED=1 portal-web; portal JWT",
        post="Standalone app start_url /dashboard",
        priority="P0",
        wave="RNOS-M2",
        trace="RNOS-M2, TC-MOB-02",
        api="GET /manifest.webmanifest · GET /sw.js ptt-portal-pwa-v1",
        main=[
            [1, "PortalPwaShell banner «Cài PTT Portal»"],
            [2, "User install → standalone display"],
            [3, "SW register scope /"],
            [4, "Bottom nav MOB SCR-MOB-006 visible"],
            [5, "Session portal JWT unchanged BR-MOB-01 staff/portal split"],
        ],
        alt=[
            ["E1", "PWA flag 0 → no banner"],
            ["E2", "iOS manual Add to Home Screen"],
        ],
        io_in="portal build flags",
        io_out="installed portal PWA",
        rules=["BR-MOB-01", "BR-PLAT-003"],
    ),
    "MOB-UC-006": uc_detail(
        "MOB-UC-006",
        "Nhận push duyệt creative",
        screens="SCR-MOB-007, SCR-MOB-009",
        actor="Client Approver",
        goal="Nhận web push khi creative/email pending; tap mở inbox",
        trigger="PortalNotificationService.emitCreativePending → PortalPushSenderService",
        pre="MOB-UC-009 subscription active; VAPID configured",
        post="Notification shown; click → /creatives or /notifications",
        priority="P0",
        wave="RNOS-M2",
        trace="PORTAL-UC-006, TC-MOB-02",
        api="POST /api/v1/portal/push/subscribe · web-push send",
        main=[
            [1, "Staff submit creative → emit notification"],
            [2, "Insert portal_notification + push payload"],
            [3, "SW push handler showNotification"],
            [4, "notificationclick → clients.openWindow link_url"],
            [5, "Approver duyệt trên SCR-MOB-007"],
        ],
        alt=[
            ["E1", "No subscription → in-app only portal_notification"],
            ["E2", "Stale endpoint 410 → auto delete subscription"],
            ["E3", "Push disabled → webhook stub only"],
        ],
        io_in="creative pending event, subscription rows",
        io_out="push notification + in-app row",
        rules=["BR-MOB-03", "BR-PORTAL-006", "BR-SYS-004"],
    ),
    "MOB-UC-007": uc_detail(
        "MOB-UC-007",
        "Duyệt email campaign mobile",
        screens="SCR-MOB-008",
        actor="Client Approver",
        goal="Approve/reject email campaign trên mobile viewport",
        trigger="Navigate /email/approvals @ ≤768px hoặc từ push MOB-UC-006",
        pre="email_enabled; role approver; pending campaign exists",
        post="Decision recorded EM-UC-007 dual approval flow",
        priority="P0",
        wave="RNOS-M2",
        trace="PORTAL-UC-008, EM-UC-007",
        api="GET portal email approvals · POST approve/reject",
        main=[
            [1, "Mobile card list thay table @768px"],
            [2, "Tap campaign → preview modal mobile 320px tab"],
            [3, "Approve hoặc Reject + comment nếu reject"],
            [4, "Toast success + badge bottom nav cập nhật"],
            [5, "Temporal/workflow signal nếu configured"],
        ],
        alt=[
            ["E1", "Viewer role → read-only notice"],
            ["E2", "Module disabled → feature flag message"],
        ],
        io_in="campaign_id, decision, comment",
        io_out="approval status updated",
        rules=["BR-PORTAL-008", "BR-EM-007", "BR-MOB-05"],
    ),
    "MOB-UC-008": uc_detail(
        "MOB-UC-008",
        "Xem KPI dashboard mobile",
        screens="SCR-MOB-006",
        actor="Client Viewer / Approver",
        goal="Xem KPI tiles 2-col grid trên mobile; pending badges",
        trigger="Open /dashboard @ ≤768px hoặc bottom nav Home",
        pre="Portal JWT; modules enabled",
        post="Read-only KPI; tap drill module routes",
        priority="P1",
        wave="RNOS-M2",
        trace="PORTAL-UC-002",
        api="GET /api/v1/portal/performance · notification summary",
        main=[
            [1, "PortalMobileBottomNav Home active"],
            [2, "KPI cards 2-column scroll vertical"],
            [3, "Pending creative/email badges on nav"],
            [4, "Attribution disclaimer footer visible"],
            [5, "Tap module card → /meta /seo /email routes"],
        ],
        alt=[
            ["E1", "Module off → card hidden"],
        ],
        io_in="client_id JWT, date_range",
        io_out="KPI summary JSON",
        rules=["BR-PORTAL-002", "BR-SYS-005"],
    ),
    "MOB-UC-009": uc_detail(
        "MOB-UC-009",
        "Quản lý subscription push",
        screens="SCR-MOB-010",
        actor="Client Approver",
        goal="Bật/tắt web push; test notification; lưu endpoint PG",
        trigger="Settings → Bật thông báo đẩy",
        pre="Browser Notification + PushManager support; PTT_PORTAL_PUSH_ENABLED",
        post="Row portal_push_subscriptions; VAPID subscribe OK",
        priority="P1",
        wave="RNOS-M2",
        trace="RNOS-M2, TC-MOB-02",
        api="GET push/vapid-public-key · POST/DELETE push/subscribe · POST push/test",
        main=[
            [1, "usePortalPush fetch VAPID public key"],
            [2, "Notification.requestPermission granted"],
            [3, "pushManager.subscribe → POST subscribe API"],
            [4, "Gửi test push verify sender"],
            [5, "Tắt → unsubscribe + DELETE endpoint"],
        ],
        alt=[
            ["E1", "Permission denied → inline error"],
            ["E2", "Stub user stub:email → UUID column fail — dùng portal user thật prod"],
            ["E3", "VAPID missing → «Push chưa bật server»"],
        ],
        io_in="PushSubscription JSON, JWT",
        io_out="subscription_id stored",
        rules=["BR-MOB-03", "BR-PLAT-003"],
    ),
    "MOB-UC-010": uc_detail(
        "MOB-UC-010",
        "Deep link từ email/SMS",
        screens="SCR-MOB-007, SCR-MOB-008",
        actor="Client Approver",
        goal="Mở thẳng màn duyệt từ link email/SMS hoặc native shell M3",
        trigger="Tap link https://portal.pttads.vn/creatives?… hoặc pttads://approve/{id}",
        pre="Valid session hoặc login redirect; M3 Capacitor optional",
        post="Target approval screen loaded scoped tenant",
        priority="P2",
        wave="RNOS-M3",
        trace="Capacitor shell README",
        api="Universal link / @capacitor/app App plugin",
        main=[
            [1, "User tap link in email/SMS"],
            [2, "Browser or Capacitor opens portal route"],
            [3, "Login gate if session expired → return URL preserved"],
            [4, "Land creative/email approval detail"],
            [5, "Complete decision MOB-UC-006/007"],
        ],
        alt=[
            ["E1", "Expired JWT → /login?next= encoded path"],
            ["E2", "Wrong tenant → 403 archived"],
        ],
        io_in="deep link URL, optional token",
        io_out="approval screen rendered",
        rules=["BR-MOB-01", "BR-SYS-011", "BR-PORTAL-001"],
    ),
}
