"""Manual BA use-case details — Email Marketing (EM-UC-001 … EM-UC-014)."""
from __future__ import annotations

from rnosai_ba_detail_helpers import uc_detail

EM_USE_CASE_DETAILS: dict[str, dict] = {
    "EM-UC-001": uc_detail(
        "EM-UC-001",
        "Onboard email workspace & domain",
        screens="SCR-EM-001",
        actor="Email Strategist / AM",
        goal="Workspace active với domain authenticated SPF/DKIM/DMARC",
        trigger="HĐ Email Marketing; SYS-UC-001 module step",
        pre="PTT_EMAIL_ENABLED=1; customer active",
        post="Sending domain verified; hub deliverability status green/yellow",
        priority="P0",
        wave="Wave R1",
        trace="SYS-001, TC-EM-01",
        api="POST /email/workspaces · domain wizard E-11 · /email/deliverability",
        main=[
            [1, "Tạo email workspace per client"],
            [2, "Domain onboarding wizard: SPF, DKIM, DMARC, ESP verify"],
            [3, "Warm-up plan documented"],
            [4, "Hub /email/hub shows deliverability status"],
        ],
        alt=[
            ["E1", "DNS pending → yellow status until verify pass"],
            ["E2", "Send without verified domain → blocked TC-EM-01"],
        ],
        io_in="client_id, domain, DNS records, ESP config",
        io_out="workspace_id, domain verify status, warm-up doc ref",
        rules=["BR-EM-001"],
    ),
    "EM-UC-002": uc_detail(
        "EM-UC-002",
        "Capture form → consent",
        screens="SCR-EM-003",
        actor="System / End Subscriber",
        goal="Capture contact với consent log immutable",
        trigger="Public form submit embedded site",
        pre="Form embed configured; capture API active",
        post="Contact created subscribed hoặc pending_confirm; GDPR log",
        priority="P0",
        wave="Wave R1",
        api="POST /email/contacts/capture · double opt-in mailer",
        main=[
            [1, "Embed form POST → capture API"],
            [2, "Record consent timestamp, source, IP hashed"],
            [3, "Double opt-in email if policy enabled"],
            [4, "Contact created subscribed or pending_confirm"],
        ],
        alt=[
            ["E1", "Invalid email → 400 validation message"],
            ["E2", "Suppressed email → reject with generic message"],
        ],
        io_in="form fields, consent checkbox, source URL",
        io_out="contact_id, consent record, opt-in status",
        rules=["BR-EM-002", "BR-EM-009"],
    ),
    "EM-UC-003": uc_detail(
        "EM-UC-003",
        "Import contacts CSV",
        screens="SCR-EM-003",
        actor="Email Strategist",
        goal="Batch import contacts với dedup và suppression check",
        trigger="Strategist upload CSV import UI",
        pre="CSV template valid; workspace active",
        post="Import job log; tags applied",
        priority="P0",
        wave="Wave R1",
        api="POST /email/contacts/import · preview + confirm batch",
        main=[
            [1, "E-04 import UI → upload CSV"],
            [2, "Map columns; validate email format"],
            [3, "Dedup + suppression check EM-UC-009"],
            [4, "Preview → confirm batch import"],
        ],
        alt=[
            ["E1", "High bounce list → quarantine import; compliance review"],
        ],
        io_in="CSV file, column mapping, tags",
        io_out="import job id, inserted/updated/skipped counts",
        rules=["BR-EM-003", "BR-EM-009"],
    ),
    "EM-UC-004": uc_detail(
        "EM-UC-004",
        "Segment compute (RFM/behavior)",
        screens="SCR-EM-003",
        actor="Email Strategist / System",
        goal="Compute và cache segment membership RFM/behavior",
        trigger="Save segment hoặc scheduled recompute",
        pre="Contact data populated",
        post="Segment member count cached; recompute on schedule",
        priority="P0",
        wave="Wave R1",
        api="POST /email/segments/:id/compute · segment builder E-05",
        main=[
            [1, "Segment Builder tabs Rules/Static/Lifecycle/RFM/Behavior"],
            [2, "Define criteria → Compute segment size"],
            [3, "Save segment version"],
            [4, "Use in campaign or journey targeting"],
        ],
        alt=[
            ["E1", "Empty criteria → block save validation"],
        ],
        io_in="segment rules JSON, client_id",
        io_out="segment_id, member_count, version",
        rules=["BR-EM-004"],
    ),
    "EM-UC-005": uc_detail(
        "EM-UC-005",
        "Template studio + preflight",
        screens="SCR-EM-004",
        actor="Email Strategist",
        actor_secondary="Creative",
        goal="Template pass preflight trước attach campaign",
        trigger="Create/edit template E-06",
        pre="Brand assets ready",
        post="Preflight pass required before send configurable strict",
        priority="P0",
        wave="Wave R1",
        api="/email/templates · preflight API",
        main=[
            [1, "Template studio drag blocks, merge tags"],
            [2, "Preflight: broken links, alt text, spam score, dark mode"],
            [3, "Save template version"],
            [4, "Attach to campaign EM-UC-006"],
        ],
        alt=[
            ["E1", "Preflight fail → block attach until fix"],
        ],
        io_in="template HTML/blocks, merge tags, brand assets",
        io_out="template version id, preflight report",
        rules=["BR-EM-005"],
    ),
    "EM-UC-006": uc_detail(
        "EM-UC-006",
        "Campaign broadcast F1",
        screens="SCR-EM-002",
        actor="Email Strategist",
        goal="Schedule hoặc send broadcast F1 với approval gate",
        trigger="Schedule or send now",
        pre="Template + segment ready; domain verified",
        post="Campaign status scheduled/sending/sent",
        priority="P0",
        wave="Wave R1",
        api="/email/campaigns · campaign API F1 flow",
        main=[
            [1, "Create campaign: name, segment, template, subject, from"],
            [2, "Test send to staff list"],
            [3, "Submit → staff approval EM-UC-007"],
            [4, "On approve → queue ESP send EM-UC-008"],
        ],
        alt=[
            ["E1", "Governance block EM-UC-012 → warn/block on submit"],
        ],
        io_in="campaign config, segment_id, template_id, schedule",
        io_out="campaign_id, status, approval state",
        rules=["BR-EM-006", "BR-EM-007", "BR-EM-012"],
    ),
    "EM-UC-007": uc_detail(
        "EM-UC-007",
        "Staff + client approval",
        screens="SCR-EM-002, SCR-PORTAL-005",
        actor="Email Strategist / Client Approver",
        actor_secondary="Compliance",
        goal="Dual approval staff + client trước ESP send",
        trigger="Campaign draft submitted",
        pre="Campaign draft ready; governance rules evaluated",
        post="Approval audit who/when/version id",
        priority="P0",
        wave="Wave R1",
        trace="SYS-004",
        api="Temporal workflow · portal PORTAL-UC-008 · compliance gate",
        main=[
            [1, "Strategist submit → internal compliance review optional"],
            [2, "Client approver portal PORTAL-UC-008"],
            [3, "Approve → unlock send; Reject → draft + comment"],
            [4, "Audit chain immutable PLAT-UC-008"],
        ],
        alt=[
            ["E1", "Client SLA timeout → escalate AM notify"],
        ],
        io_in="campaign_id, approval chain config",
        io_out="approval decisions[], unlock send flag",
        rules=["BR-EM-007", "BR-PORTAL-008", "BR-SYS-004", "BR-PLAT-008"],
    ),
    "EM-UC-008": uc_detail(
        "EM-UC-008",
        "ESP send & webhook engagement",
        screens="SCR-EM-002",
        actor="System",
        goal="Batch send ESP và ingest engagement events",
        trigger="Campaign approved; send window reached",
        pre="Campaign approved; suppression applied",
        post="Engagement metrics on reports EM-UC-013",
        priority="P0",
        wave="Wave R1",
        trace="PLAT-006",
        api="ESP batch API · PLAT-UC-006 webhook · /email/campaigns/:id/stats",
        main=[
            [1, "Worker batch send via ESP SendGrid/SES"],
            [2, "PLAT-UC-006 ingest delivered/open/click/bounce"],
            [3, "Update campaign stats real-time"],
            [4, "Bounce → auto suppression EM-UC-009"],
        ],
        alt=[
            ["E1", "ESP rate limit → retry queue PLAT-UC-007"],
        ],
        io_in="campaign send batch, recipient list scoped",
        io_out="send job id, engagement events[], stats",
        rules=["BR-EM-008", "BR-PLAT-006", "BR-EM-009"],
    ),
    "EM-UC-009": uc_detail(
        "EM-UC-009",
        "Suppression & one-click unsub",
        screens="SCR-EM-003",
        actor="System / End Subscriber",
        goal="Global suppression honored on all future sends",
        trigger="One-click unsub hoặc bounce/spam complaint",
        pre="Suppression list active per workspace",
        post="Future sends exclude contact; audit reason",
        priority="P0",
        wave="Wave R1",
        api="List-Unsubscribe header · suppression API · EM-UC-014 sync",
        main=[
            [1, "List-Unsubscribe header + preference link in sends"],
            [2, "One-click POST → global suppression list"],
            [3, "Future sends exclude contact"],
            [4, "Audit reason timestamp source"],
        ],
        alt=[
            ["E1", "Resubscribe via preference center EM-UC-014 with new consent"],
        ],
        io_in="contact email, unsub reason, source",
        io_out="suppression record, updated contact status",
        rules=["BR-EM-009", "BR-EM-014"],
    ),
    "EM-UC-010": uc_detail(
        "EM-UC-010",
        "Deliverability incident F3",
        screens="SCR-EM-007",
        actor="Email Strategist / Compliance",
        actor_secondary="DevOps",
        goal="Pause sends và remediate bounce/blocklist spike",
        trigger="Bounce rate spike, blocklist, domain fail",
        pre="Hub monitoring active; alert channels configured",
        post="Incident ticket closed; post-mortem",
        priority="P0",
        wave="Wave R1",
        api="/email/deliverability · F3 runbook · pause send API",
        main=[
            [1, "Hub alert banner + Slack/Teams EM-UC-013 alerts"],
            [2, "Pause sends for domain/client"],
            [3, "DNS/ESP remediation checklist"],
            [4, "Resume after verify + soak"],
        ],
        alt=[
            ["E1", "False positive → resume with monitoring window"],
        ],
        io_in="incident metrics, domain, client scope",
        io_out="incident id, pause/resume audit, post-mortem",
        rules=["BR-EM-010"],
    ),
    "EM-UC-011": uc_detail(
        "EM-UC-011",
        "Journey automation activate",
        screens="SCR-EM-005",
        actor="Email Strategist",
        goal="Journey graph live với enroll cap respected",
        trigger="PTT_EMAIL_JOURNEYS=1 prod cutover",
        pre="Journey designed; test mode passed",
        post="Journey version live; enrollments tracked",
        priority="P1",
        wave="Wave R2",
        api="/email/journeys · journey engine activate",
        main=[
            [1, "Build journey graph trigger → wait → send → branch"],
            [2, "Test mode dry-run enrollments"],
            [3, "Activate journey version"],
            [4, "Monitor enrollments + cap alerts"],
        ],
        alt=[
            ["E1", "Enroll cap hit → pause enroll + notify strategist"],
        ],
        io_in="journey graph JSON, triggers, caps",
        io_out="journey version id, enrollment metrics",
        rules=["BR-EM-011"],
    ),
    "EM-UC-012": uc_detail(
        "EM-UC-012",
        "Governance rule CRUD",
        screens="SCR-EM-006",
        actor="Compliance / Admin",
        goal="Rules enforced pre-send với audit mọi thay đổi",
        trigger="Admin create/edit governance rules E-13",
        pre="Admin/compliance access",
        post="Rules saved; evaluate on campaign submit",
        priority="P1",
        wave="Wave R2",
        api="POST/PATCH/DELETE /email/governance/rules · E-13 UI",
        main=[
            [1, "Governance UI create/edit/delete rules"],
            [2, "Rules: max send rate, footer, banned keywords, quiet hours"],
            [3, "Evaluate on campaign submit block/warn"],
            [4, "Audit log every change SYS-UC-010"],
        ],
        alt=[
            ["E1", "Conflicting rules → priority order admin config"],
        ],
        io_in="rule definition JSON, scope client/global",
        io_out="rule id, evaluation result on submit",
        rules=["BR-EM-012", "BR-SYS-010"],
    ),
    "EM-UC-013": uc_detail(
        "EM-UC-013",
        "Reports & Grafana BI",
        screens="SCR-EM-008",
        actor="Email Strategist / AM",
        goal="Campaign performance reports + Grafana BI export",
        trigger="User opens /email/reports hoặc scheduled export",
        pre="Campaign data exists",
        post="Reports exported; BI status card updated",
        priority="P1",
        wave="Wave R2",
        api="/email/reports · GET /reports/bi-status · Grafana link",
        main=[
            [1, "E-12 reports: campaign, deliverability, segment growth"],
            [2, "Date range + client filter"],
            [3, "BI status card link Grafana if configured"],
            [4, "Export CSV/PDF client-safe metrics"],
        ],
        alt=[
            ["E1", "Grafana unreachable → inline report only"],
        ],
        io_in="date range, client_id, report type",
        io_out="report rows, export file, bi_status",
        rules=["BR-EM-013", "BR-PORTAL-005"],
    ),
    "EM-UC-014": uc_detail(
        "EM-UC-014",
        "Public preference center",
        screens="SCR-EM-003",
        actor="End Subscriber",
        goal="Tokenized preference update và unsub all",
        trigger="Public URL token click from email",
        pre="Token valid not expired",
        post="Consent preferences updated; sync suppression",
        priority="P0",
        wave="Wave R1",
        api="Public preference routes · EM spec §preference",
        main=[
            [1, "Public URL tokenized → view subscriptions"],
            [2, "Update topic preferences or frequency"],
            [3, "Unsubscribe all one-click"],
            [4, "Confirmation page + sync EM-UC-009"],
        ],
        alt=[
            ["E1", "Expired token → request new link flow"],
        ],
        io_in="preference token, selected topics, unsub flag",
        io_out="updated preferences, suppression sync",
        rules=["BR-EM-014", "BR-EM-009"],
    ),
}
