#!/usr/bin/env bash
# Gate R1 — Pilot cohort enable helper (dry-run by default)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COHORT="${R1_PILOT_COHORT:-$ROOT/deploy/pilot-cohort.json}"
OUT="${R1_PILOT_ENV_OUT:-$ROOT/.local-dev/r1-pilot-env.sh}"
APPLY=0

usage() {
  cat <<EOF
Usage: bash scripts/rnos_r1_pilot_enable.sh [--apply] [--cohort PATH] [--out PATH]

Validates pilot-cohort JSON and prints Nest + ops-web env exports.
Default is dry-run (print only). --apply writes snippet to OUT (gitignored path).

Before prod:
  1. Copy deploy/pilot-cohort.example.json → pilot-cohort.json with real staff UUIDs
  2. bash scripts/rnos_r1_prod_pilot_gate.sh
  3. bash scripts/rnos_r1_pilot_enable.sh --apply
  4. Source OUT on VPS + rebuild ops-web + restart ptt-crm-api
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply) APPLY=1; shift ;;
    --cohort) COHORT="$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ ! -f "$COHORT" ]]; then
  echo "FAIL: cohort file not found: $COHORT" >&2
  echo "Copy deploy/pilot-cohort.example.json → pilot-cohort.json and fill real UUIDs." >&2
  exit 1
fi

python3 - <<PY
import json, sys
from pathlib import Path
p = Path("$COHORT")
data = json.loads(p.read_text())
members = data.get("members") or []
if len(members) < 5:
    sys.exit(f"Need ≥5 pilot members, got {len(members)}")
nest = data.get("nest_env") or {}
ops = data.get("ops_web_build_env") or {}
if nest.get("PTT_AI_COPILOT_ENABLED") != "1":
    sys.exit("nest_env.PTT_AI_COPILOT_ENABLED must be 1")
ids = nest.get("PTT_AI_PILOT_USER_IDS", "")
if not ids or ids.count(",") < 3:
    sys.exit("nest_env.PTT_AI_PILOT_USER_IDS must list 5–8 UUIDs")
print(f"OK  cohort {p.name}: {len(members)} members, wave={data.get('wave','?')}")
PY

NEST_BLOCK=$(python3 - <<PY
import json
from pathlib import Path
data = json.loads(Path("$COHORT").read_text())
nest = data.get("nest_env") or {}
for k, v in nest.items():
    print(f'export {k}="{v}"')
PY
)

OPS_BLOCK=$(python3 - <<PY
import json
from pathlib import Path
data = json.loads(Path("$COHORT").read_text())
ops = data.get("ops_web_build_env") or {}
for k, v in ops.items():
    print(f'export {k}="{v}"')
PY
)

echo ""
echo "# Nest (ptt-crm-api EnvironmentFile / systemd)"
echo "$NEST_BLOCK"
echo ""
echo "# ops-web build (NEXT_PUBLIC_* at build time)"
echo "$OPS_BLOCK"
echo ""
echo "# Compliance — prod mandatory"
echo 'export PTT_AI_LOG_PII="0"'
echo 'export PTT_AI_LOG_PROMPTS="0"'

if [[ "$APPLY" -eq 1 ]]; then
  mkdir -p "$(dirname "$OUT")"
  {
    echo "# Generated by rnos_r1_pilot_enable.sh — do not commit"
    echo "# Source on VPS: set -a && source $OUT && set +a"
    echo "$NEST_BLOCK"
    echo 'export PTT_AI_LOG_PII="0"'
    echo 'export PTT_AI_LOG_PROMPTS="0"'
    echo ""
    echo "# ops-web rebuild with:"
    echo "# $OPS_BLOCK"
  } > "$OUT"
  echo ""
  echo "Wrote Nest env snippet → $OUT"
  echo "Rebuild ops-web with NEXT_PUBLIC_* from cohort ops_web_build_env block above."
fi
