"""Manual BA use-case details — Zalo Ads OS (ZALO-UC-001 … ZALO-UC-021)."""
from __future__ import annotations

from rnosai_ba_detail_helpers import uc_detail

ZALO_USE_CASE_DETAILS: dict[str, dict] = {
    "ZALO-UC-001": uc_detail(
        "ZALO-UC-001",
        "Kết nối Zalo Ads / OA",
        screens="SCR-AGENCY-001, SCR-ZALO-001",
        actor="Media Buyer / Tracking-Tech",
        actor_secondary="AM",
        goal="OAuth và lưu credential Zalo Ads/OA cho client agency",
        trigger="AM thêm channel account Zalo trên client detail",
        pre="Client agency tồn tại; Zalo Developer App đã tạo",
        post="client_channel_accounts channel=zalo có token hợp lệ + webhook configured",
        priority="P0",
        wave="Wave Z1",
        api="POST /clients/:id/channel-accounts · /zalo-ads/oauth/* · POST /webhooks/zalo",
        main=[
            [1, "AM mở /agency/clients/[id]?tab=channels"],
            [2, "Thêm channel account type=zalo + OA id / ad account id"],
            [3, "Bấm Connect Zalo → OAuth redirect → token lưu vault"],
            [4, "Cấu hình webhook Zalo trỏ POST /webhooks/zalo"],
            [5, "Hệ thống validate credential; hiển thị token status xanh/đỏ trên hub"],
        ],
        alt=[
            ["E1", "OAuth fail → banner lỗi; giữ stub credential_ref dev"],
            ["E2", "Pilot only → PTT_ZALO_ADS_PILOT chặn client ngoài list"],
            ["E3", "Token sắp hết hạn → alert AM refresh trước 24h"],
        ],
        io_in="client_id, oa_id, ad_account_id, oauth_code",
        io_out="credential_ref, token_expiry, webhook_status",
        rules=["BR-ZALO-001"],
    ),
    "ZALO-UC-002": uc_detail(
        "ZALO-UC-002",
        "Hub map campaign",
        screens="SCR-ZALO-001, SCR-AGENCY-001",
        actor="Media Buyer",
        goal="Map external Zalo campaign id ↔ hub contract / target CPL",
        trigger="Buyer mở tab campaigns hoặc hub unmapped banner",
        pre="Campaigns đã sync từ Zalo API",
        post="hub_campaign_map.channel=zalo; unmapped count giảm",
        priority="P0",
        wave="Wave Z0",
        api="POST /hub-campaign-maps · HubCampaignMapsPanel",
        main=[
            [1, "Buyer mở /agency/clients/[id]?tab=campaigns hoặc /zalo/zalo-ads"],
            [2, "Filter channel Zalo + client"],
            [3, "Chọn external campaign id → map contract / target CPL / RE project"],
            [4, "Lưu mapping → hub CPL tính đúng spend/leads"],
            [5, "Unmapped campaigns hiển thị vàng trên hub cho đến khi map"],
        ],
        alt=[
            ["E1", "Campaign archived trên Zalo → soft-unmap + audit"],
            ["E2", "Duplicate map → 409 conflict message"],
        ],
        io_in="external_campaign_id, client_id, contract_id, target_cpl_vnd",
        io_out="hub_campaign_map row + mapping audit",
        rules=["BR-ZALO-002"],
    ),
    "ZALO-UC-003": uc_detail(
        "ZALO-UC-003",
        "Sync insights → daily_performance",
        screens="SCR-ZALO-001",
        actor="System",
        actor_secondary="Media Buyer (manual sync)",
        goal="Đồng bộ metrics Zalo campaign-level vào daily_performance",
        trigger="Cron T+1 hoặc Buyer bấm Sync Zalo insights",
        pre="API credentials valid; client_channel_accounts active",
        post="daily_performance channel=zalo upserted; zalo_insights_sync_state updated",
        priority="P0",
        wave="Wave Z1",
        api="POST /clients/:id/sync/zalo-insights · job zalo_insights_sync",
        main=[
            [1, "Trigger manual hoặc cron scheduler"],
            [2, "Job zalo_insights_sync chạy qua ptt_worker"],
            [3, "Adapter lấy metrics campaign-level từ Zalo API"],
            [4, "Normalize spend, impressions, clicks, leads → upsert daily_performance"],
            [5, "Cập nhật zalo_insights_sync_state.last_sync_at"],
            [6, "Hub CPL tiles refresh sau sync"],
        ],
        alt=[
            ["E1", "Token expired → job fail; hub 🔴; alert AM"],
            ["E2", "Stub mode → sinh dữ liệu pilot cho demo client"],
            ["E3", "Partial API fail → retry slice; log failed campaign ids"],
        ],
        io_in="client_id, date_range, campaign_ids[]",
        io_out="daily_performance rows[], sync_state, job_run_id",
        rules=["BR-ZALO-003"],
    ),
    "ZALO-UC-004": uc_detail(
        "ZALO-UC-004",
        "Hub CPL staff",
        screens="SCR-ZALO-001",
        actor="Media Buyer / AM / Analyst",
        goal="Xem KPI Spend, Leads, CPL, CTR Zalo trên hub staff",
        trigger="User mở /zalo/zalo-ads",
        pre="Performance data synced (ZALO-UC-003)",
        post="KPI khớp closed-loop SYS-UC-002 channel=zalo",
        priority="P0",
        wave="Wave Z1",
        api="GET /zalo-ads/hub · export CSV",
        main=[
            [1, "Mở /zalo/zalo-ads trên ops-web"],
            [2, "Filter client, date range T-7/T-30/custom"],
            [3, "Xem tiles Spend, Leads, CPL, CTR, ROAS (nếu revenue map)"],
            [4, "Drill-down campaign row → chi tiết daily breakdown"],
            [5, "Export CSV snapshot cho AM/client report"],
        ],
        alt=[
            ["E1", "Unmapped spend → yellow banner; CPL client exclude unmapped"],
            ["E2", "No data period → empty state + link sync"],
        ],
        io_in="client_id, date_from, date_to, filters",
        io_out="KPI aggregates + campaign table + CSV file",
        rules=["BR-ZALO-004", "BR-SYS-002"],
    ),
    "ZALO-UC-005": uc_detail(
        "ZALO-UC-005",
        "Portal performance",
        screens="SCR-PORTAL-007",
        actor="Client Viewer",
        goal="Client xem KPI Zalo read-only scoped client_id",
        trigger="Client login portal → /zalo",
        pre="Portal account active; Zalo module enabled for client",
        post="JWT scope enforced; không thấy client khác",
        priority="P0",
        wave="Wave Z1",
        api="GET /portal/performance?channel=zalo",
        main=[
            [1, "Client login portal (PORTAL-UC-001)"],
            [2, "Navigate /zalo"],
            [3, "Xem KPI tiles read-only: spend, leads, CPL"],
            [4, "Optional date range filter 7d/30d"],
            [5, "Export CSV nếu cap portal.export enabled"],
        ],
        alt=[
            ["E1", "Module disabled → 404 hoặc empty module message"],
            ["E2", "Cross-tenant probe → 403 empty"],
        ],
        io_in="JWT client_id, date_range",
        io_out="Scoped KPI JSON / CSV",
        rules=["BR-ZALO-005", "BR-PORTAL-001", "BR-PORTAL-002"],
    ),
    "ZALO-UC-006": uc_detail(
        "ZALO-UC-006",
        "Brief chiến dịch",
        screens="SCR-ZALO-001, SCR-SVC-004",
        actor="AM / Media Buyer",
        actor_secondary="Client (review brief)",
        goal="Ghi nhận brief Zalo: mục tiêu, ngân sách, audience, form type",
        trigger="AM mở lifecycle stage Consult/Proposal",
        pre="Client active; service delivery workflow stage phù hợp",
        post="Brief saved; Buyer có thể tạo draft campaign",
        priority="P1",
        wave="Wave Z3",
        api="PATCH /service-delivery/:id/consult-brief",
        main=[
            [1, "AM mở /crm/service-delivery/[id] stage Consult"],
            [2, "Nhập mục tiêu, ngân sách VND, audience, form lead type"],
            [3, "Upload tài liệu tham khảo (PDF/image)"],
            [4, "Submit brief → status pending_buyer_review"],
            [5, "Media Buyer nhận notification → chuyển ZALO-UC-007"],
        ],
        alt=[
            ["E1", "Client reject brief → AM revise loop"],
        ],
        io_in="objective, budget_vnd, audience, form_type, attachments[]",
        io_out="brief_id, workflow_stage advance",
        rules=["BR-ZALO-006"],
    ),
    "ZALO-UC-007": uc_detail(
        "ZALO-UC-007",
        "Tạo campaign draft",
        screens="SCR-ZALO-001",
        actor="Media Buyer",
        goal="Tạo draft campaign Zalo nội bộ trước khi launch",
        trigger="Brief approved hoặc Buyer tạo mới từ hub",
        pre="Zalo account connected; brief approved (P1 path)",
        post="Draft status pending_approval; creative linked",
        priority="P1",
        wave="Wave Z3",
        trace="—",
        api="POST /zalo/campaigns/draft (future) · CRM creatives link",
        main=[
            [1, "Chọn client + Zalo account trên hub"],
            [2, "Nhập objective, budget, schedule, form lead mapping"],
            [3, "Gắn creative assets từ SCR-SVC-003 Creative Hub"],
            [4, "Lưu draft pending_approval"],
            [5, "Trigger approval workflow ZALO-UC-008"],
        ],
        alt=[
            ["E1", "v1 manual: Buyer tạo trên Zalo Ads UI → map ID (ZALO-UC-002)"],
            ["E2", "Missing creative → block save với checklist"],
        ],
        io_in="campaign draft payload, creative_ids[]",
        io_out="internal draft id, approval queue entry",
        rules=["BR-ZALO-007"],
    ),
    "ZALO-UC-008": uc_detail(
        "ZALO-UC-008",
        "Duyệt nội dung",
        screens="SCR-ZALO-001, SCR-PORTAL-004, SCR-SVC-003",
        actor="Creative Lead / Client Approver",
        actor_secondary="Media Buyer, Manager",
        goal="Dual approval creative Zalo trước launch",
        trigger="Buyer submit creative pending_client",
        pre="Creative uploaded; governance rules pass",
        post="Approval recorded; Launch QA eligible",
        priority="P1",
        wave="Wave Z3",
        api="POST /creatives/:id/approve · portal /creatives",
        main=[
            [1, "Buyer submit creative → pending_client"],
            [2, "Client duyệt trên portal /creatives (SYS-UC-004)"],
            [3, "Manager approve budget nếu vượt ngưỡng"],
            [4, "Creative Lead final QA pass"],
            [5, "Launch QA checklist SCR-SVC-001 pass → ready launch"],
        ],
        alt=[
            ["E1", "Client reject → comment bắt buộc (PORTAL-UC-009)"],
            ["E2", "Budget over threshold → GDKD approve required"],
        ],
        io_in="creative_id, approval_action, comment",
        io_out="approval audit, status approved|rejected",
        rules=["BR-ZALO-008", "BR-SYS-004"],
    ),
    "ZALO-UC-009": uc_detail(
        "ZALO-UC-009",
        "Triển khai lên Zalo (API)",
        screens="SCR-ZALO-001, SCR-SVC-002",
        actor="Media Buyer / System",
        goal="Push approved campaign lên Zalo Ads qua API",
        trigger="Draft approved + Launch QA pass",
        pre="ZALO-UC-008 complete; campaign-writes queue configured",
        post="Campaign live on Zalo; external id auto hub-mapped",
        priority="P2",
        wave="Wave Z4",
        api="campaign-writes queue · Zalo Ads API create campaign",
        main=[
            [1, "Hệ thống build payload Zalo API từ approved draft"],
            [2, "Enqueue campaign-writes job → worker execute"],
            [3, "Nhận external campaign id từ Zalo response"],
            [4, "Auto hub map (ZALO-UC-002)"],
            [5, "Audit log + notify AM/Media Buyer"],
        ],
        alt=[
            ["E1", "API không hỗ trợ write → manual launch + map ID (v1 workaround)"],
            ["E2", "API error → retry 3x; incident P1 if all fail"],
        ],
        io_in="approved draft_id, launch payload",
        io_out="external_campaign_id, launch audit, job status",
        rules=["BR-ZALO-009", "BR-SYS-003"],
    ),
    "ZALO-UC-010": uc_detail(
        "ZALO-UC-010",
        "Pause/update/stop campaign",
        screens="SCR-ZALO-001",
        actor="Media Buyer",
        goal="Điều khiển trạng thái campaign Zalo (pause/resume/budget)",
        trigger="Buyer chọn action trên hub campaign row",
        pre="Campaign live on Zalo; mapped on hub",
        post="Status updated via API hoặc manual audit",
        priority="P2",
        wave="Wave Z4",
        api="Zalo Ads API pause/resume/update · audit log",
        main=[
            [1, "Buyer mở campaign detail trên /zalo/zalo-ads"],
            [2, "Chọn Pause / Resume / Update budget / Stop"],
            [3, "Confirm modal với reason (governance)"],
            [4, "API call hoặc manual instruction logged"],
            [5, "Hub status sync sau action"],
        ],
        alt=[
            ["E1", "Emergency stop → META-UC-012 pattern cross-channel"],
            ["E2", "API deny → manual + ticket tracking"],
        ],
        io_in="campaign_id, action, new_budget_vnd, reason",
        io_out="updated campaign status, audit entry",
        rules=["BR-ZALO-010"],
    ),
    "ZALO-UC-011": uc_detail(
        "ZALO-UC-011",
        "Webhook lead → CRM",
        screens="SCR-ZALO-002, SCR-CRM-001",
        actor="System",
        actor_secondary="CSKH (consumer)",
        goal="Ingest lead realtime từ Zalo webhook vào CRM",
        trigger="Zalo POST webhook lead event",
        pre="Webhook secret configured; endpoint live",
        post="Lead visible /crm/leads?channel=zalo với owner assigned",
        priority="P0",
        wave="Wave Z0",
        trace="PLAT-005",
        api="POST /webhooks/zalo · zalo-webhook.parser.ts",
        main=[
            [1, "Zalo POST webhook payload tới /webhooks/zalo"],
            [2, "Verify HMAC signature (PLAT-UC-005)"],
            [3, "Parse fields → normalize phone/name/form_id"],
            [4, "Dedup (ZALO-UC-013) → insert crm_leads channel=zalo"],
            [5, "Return HTTP 200 ack"],
            [6, "Trigger assignment CRM-UC-001 + score AI-UC-001"],
        ],
        alt=[
            ["E1", "Invalid signature → 401 + alert DevOps"],
            ["E2", "Missing phone → queue review CRM-UC-003"],
            ["E3", "Duplicate 24h → link existing lead id"],
        ],
        io_in="Zalo webhook JSON, X-Signature headers",
        io_out="lead_id, ingest audit, zalo_lead_events row",
        rules=["BR-ZALO-011", "BR-PLAT-005", "BR-CRM-001"],
    ),
    "ZALO-UC-012": uc_detail(
        "ZALO-UC-012",
        "Poll form lead API",
        screens="SCR-ZALO-002",
        actor="System",
        goal="Poll lead từ Zalo form API bù webhook gap",
        trigger="Worker zalo_form_lead_poll theo cron",
        pre="Form API credentials; cursor initialized",
        post="Leads ingested SLA ≤15 phút từ submit form",
        priority="P0",
        wave="Wave Z2",
        api="openapi.zalo.me/v2.0/oa/form/get · POST /zalo/forms/:id/poll",
        main=[
            [1, "Worker đọc zalo_lead_form_sync_cursor"],
            [2, "Gọi Zalo form/get với since cursor"],
            [3, "Normalize + dedup (ZALO-UC-013)"],
            [4, "Push CRM pipeline (ZALO-UC-014)"],
            [5, "Advance cursor; log poll batch metrics"],
        ],
        alt=[
            ["E1", "Rate limit → backoff exponential"],
            ["E2", "Empty batch → skip advance cursor"],
        ],
        io_in="form_id, cursor_timestamp, oa_id",
        io_out="leads_created[], cursor_new, poll_run_id",
        rules=["BR-ZALO-012", "BR-ZALO-011"],
    ),
    "ZALO-UC-013": uc_detail(
        "ZALO-UC-013",
        "Dedup & chuẩn hóa lead",
        screens="SCR-ZALO-002, SCR-CRM-001",
        actor="System",
        goal="Chuẩn hóa phone/email và chống trùng lead Zalo",
        trigger="Mọi ingest path webhook hoặc poll",
        pre="Lead ingest active",
        post="Duplicate flagged; fingerprint logged",
        priority="P0",
        wave="Wave Z0/Z2",
        trace="CRM-001",
        api="dedup engine · zalo_lead_events",
        main=[
            [1, "Normalize phone VN (+84/0xxx → E.164 internal)"],
            [2, "Normalize email lowercase trim"],
            [3, "Fingerprint hash phone+client_id"],
            [4, "Match existing lead within 24h window → mark duplicate"],
            [5, "Log zalo_lead_events với dedup decision"],
        ],
        alt=[
            ["E1", "Same phone different client → separate leads (tenant isolation)"],
            ["E2", "Invalid phone → queue manual review"],
        ],
        io_in="raw lead fields, client_id, source_event_id",
        io_out="normalized lead, is_duplicate flag, merge_target_id?",
        rules=["BR-ZALO-013", "BR-CRM-001"],
    ),
    "ZALO-UC-014": uc_detail(
        "ZALO-UC-014",
        "CRM pipeline",
        screens="SCR-CRM-001, SCR-CRM-002, SCR-ZALO-002",
        actor="CSKH",
        actor_secondary="System (auto-assign)",
        goal="CSKH xử lý lead Zalo trên pipeline CRM chuẩn",
        trigger="Lead assigned sau ingest",
        pre="Lead assigned owner (CRM-UC-001)",
        post="Pipeline stage tracked; timeline updated",
        priority="P0",
        wave="Wave Z0",
        api="GET/PATCH /api/v1/leads/:id · activity timeline",
        main=[
            [1, "Lead auto-assign owner theo rule"],
            [2, "CSKH nhận notification in-app"],
            [3, "Mở /crm/leads/[id] → log call/note"],
            [4, "Advance status B1/B2 theo CRM-UC-002"],
            [5, "Attribution chips link về /zalo/zalo-ads campaign"],
        ],
        alt=[
            ["E1", "No owner match → GDKD review queue"],
            ["E2", "Lost lead → reason code + stop nurture"],
        ],
        io_in="lead_id, activity, status transition",
        io_out="updated pipeline stage, SLA metrics",
        rules=["BR-ZALO-014", "BR-CRM-002"],
    ),
    "ZALO-UC-015": uc_detail(
        "ZALO-UC-015",
        "CRM status sync hub",
        screens="SCR-ZALO-001, SCR-CRM-002",
        actor="System",
        goal="Đồng bộ Won/Lost CRM ngược lên hub conversion metrics",
        trigger="CRM lead/customer status change domain event",
        pre="Lead mapped to Zalo campaign on hub",
        post="Hub CPL/CPA conversion metrics updated",
        priority="P1",
        wave="Wave Z2",
        api="domain event consumer · hub metrics recompute",
        main=[
            [1, "CRM emit lead.status_changed / customer.converted"],
            [2, "Worker map lead → hub campaign via attribution"],
            [3, "Recompute conversion count + revenue (if mapped)"],
            [4, "Update hub tiles CPA/CPL closed-loop"],
            [5, "Optional portal KPI refresh cache"],
        ],
        alt=[
            ["E1", "Unmapped campaign → skip conversion; flag in hub"],
        ],
        io_in="lead_id, new_status, converted_revenue_vnd?",
        io_out="hub conversion metrics delta",
        rules=["BR-ZALO-015", "BR-SYS-002"],
    ),
    "ZALO-UC-016": uc_detail(
        "ZALO-UC-016",
        "Xuất báo cáo KH",
        screens="SCR-PORTAL-007, SCR-ZALO-001",
        actor="AM / Analyst",
        goal="Export báo cáo Zalo CSV/PDF cho khách hàng",
        trigger="Reporting period closed hoặc AM manual export",
        pre="Hub data synced; period closed",
        post="Report delivered portal hoặc email (SYS-UC-005)",
        priority="P1",
        wave="Wave Z2",
        trace="SYS-005",
        api="GET /zalo-ads/hub/export · portal artifact download",
        main=[
            [1, "AM chọn client + period trên hub"],
            [2, "Preview KPI summary table"],
            [3, "Export CSV hoặc generate PDF template"],
            [4, "Upload artifact to portal /settings exports"],
            [5, "Optional email notify client (SYS-UC-005)"],
        ],
        alt=[
            ["E1", "Unmapped spend warning in report footnote"],
        ],
        io_in="client_id, period, format csv|pdf",
        io_out="report file URL, delivery audit",
        rules=["BR-ZALO-016", "BR-SYS-005"],
    ),
    "ZALO-UC-017": uc_detail(
        "ZALO-UC-017",
        "Cảnh báo bất thường",
        screens="SCR-ZALO-001, SCR-AI-001",
        actor="System / Media Buyer",
        actor_secondary="GDKD (digest)",
        goal="Alert khi CPL spike, CTR drop, zero leads 24h",
        trigger="Rule engine scan daily hoặc realtime threshold",
        pre="Baseline metrics ≥7d; mapped campaigns exist",
        post="Notification Slack/email + hub banner",
        priority="P1",
        wave="Wave Z3",
        trace="AI-UC-019",
        api="alert module · AI anomaly digest cross-link",
        main=[
            [1, "Rule scan: CPL > target_cpl_vnd, CTR drop >30%, zero leads 24h"],
            [2, "Create alert record severity high/medium"],
            [3, "Hub banner on /zalo/zalo-ads link campaign detail"],
            [4, "Notify Media Buyer + AM via in-app/Slack"],
            [5, "Optional rollup vào AI-UC-019 anomaly digest"],
        ],
        alt=[
            ["E1", "False positive → user dismiss + tune threshold"],
            ["E2", "Insufficient data → skip alert with note"],
        ],
        io_in="daily_performance[], targets, thresholds",
        io_out="alert_id[], notifications sent",
        rules=["BR-ZALO-017", "BR-AI-019"],
    ),
    "ZALO-UC-018": uc_detail(
        "ZALO-UC-018",
        "Phân tích đa chiều",
        screens="SCR-ZALO-001",
        actor="Analyst / Media Buyer",
        goal="Drill hub theo creative/client/campaign dimension",
        trigger="Analyst mở analytics view trên hub",
        pre="Data ≥30 ngày trên daily_performance",
        post="Multi-dim chart rendered; export available",
        priority="P2",
        wave="Wave Z4",
        api="GET /zalo-ads/hub/breakdown · future ClickHouse BI",
        main=[
            [1, "Mở breakdown view trên hub"],
            [2, "Chọn dimensions: campaign, creative, date, placement"],
            [3, "Render chart/table compare periods"],
            [4, "Export CSV snapshot"],
            [5, "Optional link Grafana dashboard (future)"],
        ],
        alt=[
            ["E1", "Data <30d → show partial data warning"],
        ],
        io_in="dimensions[], metrics[], date_range",
        io_out="breakdown dataset, chart config, CSV",
        rules=["BR-ZALO-018"],
    ),
    "ZALO-UC-019": uc_detail(
        "ZALO-UC-019",
        "Client duyệt budget",
        screens="SCR-PORTAL-007, SCR-PORTAL-004",
        actor="Client Approver",
        goal="Client approve budget proposal Zalo trước launch",
        trigger="AM submit budget proposal > threshold",
        pre="Budget proposal ready on portal",
        post="Approval recorded; Buyer có thể launch",
        priority="P1",
        wave="Wave Z3",
        api="portal approval inbox · PATCH approval status",
        main=[
            [1, "AM tạo budget proposal gắn Zalo campaign draft"],
            [2, "Client nhận notification portal"],
            [3, "Mở /zalo hoặc /creatives approval inbox"],
            [4, "Review budget + creative preview"],
            [5, "Approve hoặc Reject với comment (PORTAL-UC-009)"],
        ],
        alt=[
            ["E1", "Partial approve → AM revise proposal"],
        ],
        io_in="proposal_id, approval_action, comment",
        io_out="approval audit, workflow unblock",
        rules=["BR-ZALO-019", "BR-PORTAL-006"],
    ),
    "ZALO-UC-020": uc_detail(
        "ZALO-UC-020",
        "Thông báo tiến độ",
        screens="SCR-PORTAL-009, SCR-ZALO-001",
        actor="System",
        actor_secondary="AM, Client Viewer",
        goal="Notify milestone: approve, launch, error, KPI target",
        trigger="Domain events: approval, launch, alert, milestone",
        pre="Portal notifications enabled (PORTAL-UC-010)",
        post="In-app notification delivered read/unread",
        priority="P1",
        wave="Wave Z3",
        api="portal notifications DDL · in-app bell",
        main=[
            [1, "Event: creative approved / campaign launched / alert fired"],
            [2, "Create portal_notification scoped client_id"],
            [3, "Client xem /notifications"],
            [4, "AM copy trên ops-web activity feed (optional)"],
            [5, "Mark read; retention policy 90d"],
        ],
        alt=[
            ["E1", "Email fallback nếu in-app disabled"],
        ],
        io_in="event_type, client_id, payload summary",
        io_out="notification_id, delivery status",
        rules=["BR-ZALO-020", "BR-PORTAL-010"],
    ),
    "ZALO-UC-021": uc_detail(
        "ZALO-UC-021",
        "Onboard orchestrator Zalo",
        screens="SCR-AGENCY-001, SCR-ZALO-001",
        actor="AM",
        goal="Onboard Zalo module qua orchestrator checklist SYS-UC-001",
        trigger="Client onboard wizard step Zalo",
        pre="Client record created (SYS-UC-001)",
        post="Zalo module enabled; all green checks",
        priority="P1",
        wave="Wave Z2",
        trace="SYS-001",
        api="onboarding-orchestrator · deep-links per step",
        main=[
            [1, "Tab onboard orchestrator hiển thị steps Zalo"],
            [2, "Step 1: Connect account (ZALO-UC-001)"],
            [3, "Step 2: Map campaign sample (ZALO-UC-002)"],
            [4, "Step 3: First sync insights (ZALO-UC-003)"],
            [5, "Step 4: Webhook test + first lead (ZALO-UC-011)"],
            [6, "All green → enable Zalo module flag for client"],
        ],
        alt=[
            ["E1", "Step fail → yellow state + deep-link fix"],
            ["E2", "Skip Zalo module → client without Zalo routes"],
        ],
        io_in="client_id, orchestrator checklist state",
        io_out="module_flags.zalo=true, checklist completion audit",
        rules=["BR-ZALO-021", "BR-SVC-002", "BR-SYS-001"],
    ),
}
