"""Deep SCR UI/API overrides — EM (Email Marketing) module."""

EM_SCR_OVERRIDES: dict[str, dict] = {
    "SCR-EM-002": {
        "module_key": "EM",
        "api": "GET/POST /api/v1/email/campaigns · GET segments/templates",
        "pre": "crm_email_mkt.view OR crm_agency.view; write cần crm_email_mkt.write",
        "post": "Campaign list filtered; create redirects to detail",
        "purpose": "Campaign builder EM-2 E-09 — list, filter, create broadcast",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff nav + logout"],
            [2, "SendPlatformBanner", "Alert", "Không", "emailSendEnabled() off warning"],
            [3, "ClientUuidFilter", "Input", "Không", "Scope list/create by client UUID"],
            [4, "StatusFilterTabs", "Tabs", "Có", "All/draft/pending_approval/approved/sending/sent"],
            [5, "CreateCampaignForm", "Form", "Không", "Name · template · segment — write cap"],
            [6, "CampaignsTable", "Table", "Có", "Name/client/segment/template/audience/status"],
            [7, "EmailStatusBadge", "Badge", "Có", "Status chip per row"],
            [8, "RowActions", "Button", "Có", "Mở · Review (draft)"],
            [9, "MobileCampaignCards", "Card", "Không", "Responsive duplicate of table"],
        ],
        "rules": ["BR-EM-006", "BR-EM-007"],
    },
    "SCR-EM-003": {
        "module_key": "EM",
        "api": "GET /api/v1/email/contacts · POST importEmailContacts",
        "pre": "crm_email_mkt.view; import cần write",
        "post": "Contacts listed; bulk import shows created/updated/skipped",
        "purpose": "Contact registry EM-1 E-04 — search, consent, bulk import",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "ClientUuidFilter", "Input", "Không", "?client_id= prefill"],
            [3, "SearchInput", "Input", "Không", "Filter email/name q"],
            [4, "BulkImportPanel", "Form", "Không", "Textarea email,first_name per line"],
            [5, "ImportResultBadge", "Badge", "Không", "created/updated/skipped counts"],
            [6, "ContactsTable", "Table", "Có", "Email · client · EmailConsentBadge · suppressed"],
            [7, "EmailEmptyState", "Alert", "Không", "Empty + Hub CTA"],
        ],
        "rules": ["BR-EM-002", "BR-EM-003"],
    },
    "SCR-EM-004": {
        "module_key": "EM",
        "api": "GET/POST /api/v1/email/templates",
        "pre": "crm_email_mkt.view; create cần write",
        "post": "Template created with default HTML → detail page",
        "purpose": "Template library EM-2 E-08 — list + quick create",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "ClientFilterRefresh", "Toolbar", "Không", "Client UUID + refresh"],
            [3, "CreateTemplateForm", "Form", "Không", "Name + subject — write cap"],
            [4, "TemplatesTable", "Table", "Có", "Name/client/subject/version/status · Mở"],
            [5, "ErrorBanner", "Alert", "Có", "API/auth failures"],
        ],
        "rules": ["BR-EM-005"],
    },
    "SCR-EM-005": {
        "module_key": "EM",
        "api": "GET/POST /api/v1/email/journeys",
        "pre": "crm_email_mkt.view; create cần write",
        "post": "Journey created → canvas detail SCR-EM-019",
        "purpose": "Journey list EM-3 E-10 — trigger type, enrolled count",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "ClientFilterRefresh", "Toolbar", "Không", "Client UUID + refresh"],
            [3, "CreateJourneyForm", "Form", "Không", "Name + create — write cap"],
            [4, "JourneysTable", "Table", "Có", "Name/client/trigger/enrolled/status · Canvas link"],
        ],
        "rules": ["BR-EM-011"],
    },
    "SCR-EM-006": {
        "module_key": "EM",
        "api": "GET/POST/PATCH/DELETE /api/v1/email/governance",
        "pre": "crm_email_mkt.view; write via API can_write OR settings cap",
        "post": "Rules CRUD + audit log last 50 entries",
        "purpose": "Governance hub E-13 — global/client rules + audit",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "ReadWriteBadge", "Badge", "Có", "Read-only vs write indicator"],
            [3, "ScopeSelector", "Select", "Có", "All/global/brand/market/client"],
            [4, "AddGlobalRuleForm", "Form", "Không", "Rule type · priority · config_json"],
            [5, "GlobalRulesTable", "Table", "Có", "Inline JSON edit · enable toggle · delete"],
            [6, "AuditLogTable", "Table", "Có", "Last 50: time/actor/action/entity/diff"],
        ],
        "rules": ["BR-EM-012"],
    },
    "SCR-EM-007": {
        "module_key": "EM",
        "api": "GET domains · POST register/verify · POST pause",
        "pre": "crm_email_mkt.view; deliverability cap for register/verify/pause",
        "post": "Domain DNS verified; warm-up tracked",
        "purpose": "Deliverability console EM-3 E-11 — SPF/DKIM/DMARC wizard",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "ClientDropdown", "Select", "Có", "fetchEmailClients scope"],
            [3, "EmailDomainOnboardingWizard", "Wizard", "Không", "Guided setup when client selected"],
            [4, "AddDomainForm", "Form", "Không", "Register domain — deliverability cap"],
            [5, "DomainsTable", "Table", "Có", "SPF/DKIM/DMARC · EmailDnsStatus · EmailWarmupMeter"],
            [6, "VerifyPauseButtons", "Button", "Không", "Row actions — pause confirms"],
            [7, "EmailEmptyState", "Alert", "Không", "No domains configured"],
        ],
        "rules": ["BR-EM-010", "BR-EM-001"],
    },
    "SCR-EM-008": {
        "module_key": "EM",
        "api": "GET reports summary/engagement/deliverability · POST export ClickHouse · schedules",
        "pre": "crm_email_mkt.view; export/schedules cần reports OR write cap",
        "post": "KPI/chart loaded; export job queued",
        "purpose": "Analytics center EM-3 E-12 — Grafana embed + scheduled PDF",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "FilterBar", "Toolbar", "Có", "Client · 7/28/90d · refresh · Export ClickHouse"],
            [3, "BiGrafanaCard", "Panel", "Có", "ClickHouse/BI flags + iframe or setup hint"],
            [4, "EmailKpiCardGrid", "KPI", "Có", "Sent/delivered/open/click/unsub/revenue"],
            [5, "EmailEngagementChart", "Chart", "Có", "Engagement series for period"],
            [6, "DeliverabilityScorecard", "Panel", "Có", "Bounce/complaint/paused domains"],
            [7, "ScheduledPdfPanel", "Form", "Không", "Weekly schedule + Run now — export cap"],
        ],
        "rules": ["BR-EM-013", "BR-EM-008"],
    },
    "SCR-EM-009": {
        "module_key": "EM",
        "api": "GET/POST/PATCH segments · POST compute",
        "pre": "crm_email_mkt.view; write for SegmentBuilder mutations",
        "post": "Segment saved; member count computed",
        "purpose": "Segment builder EM-8b E-07 — RFM/behavior definition",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "ClientDropdown", "Select", "Có", "Client scope"],
            [3, "SegmentBuilder", "Panel", "Có", "List/select/create/save/compute/duplicate"],
            [4, "ToastNotifications", "Toast", "Không", "Success on create/save/compute"],
        ],
        "rules": ["BR-EM-004"],
    },
    "SCR-EM-010": {
        "module_key": "EM",
        "api": "GET suppression · POST addEmailSuppression",
        "pre": "crm_email_mkt.view; add cần compliance OR write",
        "post": "Suppression entry added globally per workspace",
        "purpose": "Suppression master EM-1 E-06 — global unsub/bounce list",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "FilterBar", "Toolbar", "Không", "Client UUID + email search"],
            [3, "AddSuppressionForm", "Form", "Không", "Email + reason select — compliance cap"],
            [4, "SuppressionTable", "Table", "Có", "Email/client/reason/scope/created"],
        ],
        "rules": ["BR-EM-009"],
    },
    "SCR-EM-011": {
        "module_key": "EM",
        "api": "GET consent log · POST recordEmailConsent",
        "pre": "crm_email_mkt.view; record cần compliance cap",
        "post": "Append-only consent audit entry",
        "purpose": "Consent registry EM-1 E-05 — GDPR audit trail",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "RecordConsentForm", "Form", "Không", "Email · status opted_in/out/pending_confirm"],
            [3, "ConsentAuditTable", "Table", "Có", "Time/email/topic/status/source append-only"],
        ],
        "rules": ["BR-EM-002"],
    },
    "SCR-EM-012": {
        "module_key": "EM",
        "api": "GET email clients · POST createEmailWorkspace",
        "pre": "crm_email_mkt.view; create workspace cần settings cap",
        "post": "Workspace created; link to SCR-EM-021",
        "purpose": "Email client list EM-1 E-02 — workspace per client",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "SearchBar", "Input", "Không", "Search code/name"],
            [3, "ClientsTable", "Table", "Có", "Name/code · workspace ESP · contact count"],
            [4, "MoWorkspaceButton", "Link", "Có", "→ SCR-EM-021 when workspace exists"],
            [5, "TaoWorkspaceButton", "Button", "Không", "Create workspace — settings cap"],
        ],
        "rules": ["BR-EM-001"],
    },
    "SCR-EM-013": {
        "module_key": "EM",
        "api": "GET gate-a status/readiness · GET signoff template",
        "pre": "canViewEmailGateA — emailModuleEnabled + gate flag + settings/view",
        "post": "Readiness report refreshed; sign-off JSON downloaded",
        "purpose": "Gate A prod pilot EM-5 — soak + staged PTT_EMAIL_ENABLED",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "SignoffTemplateButton", "Button", "Có", "Download JSON sign-off"],
            [3, "ReadinessPanel", "Panel", "Có", "Ready/not-ready + notes"],
            [4, "StagedFlagsTable", "Table", "Có", "Env keys ON/OFF per step"],
            [5, "SoakEvidencePanel", "Panel", "Có", "Required days · samples · failures"],
            [6, "QaHandoffChecklist", "Checklist", "Có", "§13 items status"],
            [7, "OpsRoutesPanel", "Nav", "Có", "Staff /email/* route links"],
        ],
        "rules": ["BR-SYS-009", "BR-EM-001"],
    },
    "SCR-EM-014": {
        "module_key": "EM",
        "api": "POST publicEmailConfirm(token) — no auth",
        "pre": "Valid double opt-in token in URL",
        "post": "Subscriber confirmed; consent opted_in",
        "purpose": "Public double opt-in confirm page — token scoped",
        "app": "ops-web public (no staff auth)",
        "ui": [
            [1, "PublicLayout", "Layout", "Có", "Centered max-width 480px"],
            [2, "LoadingState", "Alert", "Có", "Đang xác nhận…"],
            [3, "SuccessView", "Panel", "Có", "Xác nhận thành công + email"],
            [4, "ErrorBanner", "Alert", "Không", "Invalid/expired token"],
        ],
        "rules": ["BR-EM-002"],
    },
    "SCR-EM-015": {
        "module_key": "EM",
        "api": "GET/POST public preferences(token)",
        "pre": "Valid preference center token",
        "post": "Marketing topic preference updated",
        "purpose": "Public preference center EM-UC-014 — marketing opt in/out",
        "app": "ops-web public (no staff auth)",
        "ui": [
            [1, "PreferencesHeader", "Header", "Có", "Client name + subscriber email"],
            [2, "MarketingCheckbox", "Checkbox", "Có", "Toggle marketing opted_in"],
            [3, "SaveButton", "Button", "Có", "Persist preference"],
            [4, "UnsubscribeLink", "Link", "Có", "→ SCR-EM-016"],
            [5, "SavedConfirmation", "Badge", "Không", "Đã cập nhật tùy chọn"],
        ],
        "rules": ["BR-EM-014"],
    },
    "SCR-EM-016": {
        "module_key": "EM",
        "api": "POST publicEmailUnsubscribe(token)",
        "pre": "Valid one-click unsub token",
        "post": "Global suppression honored",
        "purpose": "Public one-click unsubscribe page",
        "app": "ops-web public (no staff auth)",
        "ui": [
            [1, "PublicLayout", "Layout", "Có", "Centered max-width 480px"],
            [2, "LoadingState", "Alert", "Có", "Đang xử lý…"],
            [3, "SuccessView", "Panel", "Có", "Hủy đăng ký thành công + email"],
            [4, "ErrorBanner", "Alert", "Không", "Invalid token"],
        ],
        "rules": ["BR-EM-009"],
    },
    "SCR-EM-017": {
        "module_key": "EM",
        "api": "GET campaign · POST preflight · POST schedule",
        "pre": "view cap; submit draft=write; schedule approved=approve cap",
        "post": "Preflight pass/fail; schedule saved if approved",
        "purpose": "Campaign detail EM-10 E-09 — preflight, experiment, schedule send",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "BreadcrumbCard", "Nav", "Có", "← campaigns list"],
            [3, "CampaignSummaryCard", "Panel", "Có", "Name/client/status/segment/template/audience"],
            [4, "ActionButtons", "Toolbar", "Có", "Preflight · Review submit · Open template"],
            [5, "CampaignExperimentPanel", "Panel", "Không", "A/B experiment config"],
            [6, "ScheduleSendCard", "Form", "Không", "datetime-local — approved + send enabled"],
            [7, "PreflightResultsCard", "Panel", "Có", "Pass/fail + PreflightChecklist"],
        ],
        "rules": ["BR-EM-006", "BR-EM-007"],
    },
    "SCR-EM-018": {
        "module_key": "EM",
        "api": "GET campaign · POST preflight/submit/approve",
        "pre": "submit draft=write; approve pending=approve; send platform on",
        "post": "Dual approval recorded; schedule optional on approve",
        "purpose": "Campaign review EM-10 E-09c — staff compliance approve flow",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "ReviewHeader", "Header", "Có", "Name/client/audience/status"],
            [3, "EmailApprovalTimeline", "Timeline", "Có", "Visual workflow by status"],
            [4, "PreflightChecklistCard", "Panel", "Có", "Auto-run on load pass/fail"],
            [5, "SubmitForApprovalButton", "Button", "Không", "Draft + write + preflight pass"],
            [6, "StaffApproveCard", "Panel", "Không", "Optional schedule · Approve & send"],
        ],
        "rules": ["BR-EM-007"],
    },
    "SCR-EM-019": {
        "module_key": "EM",
        "api": "GET/PATCH journey · POST activate",
        "pre": "view cap; canvas edit draft/paused + write",
        "post": "Graph saved; journey activated",
        "purpose": "Journey canvas editor EM-12 E-10b — visual automation graph",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "JourneyHeader", "Header", "Có", "Name/client/status/enrolled"],
            [3, "JourneyInfoCard", "Panel", "Có", "Entry segment · Activate button"],
            [4, "JourneyCanvasEditor", "Canvas", "Có", "Nodes/edges graph — patch on save"],
            [5, "EmailStatusBadge", "Badge", "Có", "Journey status chip"],
        ],
        "rules": ["BR-EM-011"],
    },
    "SCR-EM-020": {
        "module_key": "EM",
        "api": "GET/PATCH template · POST preflight",
        "pre": "crm_email_mkt.view; save/preflight cần write",
        "post": "Template body saved; preflight pass/fail",
        "purpose": "Template studio EM-8b E-08b — blocks/HTML/text + dual preview",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "ToolbarCard", "Toolbar", "Có", "Save · Preflight · client/version meta"],
            [3, "EditorTabNav", "Tabs", "Có", "Blocks · HTML · Text"],
            [4, "TemplateBlockLibrary", "Panel", "Không", "Insert HTML blocks"],
            [5, "HtmlTextEditors", "Textarea", "Có", "Raw HTML + plain text body"],
            [6, "DualPreviewPanel", "Preview", "Có", "Desktop + mobile 320px iframe srcDoc"],
            [7, "PreflightResultsCard", "Panel", "Có", "Pass/fail + PreflightChecklist"],
        ],
        "rules": ["BR-EM-005"],
    },
    "SCR-EM-021": {
        "module_key": "EM",
        "api": "GET workspaces · PATCH patchEmailWorkspace",
        "pre": "crm_email_mkt.view; save settings cần crm_email_mkt.settings",
        "post": "Workspace settings persisted; KPI tiles refresh",
        "purpose": "Email client workspace detail — Overview KPIs + Settings tab",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "BackLink", "Link", "Có", "← /email/clients"],
            [3, "EmailClientWorkspaceTabs", "Tabs", "Có", "Overview · Settings (?tab=settings)"],
            [4, "EmailKpiCardGrid", "KPI", "Có", "Contacts · Subscribers · Suppressed · Daily cap"],
            [5, "SettingsForm", "Form", "Có", "From/reply · ESP SendGrid/Mailgun · daily cap · Save"],
            [6, "NoWorkspaceFallback", "Alert", "Không", "Prompt create from clients list"],
        ],
        "rules": ["BR-EM-001"],
    },
}
