"""Manual BA use-case details — Meta Enterprise Ops (META-UC-001 … META-UC-014)."""
from __future__ import annotations

from rnosai_ba_detail_helpers import uc_detail

META_USE_CASE_DETAILS: dict[str, dict] = {
    "META-UC-001": uc_detail(
        "META-UC-001",
        "Kết nối ad account & sync insights",
        screens="SCR-META-001, SCR-AGENCY-001",
        actor="Tracking/Tech / Media Buyer",
        actor_secondary="System (sync worker)",
        goal="Map Meta ad account → client và sync T-1 insights",
        trigger="Onboard Meta service hoặc manual sync",
        pre="Meta Business Manager access; system user token configured",
        post="Insights table populated; last_sync timestamp; hub status green/yellow/red",
        priority="P0",
        wave="Wave R1",
        api="POST /clients/:id/channel-accounts · POST sync/meta-insights · GET /meta/insights",
        main=[
            [1, "Map ad account → client SVC-UC-008 tab channels"],
            [2, "OAuth/system user token lưu vault; refresh before expiry"],
            [3, "Worker sync campaigns/adsets/ads T-1 insights"],
            [4, "Hub /meta/facebook-ads hiển thị spend, impressions, clicks"],
            [5, "Sync status indicator green/yellow/red trên hub"],
        ],
        alt=[
            ["E1", "Token expired → alert AM; re-auth OAuth flow"],
            ["E2", "Partial sync fail → retry failed ad accounts slice"],
        ],
        io_in="client_id, ad_account_id, oauth tokens, date_range",
        io_out="insights rows[], sync_state, hub health badge",
        rules=["BR-META-001", "BR-SVC-008"],
    ),
    "META-UC-002": uc_detail(
        "META-UC-002",
        "Hub map campaign ↔ CRM",
        screens="SCR-META-001, SCR-AGENCY-001",
        actor="Media Buyer",
        goal="Map external Meta campaign id ↔ CRM client/project/deal for CPL",
        trigger="Unmapped campaigns listed on hub yellow banner",
        pre="Campaigns synced META-UC-001",
        post="campaign_id → client_id relation stored; CPL enabled",
        priority="P0",
        wave="Wave R1",
        api="POST /hub-campaign-maps · HubCampaignMapsPanel · bulk CSV map",
        main=[
            [1, "Buyer mở /meta/facebook-ads hoặc client tab campaigns"],
            [2, "Filter unmapped campaigns highlighted yellow"],
            [3, "Select CRM client/project/deal line + target CPL"],
            [4, "Save mapping → hub_campaign_map stored"],
            [5, "Optional bulk map CSV upload"],
        ],
        alt=[
            ["E1", "Campaign archived on Meta → soft-unmap audit"],
            ["E2", "Duplicate map → 409 conflict"],
        ],
        io_in="external_campaign_id, client_id, contract_id, target_cpl",
        io_out="hub_campaign_map row, mapping audit",
        rules=["BR-META-002", "BR-SYS-002"],
    ),
    "META-UC-003": uc_detail(
        "META-UC-003",
        "Xem CPL/ROAS trên hub",
        screens="SCR-META-001",
        actor="Media Buyer / AM",
        goal="Hub aggregate spend + CRM leads + revenue → CPL/ROAS",
        trigger="User mở /meta/facebook-ads",
        pre="Performance synced; mappings exist for client rollup",
        post="KPI matches closed-loop SYS-UC-002",
        priority="P0",
        wave="Wave R1",
        trace="SYS-002",
        api="GET /meta/facebook-ads/hub · attribution API · export CSV",
        main=[
            [1, "Hub aggregate spend Meta + leads CRM + revenue Won"],
            [2, "Display CPL, ROAS, trend 7/30 days tiles"],
            [3, "Filter client, campaign, date range"],
            [4, "Drill campaign row → daily breakdown"],
            [5, "Export CSV snapshot for client report"],
        ],
        alt=[
            ["E1", "Unmapped spend → yellow warning; exclude from client rollup"],
            ["E2", "No leads period → CPL N/A with note"],
        ],
        io_in="client_id, date_from, date_to, campaign filters",
        io_out="CPL, ROAS, trend charts, CSV export",
        rules=["BR-META-003", "BR-SYS-002"],
    ),
    "META-UC-004": uc_detail(
        "META-UC-004",
        "Webhook lead Meta → CRM",
        screens="SCR-CRM-001, SCR-CRM-015",
        actor="System",
        actor_secondary="CSKH (consumer)",
        goal="Meta Leadgen webhook tạo lead CRM ≤60s SLA",
        trigger="Meta POST leadgen webhook",
        pre="Webhook secret + form field map configured",
        post="Lead in CRM with source Meta; owner assigned; score triggered",
        priority="P0",
        wave="Wave R1",
        trace="PLAT-004, TC-PROJ-08",
        api="POST /webhooks/meta · lead ingest worker · facebook_webhook.parser",
        main=[
            [1, "Meta POST leadgen payload → PLAT-UC-004 endpoint"],
            [2, "Verify X-Hub-Signature-256 signature"],
            [3, "Parse leadgen → normalize VN phone, full_name fields"],
            [4, "Dedup phone → create/update CRM lead (CRM-UC-001)"],
            [5, "Map campaign/adset attribution meta_json"],
            [6, "Auto-assign owner + return HTTP 200 OK to Meta"],
            [7, "Trigger AI-UC-001 score async"],
        ],
        alt=[
            ["E1", "Invalid signature → 401 + DevOps alert SYS-UC-008"],
            ["E2", "Missing phone → GDKD review queue CRM-UC-003"],
            ["E3", "RE project webhook → map project_id CRM-UC-010"],
        ],
        io_in="Meta leadgen webhook JSON, signature headers",
        io_out="lead_id, ingest audit, assignment result",
        rules=["BR-META-004", "BR-PLAT-004", "BR-CRM-001"],
    ),
    "META-UC-005": uc_detail(
        "META-UC-005",
        "CAPI event gửi & dedup",
        screens="SCR-META-003",
        actor="System / Tracking-Tech",
        goal="Send Conversions API events with PII hash + event_id dedup",
        trigger="CRM stage Won / qualified event hook",
        pre="Pixel + CAPI configured; domain verified",
        post="Event visible Meta Events Manager; dedup with pixel",
        priority="P0",
        wave="Wave R1",
        api="CAPI service · CRM event hook · Meta Graph API",
        main=[
            [1, "CRM event hook on qualified/Won stage change"],
            [2, "CAPI payload builder hash PII per Meta spec"],
            [3, "event_id = hash(lead_id + event_name + date) dedup"],
            [4, "Send Conversions API batch"],
            [5, "Log response; retry on 5xx with backoff"],
        ],
        alt=[
            ["E1", "Test mode staging → Events Manager test events"],
            ["E2", "Duplicate event_id → Meta dedup skip"],
        ],
        io_in="lead/customer PII hashed, event_name, event_time, custom_data",
        io_out="CAPI response, event_id, retry audit",
        rules=["BR-META-005", "BR-META-006"],
    ),
    "META-UC-006": uc_detail(
        "META-UC-006",
        "Tracking health & pixel test",
        screens="SCR-META-003",
        actor="Tracking/Tech",
        goal="Document tracking health pre-launch: pixel, CAPI, match rate",
        trigger="Pre-launch checklist or periodic audit",
        pre="Pixel installed on client site",
        post="Health score documented; fix checklist linked",
        priority="P0",
        wave="Wave R1",
        api="GET /meta/tracking/health · POST test event API",
        main=[
            [1, "Open /meta/tracking per client"],
            [2, "View pixel status, CAPI connection, domain verification"],
            [3, "Run pixel/CAPI test event button"],
            [4, "View match rate, recent event volume"],
            [5, "Fix checklist linked to Launch QA SVC-UC-005"],
        ],
        alt=[
            ["E1", "Test event fail → block launch gate until green"],
        ],
        io_in="client_id, pixel_id, test_event payload",
        io_out="health score, test result, checklist items",
        rules=["BR-META-006", "BR-SVC-005"],
    ),
    "META-UC-007": uc_detail(
        "META-UC-007",
        "Launch Ads wizard",
        screens="SCR-META-004, SCR-SVC-001, SCR-SVC-002",
        actor="Media Buyer",
        goal="Launch campaign qua wizard + governance queue",
        trigger="Buyer launch new Meta campaign",
        pre="Creative approved SVC-UC-006; Launch QA pass SVC-UC-005",
        post="Campaign live on Meta; Meta ids stored; hub mapped",
        priority="P0",
        wave="Wave R1",
        trace="SYS-003",
        api="/meta/ads-ops wizard · Campaign Write queue · Meta Marketing API create",
        main=[
            [1, "Mở /meta/ads-ops launch wizard"],
            [2, "Chọn objective, budget, audience, creative from hub"],
            [3, "Launch QA gate SVC-UC-005 pass confirmation"],
            [4, "Submit → Campaign Write queue SVC-UC-007 pending approval"],
            [5, "On approve → Meta create API → store external ids"],
            [6, "Auto-suggest hub map META-UC-002"],
        ],
        alt=[
            ["E1", "QA fail → block submit with checklist items"],
            ["E2", "API error → job retry + notify buyer"],
        ],
        io_in="launch payload, creative_ids[], budget, schedule",
        io_out="external campaign/adset/ad ids, write job audit",
        rules=["BR-META-007", "BR-SYS-003", "BR-SVC-007"],
    ),
    "META-UC-008": uc_detail(
        "META-UC-008",
        "Edit campaign có governance",
        screens="SCR-META-004, SCR-SVC-002",
        actor="Media Buyer",
        goal="Edit budget/bid/status via approval queue — no API bypass",
        trigger="Buyer request campaign edit on live campaign",
        pre="Campaign exists on Meta; write queue configured",
        post="Edit audit trail; threshold rules enforced",
        priority="P0",
        wave="Wave R1",
        api="Campaign write edit jobs · Meta Marketing API update",
        main=[
            [1, "Buyer chọn Edit on hub campaign row → /meta/ads-ops"],
            [2, "Nhập thay đổi budget/bid/status"],
            [3, "Budget increase >X% → manager approval required"],
            [4, "Submit write queue job → approver review"],
            [5, "On approve → Meta API update + audit log"],
        ],
        alt=[
            ["E1", "Emergency edit → GDKD override with reason audit"],
            ["E2", "Reject edit → notify buyer with comment"],
        ],
        io_in="campaign_id, edit fields, reason, approver_id",
        io_out="write job status, Meta API response, audit",
        rules=["BR-META-008", "BR-SVC-007"],
    ),
    "META-UC-009": uc_detail(
        "META-UC-009",
        "Anomaly detection & alert",
        screens="SCR-META-002, SCR-META-001, SCR-AI-001",
        actor="System / Media Buyer",
        actor_secondary="GDKD (digest via AI-UC-019)",
        goal="Detect spend spike, CPL drift, zero delivery → alert",
        trigger="Daily metrics scan vs baseline",
        pre="Baseline metrics ≥7d; mapped campaigns",
        post="Slack/email alert + hub banner; optional AI digest",
        priority="P1",
        wave="Wave R2",
        trace="AI-UC-019",
        api="anomaly rules engine · alert module · hub banner API",
        main=[
            [1, "Rules engine scan daily_performance Meta channel"],
            [2, "Detect: spend spike, CPL >2σ, zero delivery 24h"],
            [3, "Create alert record + hub banner on /meta/facebook-ads"],
            [4, "Notify Media Buyer + AM Slack/email"],
            [5, "Rollup optional vào AI-UC-019 anomaly digest"],
        ],
        alt=[
            ["E1", "False positive → dismiss + tune threshold BR-META-009"],
        ],
        io_in="metrics[], baselines, alert rules config",
        io_out="alert_ids[], notifications, banner state",
        rules=["BR-META-009", "BR-AI-019"],
    ),
    "META-UC-010": uc_detail(
        "META-UC-010",
        "Intelligence forecast",
        screens="SCR-META-002",
        actor="Media Buyer / AM / GDKD",
        goal="Forecast spend/leads based on historical Meta performance",
        trigger="User mở /meta/intelligence forecast tab",
        pre="Historical data ≥30 days synced",
        post="Forecast chart rendered; scenario budget slider",
        priority="P1",
        wave="Wave R2",
        api="GET /meta/intelligence/forecast · forecast API",
        main=[
            [1, "Mở /meta/intelligence → Forecast tab"],
            [2, "Select client/campaign scope + horizon 7/30/90d"],
            [3, "Render spend/leads forecast curve from historical"],
            [4, "Scenario budget slider what-if CPL impact"],
            [5, "Export forecast CSV for planning"],
        ],
        alt=[
            ["E1", "Data <30d → partial forecast warning"],
        ],
        io_in="client_id, campaign_ids[], horizon_days, budget_scenario",
        io_out="forecast series[], scenario comparison CSV",
        rules=["BR-META-010"],
    ),
    "META-UC-011": uc_detail(
        "META-UC-011",
        "Breakdown insights (platform/placement)",
        screens="SCR-META-002",
        actor="Media Buyer",
        goal="View Meta insights breakdown by platform, placement, demographics",
        trigger="Buyer mở breakdown tab on intelligence",
        pre="Breakdown insights synced v8 DDL",
        post="Breakdown table visible; export CSV",
        priority="P1",
        wave="Wave R2",
        api="GET /meta/insights/breakdown · breakdown insights API",
        main=[
            [1, "Mở /meta/intelligence → Breakdown tab"],
            [2, "Select breakdown dimensions: platform, placement, age, gender"],
            [3, "Render table + chart compare periods"],
            [4, "Identify underperforming placements"],
            [5, "Export CSV breakdown snapshot"],
        ],
        alt=[
            ["E1", "API rate limit → cached snapshot with timestamp"],
        ],
        io_in="campaign_id, breakdown_dims[], date_range",
        io_out="breakdown table, chart spec, CSV",
        rules=["BR-META-011"],
    ),
    "META-UC-012": uc_detail(
        "META-UC-012",
        "Pause domain/client spend emergency",
        screens="SCR-META-004, SCR-META-001",
        actor="Admin / GDKD / Media Buyer",
        goal="Emergency pause all active Meta campaigns for client/domain",
        trigger="Fraud, client request, billing dispute, compliance",
        pre="Emergency cap authorized role",
        post="No new spend; campaigns PAUSED on Meta; audit who triggered",
        priority="P0",
        wave="Wave R1",
        api="POST emergency pause API · Meta batch pause · runbook link",
        main=[
            [1, "GDKD/Admin toggle Emergency pause on client/domain"],
            [2, "Confirm modal reason bắt buộc"],
            [3, "Queue pause all active campaigns via Meta API batch"],
            [4, "Notify AM + client (portal notification optional)"],
            [5, "Audit log: who, when, reason, campaigns affected"],
        ],
        alt=[
            ["E1", "Partial API fail → retry failed campaigns list"],
            ["E2", "Resume requires separate approval workflow"],
        ],
        io_in="client_id or domain, pause_reason, actor_id",
        io_out="paused campaign ids[], audit record, notifications",
        rules=["BR-META-012"],
    ),
    "META-UC-013": uc_detail(
        "META-UC-013",
        "Weekly client PDF report",
        screens="SCR-PORTAL-003, SCR-META-001",
        actor="AM / System",
        goal="Scheduler weekly Meta KPI PDF → portal/email",
        trigger="Week closed cron RPT-M3",
        pre="Reporting period closed; portal module Meta enabled",
        post="PDF on portal; client notified SYS-UC-005",
        priority="P1",
        wave="Wave R2",
        trace="SYS-005",
        api="report worker RPT-M3 · portal download · email delivery",
        main=[
            [1, "Scheduler Sunday night aggregate Meta KPI week"],
            [2, "Generate PDF template client-safe metrics"],
            [3, "Upload artifact to portal /meta or /settings exports"],
            [4, "Email client viewer optional"],
            [5, "AM review copy before send if manual gate enabled"],
        ],
        alt=[
            ["E1", "Unmapped spend footnote in PDF"],
        ],
        io_in="client_id, week period, KPI aggregates",
        io_out="PDF URL, delivery audit, portal notification",
        rules=["BR-META-013", "BR-SYS-005", "BR-PORTAL-003"],
    ),
    "META-UC-014": uc_detail(
        "META-UC-014",
        "Horizon migration signoff",
        screens="SCR-META-001, SCR-ADMIN-002",
        actor="Tech Lead / Admin / Media Buyer",
        goal="Meta API version upgrade checklist + regression sign-off",
        trigger="Meta deprecation deadline approaching",
        pre="Migration plan approved; staging regression env ready",
        post="Signoff doc recorded; prod API version updated",
        priority="P1",
        wave="Wave R3",
        api="API version config · migration runbook · staging E2E gates",
        main=[
            [1, "Review Meta API changelog + deprecation timeline"],
            [2, "Run regression test suite on staging new API version"],
            [3, "Validate sync, webhook, CAPI, ads-ops write paths"],
            [4, "Tech Lead + Buyer sign-off checklist document"],
            [5, "Cutover prod API version config + monitor 48h hypercare"],
        ],
        alt=[
            ["E1", "Regression fail → rollback version pin"],
            ["E2", "Partial feature deprecated → document manual workaround"],
        ],
        io_in="target_api_version, regression results, signoff approvers",
        io_out="signoff record, config change audit, hypercare log",
        rules=["BR-META-014"],
    ),
}
