"""Manual BA use-case details — Platform Auth/Webhooks (PLAT-UC-001 … PLAT-UC-010)."""
from __future__ import annotations

from rnosai_ba_detail_helpers import uc_detail

PLAT_USE_CASE_DETAILS: dict[str, dict] = {
    "PLAT-UC-001": uc_detail(
        "PLAT-UC-001",
        "Staff JWT login & refresh",
        screens="SCR-AUTH-001",
        actor="Staff",
        goal="Issue JWT access + refresh; session scoped staff id + caps",
        trigger="Login ops-web rs.pttads.vn",
        pre="Staff account seeded PLAT-UC-009; account active",
        post="Session valid; refresh before expiry BR-PLAT-001",
        priority="P0",
        wave="Wave R1",
        trace="TC-AUTH-01",
        api="POST /auth/login · POST /auth/refresh · ops-web auth middleware",
        main=[
            [1, "POST /auth/login email + password"],
            [2, "Validate bcrypt hash; issue access JWT + refresh token"],
            [3, "ops-web stores token; Authorization header"],
            [4, "Refresh before expiry via /auth/refresh"],
            [5, "Redirect dashboard theo caps array"],
        ],
        alt=[
            ["E1", "Invalid credentials → 401 rate limit lockout"],
            ["E2", "Account disabled → 403 contact admin"],
        ],
        io_in="email, password",
        io_out="access JWT, refresh token, caps[], staff_id",
        rules=["BR-PLAT-001", "BR-PLAT-002"],
    ),
    "PLAT-UC-002": uc_detail(
        "PLAT-UC-002",
        "RBAC cap enforcement",
        screens="SCR-AUTH-001",
        actor="All staff",
        goal="Least privilege enforced server-side 403 unauthorized",
        trigger="Every API request và UI nav render",
        pre="JWT caps assigned PLAT-UC-009",
        post="403 on unauthorized route; UI hides nav without cap",
        priority="P0",
        wave="Wave R1",
        api="Nest guards per route cap · ops-web nav filter",
        main=[
            [1, "API route declares required cap e.g. crm.leads.read"],
            [2, "Guard checks JWT caps vs route deny by default"],
            [3, "UI hides nav items without cap"],
            [4, "403 on unauthorized API not UI-only bypass"],
        ],
        alt=[
            ["E1", "Missing cap in token → re-login after role change"],
        ],
        io_in="JWT caps[], route required cap",
        io_out="200 authorized or 403 forbidden",
        rules=["BR-PLAT-002"],
    ),
    "PLAT-UC-003": uc_detail(
        "PLAT-UC-003",
        "Portal JWT login",
        screens="SCR-PORTAL-002",
        actor="Client Viewer",
        actor_secondary="Client Approver",
        goal="Portal JWT scoped client_id + portal_role",
        trigger="Login portal.pttads.vn",
        pre="Portal account active PORTAL-UC-001 provisioned",
        post="All portal APIs filter client_id SYS-UC-011",
        priority="P0",
        wave="Wave R1",
        trace="PORTAL-001",
        api="POST /portal/auth/login · separate issuer/audience",
        main=[
            [1, "Portal login separate issuer/audience from staff"],
            [2, "JWT contains client_id, portal_role viewer|approver"],
            [3, "All portal APIs filter by client_id middleware"],
            [4, "No cross-tenant access TC-ISO-01"],
        ],
        alt=[
            ["E1", "Wrong tenant probe → 403 empty result"],
        ],
        io_in="email, password",
        io_out="portal JWT, client_id scope, role",
        rules=["BR-PLAT-003", "BR-PORTAL-001", "BR-SYS-011"],
    ),
    "PLAT-UC-004": uc_detail(
        "PLAT-UC-004",
        "Webhook Meta ingest",
        screens="SCR-AGENCY-004",
        actor="System",
        goal="Verify signature; queue lead → CRM idempotent",
        trigger="Meta POST leadgen / verification",
        pre="Webhook secret + tenant routing configured",
        post="Event persisted; downstream job queued META-UC-004",
        priority="P0",
        wave="Wave R1",
        trace="META-004, TC-WH-META-01",
        api="POST /webhooks/meta · X-Hub-Signature-256 verify",
        main=[
            [1, "Verify X-Hub-Signature-256"],
            [2, "Handle challenge GET subscription"],
            [3, "Queue lead payload → worker → CRM"],
            [4, "Return 200 within timeout <5s"],
            [5, "Idempotent via event id dedup"],
        ],
        alt=[
            ["E1", "Signature fail → 401 + alert SYS-UC-008"],
            ["E2", "Down sustained → incident P1 runbook"],
        ],
        io_in="Meta webhook payload + headers",
        io_out="event_id, job_id, ingest status",
        rules=["BR-PLAT-004", "BR-SYS-008", "BR-SVC-009"],
    ),
    "PLAT-UC-005": uc_detail(
        "PLAT-UC-005",
        "Webhook Zalo/Google ingest",
        screens="SCR-AGENCY-004",
        actor="System",
        goal="Channel signature verify → normalize lead → CRM",
        trigger="Zalo OA hoặc Google Ads lead webhook POST",
        pre="Endpoint configured per tenant",
        post="Payload normalized; CRM ingest CRM-UC-001",
        priority="P0",
        wave="Wave R1",
        trace="ZALO-011",
        api="Zalo OA webhook · Google Ads lead form webhook",
        main=[
            [1, "Channel-specific signature verify"],
            [2, "Normalize lead fields to CRM schema"],
            [3, "Dedup phone+client BR-ZALO-013 if Zalo"],
            [4, "Persist + queue CRM ingest job"],
            [5, "Monitor on /agency/ingest"],
        ],
        alt=[
            ["E1", "Unknown tenant routing → 404 + log"],
        ],
        io_in="channel payload, signature headers",
        io_out="normalized lead, crm_job_id",
        rules=["BR-PLAT-005", "BR-ZALO-011", "BR-CRM-001"],
    ),
    "PLAT-UC-006": uc_detail(
        "PLAT-UC-006",
        "Webhook Email ESP ingest",
        screens="SCR-AGENCY-004",
        actor="System",
        goal="Parse ESP events → update contact + campaign stats",
        trigger="ESP POST delivered/bounce/open/click/complaint",
        pre="ESP webhook configured per workspace",
        post="Bounce triggers suppression EM-UC-009",
        priority="P0",
        wave="Wave R1",
        trace="EM-008",
        api="ESP webhook endpoints · email event worker",
        main=[
            [1, "Parse ESP event type delivered/open/click/bounce/spam"],
            [2, "Update contact engagement fields"],
            [3, "Update campaign stats EM-UC-008 real-time"],
            [4, "Bounce/complaint → suppression EM-UC-009"],
        ],
        alt=[
            ["E1", "Duplicate event id → idempotent skip"],
        ],
        io_in="ESP event JSON, signature",
        io_out="contact update, campaign stat delta",
        rules=["BR-PLAT-006", "BR-EM-008", "BR-EM-009"],
    ),
    "PLAT-UC-007": uc_detail(
        "PLAT-UC-007",
        "Job queue worker process",
        screens="SCR-AGENCY-005",
        actor="System",
        goal="At-least-once job processing với retry + dead letter",
        trigger="Job enqueued sync/send/report/segment",
        pre="BullMQ/Redis queue configured",
        post="Jobs processed; metrics queue depth + failure rate",
        priority="P0",
        wave="Wave R1",
        api="Worker service · Redis · /agency/jobs monitor UI",
        main=[
            [1, "Queue types: sync, send, report, segment compute"],
            [2, "Worker consume with retry backoff"],
            [3, "Dead letter on max retries"],
            [4, "Metrics visible SCR-AGENCY-005 dashboard"],
        ],
        alt=[
            ["E1", "Poison message → DLQ + alert DevOps"],
        ],
        io_in="job payload, job type, tenant context",
        io_out="job status, retry count, DLQ ref",
        rules=["BR-PLAT-007"],
    ),
    "PLAT-UC-008": uc_detail(
        "PLAT-UC-008",
        "Temporal approval workflow",
        screens="SCR-SVC-002",
        actor="System",
        goal="Durable human-in-loop approval với timeout escalate",
        trigger="Campaign write / email send / cross-module approval",
        pre="Temporal connected namespace configured",
        post="Workflow history durable; side effect on complete",
        priority="P1",
        wave="Wave R2",
        api="Temporal namespace · signals staff/client · SVC-UC-007 EM-UC-007",
        main=[
            [1, "Start workflow on submit approval-required item"],
            [2, "Wait human signals staff then client"],
            [3, "Timeout → escalate notification AM"],
            [4, "Complete → execute side effect Meta API ESP send"],
        ],
        alt=[
            ["E1", "Reject signal → terminate workflow return draft"],
        ],
        io_in="workflow type, item ref, approver list",
        io_out="workflow id, final decision, side effect result",
        rules=["BR-PLAT-008", "BR-SYS-004", "BR-SVC-007"],
    ),
    "PLAT-UC-009": uc_detail(
        "PLAT-UC-009",
        "Seed staff permissions",
        screens="SCR-AUTH-001",
        actor="Super Admin",
        actor_secondary="DevOps",
        goal="Staff user với role template caps for fresh deploy/hire",
        trigger="Fresh deploy hoặc new hire onboarding",
        pre="Seed script or admin UI access",
        post="Staff access permitted modules only PLAT-UC-002",
        priority="P0",
        wave="Wave R1",
        api="Seed scripts · admin user API · accounts.json handover",
        main=[
            [1, "Run seed script or admin UI create user"],
            [2, "Assign role template caps matrix"],
            [3, "User first login optional force password change"],
            [4, "Verify login TC-AUTH-01 smoke"],
        ],
        alt=[
            ["E1", "Duplicate email → reject create"],
        ],
        io_in="email, role template, cap overrides",
        io_out="staff user id, caps[], audit create",
        rules=["BR-PLAT-009", "BR-PLAT-002"],
    ),
    "PLAT-UC-010": uc_detail(
        "PLAT-UC-010",
        "Health check & soak evidence",
        screens="SCR-AGENCY-004",
        actor="DevOps",
        actor_secondary="QA",
        goal="Gate PASS artifacts liveness/readiness + soak scripts",
        trigger="Staging/prod deploy or nghiệm thu gate",
        pre="Services deployed; gate scripts in repo",
        post="Evidence stored CI/ops folder SYS-UC-009",
        priority="P1",
        wave="Wave R2",
        api="GET /health DB Redis Temporal · email_p1_gate.sh module gates",
        main=[
            [1, "GET /health liveness/readiness DB Redis Temporal"],
            [2, "Run soak scripts email_p1_gate.sh module gates"],
            [3, "Collect evidence nghiệm thu handover §6"],
            [4, "Attach to change log gate PASS"],
        ],
        alt=[
            ["E1", "Health fail → block cutover SYS-UC-009 rollback"],
        ],
        io_in="env target, gate script list",
        io_out="health status JSON, gate PASS artifacts",
        rules=["BR-PLAT-010", "BR-SYS-009"],
    ),
}
