"""Deep SCR UI/API overrides — CRM module."""

CRM_SCR_OVERRIDES: dict[str, dict] = {
    "SCR-CRM-008": {
        "api": "GET /api/v1/crm/customers",
        "pre": "cap crm_board_customers.view",
        "post": "Danh sách khách hàng theo filter (limit 200)",
        "purpose": "Danh sách khách hàng post-convert — search, lọc, drill-down chi tiết",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar CRM"],
            [2, "SearchForm", "Form", "Không", "Ô q + nút Lọc (submit)"],
            [3, "CustomerCount", "Badge", "Có", "Tổng số bản ghi trả về"],
            [4, "CustomersTable", "Table", "Có", "ID/Tên/SĐT/Email/Công ty/Nguồn"],
            [5, "RowDetailLink", "Link", "Có", "Click row → /crm/customers/[id]"],
            [6, "EmptyState", "Alert", "Không", "Không có khách hàng"],
        ],
        "rules": ["BR-CRM-007"],
    },
    "SCR-CRM-009": {
        "api": "GET/PATCH /api/v1/crm/customers/:id · POST relations · POST issues",
        "pre": "cap crm_board_customers.view; edit cần edit cap",
        "post": "Profile/relations/issues/timeline cập nhật",
        "purpose": "Hồ sơ khách hàng: chỉnh sửa profile, quan hệ, issue, timeline RNOS-16",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "BackLink", "Link", "Có", "← Danh sách customers"],
            [3, "ProfileHeader", "Header", "Có", "Tên + stats tóm tắt"],
            [4, "EditProfileForm", "Form", "Có", "name/phone/email/company/notes — Save"],
            [5, "RelationsPanel", "Panel", "Không", "List + add relation form"],
            [6, "IssuesPanel", "Panel", "Không", "List + add issue form"],
            [7, "CustomerTimelinePanel", "Timeline", "Có", "RNOS-16 enrich — cần crm_leads.assign"],
        ],
        "rules": ["BR-CRM-007", "BR-AI-008"],
    },
    "SCR-CRM-010": {
        "api": "Hub panels: campaign maps · contract approvals",
        "pre": "crm_agency.view OR crm_leads.assign",
        "post": "Filter client/campaign áp dụng cho panels",
        "purpose": "Hub agency: campaign map Meta + hợp đồng chờ duyệt",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "AgencyReadOnlyBadge", "Badge", "Không", "Hiện khi không có agency write"],
            [3, "HubTabBar", "Tabs", "Có", "Campaign map · HĐ chờ duyệt"],
            [4, "ClientCampaignFilters", "Filter", "Không", "?client_id= · ?campaign_id="],
            [5, "HubCampaignMapsPanel", "Panel", "Có", "Map campaign ↔ CRM client"],
            [6, "ContractApprovalsPanel", "Panel", "Có", "Pending contract approvals"],
        ],
        "rules": ["BR-CRM-003", "BR-CRM-011"],
    },
    "SCR-CRM-011": {
        "api": "GET kpi board/chart/trend · PATCH staff KPI · GET ai acceptance · downloadStaffKpiXlsx",
        "pre": "cap crm_kpi_records.view; grid edit cần edit",
        "post": "Tiles/chart/trend theo year/month; export Excel OK",
        "purpose": "KPI dashboard nhân sự — tiles, chart, trend, editable grid, AI acceptance",
        "ui": [
            [1, "DashboardShell", "Layout", "Có", "KPI layout wrapper"],
            [2, "PeriodFilters", "Filter", "Có", "Year/month + Export Excel"],
            [3, "KpiTileGrid", "KPI", "Có", "5 tiles executive"],
            [4, "KpiBarChart", "Chart", "Có", "Metric selector — bar link → staff/[id]"],
            [5, "KpiTrendPanel", "Chart", "Có", "6-month trend"],
            [6, "KpiAlertList", "List", "Không", "Alerts vượt ngưỡng"],
            [7, "KpiEditableGrid", "Grid", "Không", "Patch progress — edit cap"],
            [8, "AiAcceptanceTile", "Link", "Không", "→ /crm/ai/insights"],
        ],
        "rules": ["BR-CRM-013", "BR-CRM-014"],
    },
    "SCR-CRM-012": {
        "api": "GET/PATCH intake sessions · POST complete/reopen · POST AI summary",
        "pre": "Requires ?lead_id= or ?lifecycle_id=; crm_leads.view",
        "post": "Session saved/completed; BANT scored",
        "purpose": "Intake pre-sales BANT — session lifecycle + AI summary stub",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "BackLink", "Link", "Có", "← lead hoặc lifecycle parent"],
            [3, "SessionStats", "KPI", "Có", "Sessions count/status"],
            [4, "CreateSessionButtons", "Button", "Không", "phone / in_person — edit cap"],
            [5, "BantScoreGrid", "Form", "Có", "6 keys 0–5 · total /30"],
            [6, "DecisionSelect", "Select", "Có", "Go / Nurture / No-Go"],
            [7, "SessionActions", "Toolbar", "Có", "Save · Complete · AI summary · Reopen"],
        ],
        "rules": ["BR-CRM-005"],
    },
    "SCR-CRM-013": {
        "api": "GET sales summary/plans/pipeline/partners/trainings/market/reports · POST create*",
        "pre": "crm_sales_overview OR crm_sales_plans view; funnel tab cần crm_sales_funnel",
        "post": "Tab data reload; pipeline excludes chot/mat",
        "purpose": "Sales ops 6-tab: plans, funnel, partners, training, market, reports",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "SalesTabSwitcher", "Tabs", "Có", "6 tabs Plans/Funnel/Partners/Training/Market/Reports"],
            [3, "SummaryCounts", "KPI", "Có", "Header counts per tab"],
            [4, "SalesPipelineFunnelPanel", "Panel", "Có", "?deal_id= opens funnel; sort-by-score"],
            [5, "PlanListCreate", "List+Form", "Không", "Plans list + create form"],
            [6, "PartnerTrainingMarket", "List+Form", "Không", "CRUD lists per tab"],
            [7, "ReportsJsonPanel", "Panel", "Không", "Reports JSON + transactions"],
        ],
        "rules": ["BR-CRM-009"],
    },
    "SCR-CRM-014": {
        "api": "GET/POST proposals · POST generateProposal · DELETE proposal",
        "pre": "crm_board.view; create/generate/delete cần edit",
        "post": "Proposal created or AI-generated for customer",
        "purpose": "Proposal list + create + AI generate per customer",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "CustomerSelect", "Select", "Có", "?customer_id= prefill"],
            [3, "ProposalList", "Table", "Có", "id/slugs/amount per row"],
            [4, "CreateProposalForm", "Form", "Không", "service slugs comma-separated + notes"],
            [5, "AiGenerateButton", "Button", "Không", "generateProposal per row"],
            [6, "DeleteProposalButton", "Button", "Không", "delete — edit cap"],
        ],
        "rules": ["BR-CRM-006"],
    },
    "SCR-CRM-015": {
        "api": "GET /api/v1/crm/re-projects · POST create",
        "pre": "crm_re_projects.view OR crm_re_projects_products.view; create cần create cap",
        "post": "Project list filtered; new project type can_ho",
        "purpose": "Danh sách dự án BĐS — search, create, link detail",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "SearchForm", "Form", "Không", "Search submit"],
            [3, "ReProjectsList", "Table", "Có", "code/type/status/city + link detail"],
            [4, "CreateProjectForm", "Form", "Không", "name only — type defaults can_ho"],
            [5, "EmptyState", "Alert", "Không", "No projects"],
        ],
        "rules": ["BR-CRM-010"],
    },
    "SCR-CRM-016": {
        "api": "GET staff list/levels/competency · POST import · PATCH save levels/competency",
        "pre": "crm_staff_roster.view; import/save cần edit",
        "post": "Roster/levels/competency persisted",
        "purpose": "Staff roster 4-tab: roster, import JSON, levels, competency",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "StaffTabSwitcher", "Tabs", "Có", "Roster · Import · Levels · Competency"],
            [3, "RosterSearchTable", "Table", "Có", "Search + summary + staff links"],
            [4, "JsonImportTextarea", "Form", "Không", "JSON array import — edit only"],
            [5, "LevelsEditor", "JSON Editor", "Không", "Save levels"],
            [6, "CompetencyEditor", "JSON Editor", "Không", "Save competency matrix"],
        ],
        "rules": ["BR-CRM-013"],
    },
    "SCR-CRM-017": {
        "api": "GET/POST/PATCH tickets · POST messages · POST sentiment (ai-api)",
        "pre": "crm_board.view; create/edit/status/messages cần edit",
        "post": "Ticket updated; sentiment scored on create/reply",
        "purpose": "Ticket queue CSKH — filter, drawer detail, sentiment AI",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "TicketFilterBar", "Filter", "Có", "q/status/sentiment"],
            [3, "CreateTicketForm", "Form", "Không", "6 types · 5 statuses · 4 priorities"],
            [4, "TicketsTable", "Table", "Có", "SentimentChip per row"],
            [5, "TicketDetailDrawer", "Drawer", "Có", "Messages thread + reply + status select"],
            [6, "HealthDeepLinks", "Link", "Không", "→ customer/agency health"],
        ],
        "rules": ["BR-CRM-008"],
    },
    "SCR-CRM-018": {
        "api": "GET /api/v1/crm/orders",
        "pre": "cap crm_board.view",
        "post": "Read-only order list displayed",
        "purpose": "Danh sách đơn hàng SO — RNOS-25 / SVC handover step 9",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "OrdersTable", "Table", "Có", "Mã SO/KH/Ngày/Trạng thái/Giá trị VND"],
            [3, "LoadingErrorStates", "Alert", "Có", "Loading + error banner"],
            [4, "EmptyState", "Alert", "Không", "Không có đơn"],
        ],
        "rules": ["BR-SVC-004"],
    },
    "SCR-CRM-019": {
        "api": "GET /api/v1/crm/invoices",
        "pre": "cap crm_business_dashboard.view",
        "post": "Invoice list with optional overdue filter",
        "purpose": "Danh sách hóa đơn — overdue filter · AR aging link",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "OverdueCheckbox", "Filter", "Không", "?overdue=true reload"],
            [3, "InvoicesTable", "Table", "Có", "Số HĐ/KH/Due/Status/Amount/Paid"],
            [4, "ReadOnlyBanner", "Alert", "Có", "Read-only — ties SVC-UC-004"],
        ],
        "rules": ["BR-SVC-004"],
    },
    "SCR-CRM-020": {
        "api": "GET finance summary · GET AR aging · GET finance intelligence",
        "pre": "cap crm_business_dashboard.view",
        "post": "Tiles + lifecycle + AR theo year/month",
        "purpose": "Tài chính front-office — KPI tiles, intelligence, lifecycle, AR aging",
        "ui": [
            [1, "DashboardShell", "Layout", "Có", "Finance dashboard wrapper"],
            [2, "PeriodFilters", "Filter", "Có", "Year/month selectors"],
            [3, "KpiTileGrid", "KPI", "Có", "Summary finance tiles"],
            [4, "FinancialIntelligencePanel", "Panel", "Có", "AI/rule insights"],
            [5, "FinancialLifecycleTable", "Table", "Có", "Lifecycle by stage"],
            [6, "ArAgingPanel", "Panel", "Có", "AR aging buckets"],
            [7, "DisclaimerFooter", "Alert", "Có", "Not ERP/MISA — front-office only"],
        ],
        "rules": ["BR-CRM-014", "BR-CRM-011"],
    },
    "SCR-CRM-021": {
        "api": "GET/POST /api/v1/crm/marketing-plans",
        "pre": "crm_board.view; create cần edit",
        "post": "Plan list filtered; create navigates to detail",
        "purpose": "Danh sách marketing plan TMMT — search, create",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "SearchForm", "Form", "Không", "Search plans submit"],
            [3, "PlansList", "Table", "Có", "id/name/status/FY/milestones count"],
            [4, "CreatePlanForm", "Form", "Không", "Create — edit cap"],
            [5, "DetailLink", "Link", "Có", "→ SCR-CRM-030"],
        ],
        "rules": ["BR-SVC-011"],
    },
    "SCR-CRM-022": {
        "api": "GET sop templates/runs/overdue · POST createSopRun",
        "pre": "crm_board.view; create run cần edit",
        "post": "Run created; overdue tasks visible with lifecycle links",
        "purpose": "SOP library — templates, runs, overdue escalate FR-SD-03",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "OverdueAlertCard", "Alert", "Có", "Overdue tasks table + lifecycle links"],
            [3, "TemplatesList", "List", "Có", "SOP templates incl MKT-LAUNCH-14D"],
            [4, "RunsList", "List", "Có", "Runs with overdue badge"],
            [5, "CreateRunForm", "Form", "Không", "name + template select"],
        ],
        "rules": ["BR-SVC-011", "BR-SVC-012"],
    },
    "SCR-CRM-023": {
        "api": "GET catalog bundle · POST/PATCH services/industries · POST assign scope",
        "pre": "crm_leads.view; configure cần crm_leads.configure",
        "post": "Catalog slug active/inactive; AM scope saved",
        "purpose": "Catalog dịch vụ/ngành + AM assign scope wildcard",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "ServicesTable", "Table", "Có", "slug/name/order/active toggle"],
            [3, "IndustriesTable", "Table", "Có", "Industry catalog CRUD"],
            [4, "AssignScopeTable", "Table", "Có", "AM routing industry/service * wildcard"],
            [5, "LeadsCatalogLink", "Link", "Không", "→ /crm/leads"],
        ],
        "rules": ["BR-CRM-004", "BR-CRM-012"],
    },
    "SCR-CRM-024": {
        "api": "GET staff list · GET staff KPI auto · GET kpi chart",
        "pre": "cap crm_staff_kpi_am_sp.view",
        "post": "Progress list + peer compare chart for period",
        "purpose": "Staff KPI AM/SP — progress list + peer bar chart",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "StaffRoleFilters", "Filter", "Có", "staff/role AM|SP/year/month"],
            [3, "KpiProgressList", "List", "Có", "Auto-metrics per staff"],
            [4, "KpiBarChart", "Chart", "Có", "Peer compare — link staff/[id]"],
        ],
        "rules": ["BR-CRM-013"],
    },
    "SCR-CRM-025": {
        "api": "GET/PATCH owner weekly · GET export JSON",
        "pre": "crm_owner_weekly_dashboard.view; configure/export caps",
        "post": "Dashboard + config saved; JSON export downloaded",
        "purpose": "Owner weekly executive — 4 blocks, actions, configurable targets",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "WeekFilters", "Filter", "Có", "Year/week ISO 1–53 + Export JSON"],
            [3, "KpiTileGrid", "KPI", "Có", "Weekly executive tiles"],
            [4, "OwnerWeeklyBlockGrid", "Grid", "Có", "4 narrative blocks"],
            [5, "OwnerWeeklyActionList", "List", "Có", "Recommended actions"],
            [6, "OwnerWeeklyConfigForm", "Form", "Không", "Targets — configure cap only"],
        ],
        "rules": ["BR-CRM-014"],
    },
    "SCR-CRM-026": {
        "api": "GET payroll dashboard/period/attendance/policy · POST compute · export JSON",
        "pre": "salary OR attendance OR roster view; compute needs salary edit",
        "post": "Payroll computed; attendance max 50 rows",
        "purpose": "Payroll 4-tab — dashboard, lines, attendance, policy JSON",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "PeriodToolbar", "Toolbar", "Có", "Year/month + Tính lương + Export JSON"],
            [3, "PayrollTabSwitcher", "Tabs", "Có", "Dashboard/Payroll/Attendance/Policy"],
            [4, "PayrollLinesList", "List", "Có", "Gross VND formatting"],
            [5, "AttendanceList", "List", "Không", "Max 50 rows"],
            [6, "PolicyJsonPre", "Panel", "Không", "Policy JSON readout"],
        ],
        "rules": ["BR-CRM-013"],
    },
    "SCR-CRM-027": {
        "api": "GET /api/v1/crm/staff/:id/workspace",
        "pre": "cap crm_staff_roster.view",
        "post": "Read-only workspace: cases max 15",
        "purpose": "Staff workspace read-only — open cases + SLA stats",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "BackLink", "Link", "Có", "← roster"],
            [3, "StaffHeader", "Header", "Có", "Name + job title"],
            [4, "StatsLine", "KPI", "Có", "open cases/high priority/SLA overdue"],
            [5, "AssignedCasesList", "List", "Có", "Max 15 cases"],
        ],
        "rules": ["BR-CRM-013"],
    },
    "SCR-CRM-028": {
        "api": "GET re-project * endpoints · POST create* · sync/pull/export",
        "pre": "Per-tab caps: crm_re_projects.* (kpi/budget/risks/export/edit)",
        "post": "Tab data synced; export report types available",
        "purpose": "RE project detail 11 tabs — summary→export, accounting, lead config",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "CapGatedTabBar", "Tabs", "Có", "11 tabs visibility from caps"],
            [3, "SummaryProductsInventory", "Panel", "Có", "Summary/products/inventory tabs"],
            [4, "KpiBudgetRisksPanels", "Panel", "Không", "Financial + risk JSON panels"],
            [5, "AccountingSubViews", "Panel", "Không", "Accounting if budget view"],
            [6, "LeadConfigWorkflow", "Form", "Không", "FB page ID + webhook flags save"],
            [7, "SyncExportActions", "Toolbar", "Không", "Sync/pull/export report types"],
        ],
        "rules": ["BR-CRM-010"],
    },
    "SCR-CRM-029": {
        "api": "GET/PATCH service lifecycle · GET context",
        "pre": "crm_board.view; notes/stage backward cần edit",
        "post": "Stage updated backward-only with confirm; tab deep-link",
        "purpose": "Service delivery lifecycle 7-stage detail — workflow/TMMT/finance/SOP/QA",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "LifecycleHeader", "Header", "Có", "Stage/status display"],
            [3, "NotesForm", "Form", "Không", "Patch notes — edit cap"],
            [4, "BackwardStageSelector", "Select", "Không", "Backward-only + confirm"],
            [5, "LifecycleHubLinksPanel", "Nav", "Có", "Cross-module links"],
            [6, "DetailTabs", "Tabs", "Có", "workflow/tmmt/finance/sop/launch_qa ?tab="],
            [7, "EventsLog", "Timeline", "Có", "Lifecycle audit events"],
        ],
        "rules": ["BR-SVC-001", "BR-SVC-003", "BR-SVC-004"],
    },
    "SCR-CRM-030": {
        "api": "GET/PATCH /api/v1/crm/marketing-plans/:id",
        "pre": "crm_board.view; save cần edit",
        "post": "Plan patched; milestones read-only",
        "purpose": "Chi tiết marketing plan — name/status/notes + milestone list",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Sidebar"],
            [2, "BackLink", "Link", "Có", "← /crm/marketing-plan"],
            [3, "PlanNameInput", "Input", "Có", "Editable with edit cap"],
            [4, "StatusSelect", "Select", "Có", "draft/review/active/paused/completed/archived/cancelled"],
            [5, "NotesTextarea", "Textarea", "Không", "Internal AM notes"],
            [6, "SaveButton", "Button", "Có", "PATCH plan"],
            [7, "MilestoneList", "Read-only", "Có", "Title + status per milestone"],
        ],
        "rules": ["BR-SVC-011"],
    },
}
