"""Manual BA use-case details — CRM Core (CRM-UC-001 … CRM-UC-015)."""
from __future__ import annotations

from rnosai_ba_detail_helpers import uc_detail

CRM_USE_CASE_DETAILS: dict[str, dict] = {
    "CRM-UC-001": uc_detail(
        "CRM-UC-001",
        "Đăng nhập & phân công lead tự động",
        screens="SCR-CRM-001, SCR-AUTH-001",
        actor="CSKH / Sales",
        actor_secondary="System (webhook ingest, assignment engine)",
        goal="Lead mới được gán owner primary tự động sau ingest",
        trigger="Lead mới từ Meta/Zalo/form hoặc import Excel",
        pre="Staff đăng nhập ops-web; assignment rules configured; lead source mapped",
        post="Lead có owner primary; audit source + timestamp",
        priority="P0",
        wave="Wave R1",
        trace="P0-2",
        api="POST /api/v1/leads · POST /webhooks/meta|zalo · GET /crm/leads",
        main=[
            [1, "Webhook hoặc form submit tạo lead (PLAT-UC-004/005, META-UC-004, ZALO-UC-011)"],
            [2, "Engine dedup theo phone/email (BR-CRM-001)"],
            [3, "Gán owner: round-robin / territory / product line / ML route (RNOS-26)"],
            [4, "Lead xuất hiện /crm/leads status Mới + cột AI Score"],
            [5, "CSKH nhận notification in-app; trigger AI-UC-001 score async"],
        ],
        alt=[
            ["E1", "Duplicate → merge hoặc link existing lead; không tạo bản ghi trùng"],
            ["E2", "Không match rule → fallback GDKD review queue (CRM-UC-003)"],
            ["E3", "Import batch → queue assignment per row"],
        ],
        io_in="Lead payload: phone, name, email, source, campaign_id, meta_json",
        io_out="Lead record + owner_id + assignment audit + ingest source",
        rules=["BR-CRM-001", "BR-PLAT-004"],
    ),
    "CRM-UC-002": uc_detail(
        "CRM-UC-002",
        "Chăm sóc lead B2 (Liên hệ OK)",
        screens="SCR-CRM-002",
        actor="CSKH",
        goal="Ghi nhận liên hệ thành công và chuyển status B2",
        trigger="CSKH liên hệ thành công lead Mới/B1",
        pre="Lead status Mới/B1; staff là owner primary",
        post="SLA contact time tracked; KPI CSKH cập nhật; activity timeline",
        priority="P0",
        wave="Wave R1",
        api="PATCH /api/v1/leads/:id · POST activity · LeadFunnelPanel",
        main=[
            [1, "CSKH mở /crm/leads/[id] — verify owner=me hoặc GDKD"],
            [2, "Log call/note trên activity timeline"],
            [3, "Cập nhật status → B2 — Liên hệ OK qua LeadFunnelPanel"],
            [4, "Hệ thống ghi activity + SLA contact timestamp"],
            [5, "Nếu qualify → chuyển Pre-sales CRM-UC-005"],
        ],
        alt=[
            ["E1", "Không liên lạc được → B1 retry hoặc Lost với reason bắt buộc"],
            ["E2", "Copy SĐT/Zalo từ lead detail → log manual outreach"],
        ],
        io_in="lead_id, activity note, call outcome, next action",
        io_out="updated status B2, activity record, SLA metrics",
        rules=["BR-CRM-002"],
    ),
    "CRM-UC-003": uc_detail(
        "CRM-UC-003",
        "Review queue GDKD",
        screens="SCR-CRM-003, SCR-CRM-010",
        actor="GDKD / Head Sales",
        goal="GDKD duyệt/reassign lead high-value hoặc không match assignment rule",
        trigger="Lead vào review queue: high value / no owner / policy",
        pre="Agency tenant; lead flagged review_required",
        post="Lead có owner hợp lệ hoặc archived với reason audit",
        priority="P0",
        wave="Wave R1",
        api="GET /crm/leads/review-queue · PATCH assign/reject",
        main=[
            [1, "GDKD mở /crm/leads/review-queue hoặc hub CRM"],
            [2, "Xem lead summary, source, estimated value, reason queue"],
            [3, "Approve assign → chọn owner + priority"],
            [4, "Reject/reassign → comment bắt buộc"],
            [5, "Lead rời queue; notification gửi owner mới"],
        ],
        alt=[
            ["E1", "Deal > threshold → bắt buộc GDKD trước proposal (BR-CRM-003)"],
            ["E2", "Bulk approve nhiều lead cùng owner"],
        ],
        io_in="lead_id, assignee_id, priority, reject_reason",
        io_out="assignment audit, queue status cleared",
        rules=["BR-CRM-003"],
    ),
    "CRM-UC-004": uc_detail(
        "CRM-UC-004",
        "Add-on ngành trên lead",
        screens="SCR-CRM-002",
        actor="CSKH / AM",
        goal="Theo dõi nhu cầu đa ngành trên một lead (BĐS + MKT + …)",
        trigger="Lead có nhu cầu cross-industry trong discovery",
        pre="Lead active; catalog ngành seeded CRM-UC-012",
        post="Lead có 1+ add-on lines; routing rules áp dụng per line",
        priority="P1",
        wave="Wave R2",
        api="PATCH lead add-ons · catalog API",
        main=[
            [1, "Mở lead detail → tab Add-ons"],
            [2, "Chọn ngành từ catalog (CRM-UC-012)"],
            [3, "Gán specialist phụ theo ngành"],
            [4, "Pipeline tracking per add-on line trên funnel panel"],
            [5, "Add-on Won/Lost độc lập với lead master status"],
        ],
        alt=[
            ["E1", "Duplicate add-on ngành → merge lines"],
        ],
        io_in="lead_id, industry_sku[], specialist_ids[]",
        io_out="add_on lines[], routing overrides",
        rules=["BR-CRM-004", "BR-CRM-012"],
    ),
    "CRM-UC-005": uc_detail(
        "CRM-UC-005",
        "Pre-sales & KH MKT sơ bộ",
        screens="SCR-CRM-012, SCR-CRM-002",
        actor="Pre-sales / AM",
        goal="Discovery qualify và tạo KH MKT sơ bộ (draft scope)",
        trigger="Lead B2 qualify sau CRM-UC-002",
        pre="Lead status B2+; pre-sales cap enabled",
        post="KH MKT draft linked to lead; stage Proposal prep",
        priority="P0",
        wave="Wave R1",
        api="POST /crm/intake · pre-sales record API",
        main=[
            [1, "Pre-sales discovery call → ghi needs, budget, timeline trên /crm/intake"],
            [2, "Tạo KH MKT sơ bộ draft scope document"],
            [3, "Attach competitor / brief docs"],
            [4, "Chuyển stage → Proposal prep (CRM-UC-006)"],
            [5, "Notify AM nếu handoff từ CSKH"],
        ],
        alt=[
            ["E1", "Not qualify → return lead CSKH với reason"],
        ],
        io_in="lead_id, discovery notes, budget_range, timeline, attachments[]",
        io_out="pre_sales_record_id, KH MKT draft_id",
        rules=["BR-CRM-005"],
    ),
    "CRM-UC-006": uc_detail(
        "CRM-UC-006",
        "Chuyển lead → Proposal/HĐ",
        screens="SCR-CRM-014, SCR-CRM-002",
        actor="Sales / AM",
        goal="Tạo proposal từ template → client accept → HĐ draft",
        trigger="Client đồng ý scope sơ bộ (CRM-UC-005)",
        pre="Lead qualified; catalog dịch vụ active",
        post="Proposal linked; HĐ record nếu ký; stage Proposal/Won path",
        priority="P0",
        wave="Wave R1",
        api="POST /crm/proposals · GET/POST contracts API",
        main=[
            [1, "AM tạo Proposal từ template trên /crm/proposals"],
            [2, "Chọn dịch vụ từ catalog → pricing lines"],
            [3, "Gửi client email/PDF export"],
            [4, "Client accept → tạo HĐ draft"],
            [5, "Legal/finance sign-off → HĐ active → CRM-UC-007 path"],
        ],
        alt=[
            ["E1", "Revision → version proposal; giữ history"],
            ["E2", "GDKD approval nếu deal > threshold (CRM-UC-003)"],
        ],
        io_in="lead_id, service_skus[], pricing_lines[], proposal_version",
        io_out="proposal_id, contract_draft_id, PDF artifact",
        rules=["BR-CRM-006", "BR-CRM-003"],
    ),
    "CRM-UC-007": uc_detail(
        "CRM-UC-007",
        "Convert → Customer + Case",
        screens="SCR-CRM-008, SCR-CRM-009, SCR-CRM-002",
        actor="Sales / AM",
        actor_secondary="System",
        goal="Convert lead/deal Won → Customer master + delivery case",
        trigger="HĐ ký / Won deal",
        pre="Contract signed; unique customer code available",
        post="Customer active; duplicate lead merged; SVC onboard triggered",
        priority="P0",
        wave="Wave R1",
        trace="SYS-001",
        api="POST /api/v1/leads/:id/convert · GET /crm/customers",
        main=[
            [1, "AM action Convert to Customer trên lead/deal detail"],
            [2, "System tạo Customer master + link HĐ"],
            [3, "Tạo Case delivery initial (optional RE project CRM-UC-010)"],
            [4, "Trigger service lifecycle Onboard SVC-UC-001"],
            [5, "Revenue fields feed closed-loop SYS-UC-002"],
            [6, "Timeline enrich AI-UC-008 trên customer detail"],
        ],
        alt=[
            ["E1", "Duplicate legal entity → merge customer records"],
            ["E2", "Partial convert → retain lead for upsell lines"],
        ],
        io_in="lead_id, contract_id, customer legal fields",
        io_out="customer_id, case_id, merge audit",
        rules=["BR-CRM-007", "BR-CRM-001"],
    ),
    "CRM-UC-008": uc_detail(
        "CRM-UC-008",
        "Quản lý bảng CSKH",
        screens="SCR-CRM-004, SCR-CRM-017",
        actor="CSKH / CSKH Lead",
        goal="Theo dõi case CSKH Kanban SLA + ticket queue",
        trigger="Daily ops CSKH; case mới hoặc SLA breach",
        pre="Case CSKH tồn tại; cap cskh.view",
        post="Kanban SLA accurate; breaches visible; assignments updated",
        priority="P0",
        wave="Wave R1",
        trace="P1-3, RNOS-24",
        api="GET /api/v1/cskh/board · PATCH cases/:id · /crm/tickets",
        main=[
            [1, "CSKH mở /crm/cskh-board Kanban"],
            [2, "Filter owner, SLA status, client"],
            [3, "Kéo thả hoặc cập nhật case status"],
            [4, "SLA badge xanh/vàng/đỏ realtime"],
            [5, "Bulk assign / reschedule follow-up; export snapshot standup"],
            [6, "Ticket queue /crm/tickets cho case phức tạp"],
        ],
        alt=[
            ["E1", "Reassign case → owner mới notification"],
            ["E2", "SLA breach → escalate GDKD optional"],
        ],
        io_in="case_id, new status, assignee, due_at",
        io_out="updated Kanban state, SLA metrics, export CSV",
        rules=["BR-CRM-008"],
    ),
    "CRM-UC-009": uc_detail(
        "CRM-UC-009",
        "Pipeline sales & đề xuất",
        screens="SCR-CRM-013",
        actor="Sales / GDKD",
        goal="Kanban pipeline deals Qualify → Won/Lost với forecast weight",
        trigger="Deal enter pipeline hoặc stage drag",
        pre="Lead qualified hoặc proposal linked",
        post="Pipeline report accurate; Won triggers CRM-UC-007",
        priority="P1",
        wave="Wave R2",
        trace="RNOS-23",
        api="GET/PATCH /crm/sales/pipeline · deal score AI-UC-012",
        main=[
            [1, "Mở /crm/sales pipeline Kanban"],
            [2, "Drag stage: Qualify → Proposal → Negotiation → Won/Lost"],
            [3, "Ghi lost reason taxonomy nếu Lost"],
            [4, "Forecast weight per stage cho GDKD dashboard"],
            [5, "Deal score mini-bar AI-UC-012; NBA AI-UC-011 nếu stalled"],
        ],
        alt=[
            ["E1", "Won → prompt convert customer CRM-UC-007"],
            ["E2", "Stage regression → audit who moved back"],
        ],
        io_in="deal_id, new_stage, lost_reason?, quote_value",
        io_out="pipeline snapshot, forecast delta, deal score",
        rules=["BR-CRM-009", "BR-AI-011"],
    ),
    "CRM-UC-010": uc_detail(
        "CRM-UC-010",
        "Dự án BĐS (RE Projects)",
        screens="SCR-CRM-015",
        actor="RE PM / AM BĐS",
        goal="Quản lý RE project: units inventory, campaign mapping, lead theo dự án",
        trigger="Tạo RE project gắn customer hoặc pre-launch",
        pre="RE module enabled; Facebook leadgen webhook configured",
        post="Leads mapped to project; attribution per dự án",
        priority="P1",
        wave="Wave R1",
        trace="TC-PROJ-08, META-UC-004",
        api="POST /crm/re-projects · webhook leadgen map project_id",
        main=[
            [1, "Tạo RE project: tên, location, units inventory"],
            [2, "Map Meta/Zalo campaigns → project (hub map)"],
            [3, "Webhook leadgen gắn project_id + assignment pool BĐS"],
            [4, "Báo cáo leads/conversion theo project"],
            [5, "Drill lead list filter project trên /crm/leads"],
        ],
        alt=[
            ["E1", "Unit sold out → stop assign new leads to unit"],
        ],
        io_in="project config, units[], campaign_map[]",
        io_out="project_id, lead attribution, inventory state",
        rules=["BR-CRM-010", "BR-META-004"],
    ),
    "CRM-UC-011": uc_detail(
        "CRM-UC-011",
        "Hub hợp đồng & lifecycle",
        screens="SCR-CRM-010",
        actor="AM / GDKD / Finance",
        goal="Single pane contract health + lifecycle stage per client",
        trigger="AM/GDKD mở hub CRM daily",
        pre="Contracts exist in system",
        post="Renewal alerts visible; drill HĐ → services → invoices",
        priority="P0",
        wave="Wave R1",
        trace="RNOS-25",
        api="GET /crm/hub · contract lifecycle API · orders/invoices drill",
        main=[
            [1, "Mở /crm/hub — contracts expiring widget"],
            [2, "Drill client → HĐ detail → linked services modules"],
            [3, "Alert renewal 30/60/90 days"],
            [4, "Link orders/invoices RNOS-25 finance gate"],
            [5, "Review queue shortcut CRM-UC-003"],
        ],
        alt=[
            ["E1", "Overdue invoice → highlight red; block handover SVC-UC-004"],
        ],
        io_in="filter client, lifecycle stage, date range",
        io_out="hub dashboard state, renewal task suggestions",
        rules=["BR-CRM-011", "BR-SVC-004"],
    ),
    "CRM-UC-012": uc_detail(
        "CRM-UC-012",
        "Catalog dịch vụ/ngành",
        screens="SCR-CRM-012",
        actor="Admin / AM",
        goal="CRUD service SKUs, industry verticals, pricing tiers cho proposal",
        trigger="Admin maintain catalog hoặc AM chọn dịch vụ proposal",
        pre="Admin cap catalog.edit",
        post="Service lines selectable on proposals; disabled SKUs hidden",
        priority="P1",
        wave="Wave R2",
        api="GET/POST /crm/catalog · admin catalog API",
        main=[
            [1, "Admin mở catalog management (intake/admin route)"],
            [2, "CRUD service SKUs + industry verticals"],
            [3, "Set pricing tiers và enable/disable per SKU"],
            [4, "AM chọn catalog lines trên proposal CRM-UC-006"],
            [5, "Add-on ngành CRM-UC-004 reference same catalog"],
        ],
        alt=[
            ["E1", "Disable SKU in-use → grandfather existing proposals"],
        ],
        io_in="sku code, name, industry, price_tier, active flag",
        io_out="catalog version, selectable SKUs list",
        rules=["BR-CRM-012"],
    ),
    "CRM-UC-013": uc_detail(
        "CRM-UC-013",
        "KPI nhân sự & chấm công",
        screens="SCR-CRM-011, SCR-CRM-016",
        actor="GDKD / HR / Team Lead",
        goal="Attendance + KPI scorecard per staff (leads handled, conversion)",
        trigger="Monthly close hoặc GDKD review /crm/kpi",
        pre="Staff roster active SCR-CRM-016; caps assigned",
        post="KPI tiles rendered; export staff KPI Excel",
        priority="P1",
        wave="Wave R1",
        trace="RNOS-42",
        api="GET /crm/kpi · export Excel · staff roster API",
        main=[
            [1, "HR maintain roster /crm/staff caps và teams"],
            [2, "Attendance log ingest (manual or integration)"],
            [3, "KPI targets per role: leads handled, B2 rate, conversion"],
            [4, "GDKD mở /crm/kpi — tiles + drill staff row"],
            [5, "Export staff KPI Excel for payroll/bonus review"],
        ],
        alt=[
            ["E1", "Missing attendance → KPI partial with warning"],
        ],
        io_in="staff_id, period, attendance records, KPI targets",
        io_out="scorecard tiles, Excel export file",
        rules=["BR-CRM-013"],
    ),
    "CRM-UC-014": uc_detail(
        "CRM-UC-014",
        "Dashboard kinh doanh chủ DN",
        screens="SCR-CRM-005",
        actor="GDKD / Chủ DN",
        goal="Executive dashboard revenue YTD, pipeline, win rate, channel mix",
        trigger="GDKD mở /crm/business-dashboard",
        pre="Finance + CRM data synced tenant scope",
        post="Drill-down ≤3 clicks SYS-UC-007; tiles accurate",
        priority="P1",
        wave="Wave R1",
        trace="RNOS-46",
        api="GET /api/v1/crm/business-dashboard",
        main=[
            [1, "Mở /crm/business-dashboard executive tiles"],
            [2, "Xem revenue YTD, pipeline weighted, win rate, top AM"],
            [3, "Channel mix Meta/Zalo/Google split"],
            [4, "Drill tile → detail module ≤3 clicks"],
            [5, "Optional export PDF snapshot"],
        ],
        alt=[
            ["E1", "Cross-tenant data probe → empty/403 (BR-CRM-014)"],
        ],
        io_in="tenant_id, date_range, drill path",
        io_out="KPI aggregates, drill targets, PDF export",
        rules=["BR-CRM-014", "BR-SYS-007", "BR-SYS-002"],
    ),
    "CRM-UC-015": uc_detail(
        "CRM-UC-015",
        "Import/export lead",
        screens="SCR-CRM-001",
        actor="Sales / AM / Admin",
        goal="Import/export lead Excel/CSV với validate và dedup preview",
        trigger="User bấm Import/Export trên CrmLeadsImportExport toolbar",
        pre="Cap crm_leads.edit; template chuẩn downloaded",
        post="Import job log; source tagged import; export filter results",
        priority="P1",
        wave="Wave R1",
        trace="P0-2",
        api="POST /api/v1/leads/import · GET export · leads_import_sample.csv",
        main=[
            [1, "Download CSV/Excel template chuẩn"],
            [2, "Upload file → validate columns bắt buộc phone/name"],
            [3, "Dedup preview: new vs skip vs update rows"],
            [4, "Confirm import → batch create/update + assignment CRM-UC-001"],
            [5, "Export filter results CSV từ danh sách hiện tại"],
        ],
        alt=[
            ["E1", "Validation fail → row-level error report; partial import optional"],
            ["E2", "Missing required column → HTTP 400 + message"],
        ],
        io_in="import file, column mapping, dedup mode",
        io_out="import job result counts, export CSV, audit log",
        rules=["BR-CRM-015", "BR-CRM-001"],
    ),
}
