"""Deep SCR UI/API overrides — Mobile Experience (cross-cutting PWA surfaces)."""

MOB_SCR_OVERRIDES: dict[str, dict] = {
    "SCR-MOB-001": {
        "module_key": "MOB",
        "api": "GET /manifest.webmanifest · GET /sw.js · staff auth",
        "pre": "NEXT_PUBLIC_PWA_ENABLED=1; ops-web served",
        "post": "SW registered; install banner dismissed or accepted",
        "purpose": "PWA install shell staff — banner + service worker ops-web",
        "app": "ops-web (rs.pttads.vn) global",
        "ui": [
            [1, "PwaShell", "Banner", "Không", "Fixed bottom install CTA RNOS-41"],
            [2, "InstallActions", "Button", "Không", "Thêm màn hình chính · Để sau"],
            [3, "ServiceWorkerRegister", "System", "Có", "register /sw.js ptt-ops-pwa-v1"],
        ],
        "rules": ["BR-MOB-01", "BR-MOB-02"],
    },
    "SCR-MOB-002": {
        "module_key": "MOB",
        "api": "GET /api/v1/leads",
        "pre": "Staff JWT + cap crm_leads.view",
        "post": "Lead cards rendered @ ≤768px",
        "purpose": "Lead list mobile card view — thay table desktop",
        "app": "ops-web /crm/leads @ mobile",
        "ui": [
            [1, "CrmLeadsCards", "List", "Có", ".crm-leads-cards @768px"],
            [2, "LeadCardLink", "Card", "Có", "Name · phone · status · AI score"],
            [3, "FilterBar", "Form", "Có", "Shared desktop filters"],
            [4, "TableWrapHidden", "Layout", "Có", "Hide .crm-leads-table-wrap mobile"],
        ],
        "rules": ["BR-MOB-02", "BR-CRM-001"],
    },
    "SCR-MOB-003": {
        "module_key": "MOB",
        "api": (
            "GET /api/crm/leads/:id · GET attribution/activities/audit · PATCH status · POST assign/activity · "
            "GET/POST /api/v1/ai/scores · /route/lead · /next-best-action · /summarize · recommendation draft"
        ),
        "pre": "Staff JWT + crm_leads.view; lead id hợp lệ; aiCopilotEnabled() cho tab AI",
        "post": "Lead detail + timeline; copilot brief/draft copy-only (BR-AI-01)",
        "purpose": (
            "Lead detail responsive @<1024px: 3-tab Chi tiết/Hoạt động/AI; tablet FAB drawer; desktop inline copilot"
        ),
        "app": "ops-web /crm/leads/[id] — page.tsx + LeadCopilotPanel",
        "status_note": "Done 1.0 — tabs+drawer+copilot+tel Gọi+offline banner+gate E2E ✅",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell rs.pttads.vn"],
            [2, "BackLink", "Link", "Có", "← /crm/leads"],
            [3, "LeadDetailTabs", "Tab bar", "Có", "Chi tiết · Hoạt động · AI @ mobile <1024 + copilot on"],
            [4, "LeadHeaderCard", "Card", "Có", "#id · name · LeadAttributionChips"],
            [5, "LeadDetailDl", "DL", "Có", "SĐT/email/source/owner — lead-detail-dl grid"],
            [6, "ContactQuickActions", "Button", "Có", "Gọi tel: · Copy SĐT · Copy Zalo — data-testid lead-contact-*"],
            [7, "StatusAssignForms", "Form", "Có", "Status + assign + add activity — caps edit/assign"],
            [8, "ActivityTimeline", "List", "Có", "lead-activity-list; select → AI summarize"],
            [9, "AuditSection", "Panel", "Có", "Status + assignment audit logs"],
            [10, "LeadCopilotPanel", "Panel", "Có", "Score · Route · NBA · Brief · Summarize · Follow-up draft"],
            [11, "CopilotFabDrawer", "Drawer", "Có", "Tablet 1024–1279: FAB + ai-copilot-panel--drawer"],
            [12, "CopilotTrustFooter", "Footer", "Có", "data-testid=copilot-trust-footer BR-AI-01"],
            [13, "CopilotOfflineBanner", "Alert", "Có", "data-testid=copilot-offline-banner — MOB-UC-003 E1"],
        ],
        "rules": ["BR-MOB-02", "BR-MOB-04", "BR-MOB-05", "BR-AI-001", "BR-AI-002"],
    },
    "SCR-MOB-004": {
        "module_key": "MOB",
        "api": (
            "GET /api/crm/cskh-board · POST bulk-assign · POST bulk-reschedule · "
            "GET /api/crm/cskh-board/export · GET staff catalog"
        ),
        "pre": "Staff JWT + CSKH board view cap; SLA data synced (CRM-UC-008)",
        "post": "Mobile card list reflects filter + summary; tap → lead detail",
        "purpose": "CSKH SLA first-call board @≤768px — card list thay table (target M1.2)",
        "app": "ops-web /crm/cskh-board — CskhBoardContent.tsx",
        "status_note": "Done 1.0 — card list + SLA chips + gate rnos_mob_cskh_board_gate.sh ✅",
        "ui": [
            [1, "OpsNav", "Navigation", "Có", "Staff shell"],
            [2, "PageHeader", "Header", "Có", "SLA first call 15m subtitle CRM-UC-008"],
            [3, "SlaSummaryChips", "Chip row", "Có", "Sticky breach/warning/ok — target @768px"],
            [4, "FilterAccordion", "Collapsible", "Có", "sla_filter · owner_id · q · Lọc — target collapse"],
            [5, "CskhLeadCard", "Card", "Có", "Target .cskh-board-cards — link /crm/leads/[id]"],
            [6, "SlaBadge", "Badge", "Có", "ok/warning/breach/na + sla_minutes_elapsed"],
            [7, "CskhBoardTable", "Table", "Có", "As-is desktop; ẩn @768px khi cards ship"],
            [8, "BulkActionSheet", "Sheet", "Không", "Reassign + reschedule — cap crm_leads.assign"],
            [9, "ExportCsvButton", "Button", "Có", "cskhBoardExportUrl — giữ mobile"],
            [10, "PaginationBar", "Pager", "Có", "PAGE_SIZE=50 prev/next"],
            [11, "EmptyState", "Alert", "Có", "Không có lead phù hợp bộ lọc"],
        ],
        "rules": ["BR-CRM-008", "BR-MOB-02", "BR-MOB-05"],
    },
    "SCR-MOB-005": {
        "module_key": "MOB",
        "api": "GET /manifest.webmanifest · GET /sw.js",
        "pre": "NEXT_PUBLIC_PWA_ENABLED=1 portal-web",
        "post": "Portal SW + optional install",
        "purpose": "Portal PWA install shell RNOS-M2",
        "app": "portal-web global",
        "ui": [
            [1, "PortalPwaShell", "Banner", "Không", "Above bottom nav offset"],
            [2, "InstallActions", "Button", "Không", "Cài PTT Portal"],
            [3, "ServiceWorkerRegister", "System", "Có", "ptt-portal-pwa-v1"],
        ],
        "rules": ["BR-MOB-01", "BR-PLAT-003"],
    },
    "SCR-MOB-006": {
        "module_key": "MOB",
        "api": "GET portal performance · notification summary",
        "pre": "Portal JWT session",
        "post": "Dashboard KPI + bottom nav",
        "purpose": "Portal dashboard mobile 2-col KPI + bottom nav",
        "app": "portal-web /dashboard @ ≤768px",
        "ui": [
            [1, "PortalMobileBottomNav", "Navigation", "Có", "Home · Creative · Alerts · Settings"],
            [2, "KpiGridMobile", "KPI", "Có", "2-col scroll"],
            [3, "PortalNavDesktopHidden", "Layout", "Có", ".portal-nav-links hidden mobile"],
            [4, "SessionWarning", "Badge", "Không", "JWT expiry notice"],
        ],
        "rules": ["BR-PORTAL-002", "BR-MOB-05"],
    },
    "SCR-MOB-007": {
        "module_key": "MOB",
        "api": "GET/POST portal creatives approve/reject",
        "pre": "Approver role for actions",
        "post": "Creative decision recorded",
        "purpose": "Creative inbox mobile — approve/reject cards",
        "app": "portal-web /creatives @ mobile",
        "ui": [
            [1, "CreativeInboxCards", "List", "Có", "Stack cards full width"],
            [2, "ApproveRejectActions", "Button", "Có", "Touch target ≥44px"],
            [3, "RejectModal", "Modal", "Không", "Comment required BR-PORTAL-009"],
            [4, "BottomNavBadge", "Badge", "Có", "Pending count"],
        ],
        "rules": ["BR-PORTAL-006", "BR-PORTAL-009"],
    },
    "SCR-MOB-008": {
        "module_key": "MOB",
        "api": "GET portal email approvals",
        "pre": "email_enabled; approver",
        "post": "Email approval decision",
        "purpose": "Email approvals mobile card list",
        "app": "portal-web /email/approvals @ mobile",
        "ui": [
            [1, "EmailApprovalCards", "List", "Có", "MobileCampaignCards pattern"],
            [2, "PreviewModal", "Modal", "Không", "320px mobile preview tab"],
            [3, "ApproveRejectBar", "Button", "Có", "Primary actions sticky optional"],
        ],
        "rules": ["BR-PORTAL-008", "BR-EM-007"],
    },
    "SCR-MOB-009": {
        "module_key": "MOB",
        "api": "GET/PATCH portal notifications",
        "pre": "Portal JWT",
        "post": "Notifications read state updated",
        "purpose": "Notification center mobile list",
        "app": "portal-web /notifications @ mobile",
        "ui": [
            [1, "NotificationList", "List", "Có", "Unread highlight"],
            [2, "MarkAllRead", "Button", "Có", "Bulk read"],
            [3, "BottomNavAlerts", "Navigation", "Có", "Unread badge"],
        ],
        "rules": ["BR-ZALO-020", "BR-SYS-004"],
    },
    "SCR-MOB-010": {
        "module_key": "MOB",
        "api": "POST/DELETE /api/v1/portal/push/subscribe · POST push/test",
        "pre": "Push API enabled; Notification API",
        "post": "Subscription stored PG",
        "purpose": "Push notification settings on /settings",
        "app": "portal-web /settings (Push section)",
        "ui": [
            [1, "PushNotificationCard", "Form", "Có", "Bật/tắt push MOB-UC-009"],
            [2, "TestPushButton", "Button", "Không", "Gửi test push staging"],
            [3, "PermissionStatus", "Text", "Có", "Quyền Notification hiện tại"],
            [4, "BrandingSettings", "Form", "Có", "Existing settings below"],
        ],
        "rules": ["BR-MOB-03", "BR-PORTAL-012"],
    },
}
