"""Manual BA use-case details — System Overview cross-module (SYS-UC-001 … SYS-UC-012)."""
from __future__ import annotations

from rnosai_ba_detail_helpers import uc_detail

SYS_USE_CASE_DETAILS: dict[str, dict] = {
    "SYS-UC-001": uc_detail(
        "SYS-UC-001",
        "Onboard client mới end-to-end",
        screens="SCR-AGENCY-002, SCR-AGENCY-001",
        actor="AM / Admin",
        actor_secondary="Tracking/Tech, Email/SEO Strategist",
        goal="Onboard client qua checklist và bật module theo HĐ",
        trigger="HĐ mới ký; lifecycle → Onboard",
        pre="Lead convert hoặc customer CRM tồn tại; staff cap CRM/agency",
        post="Client active; module flags theo HĐ; portal users (optional)",
        priority="P0",
        wave="Wave R1",
        trace="SYS-001, TC-ONBOARD-01",
        api="POST /agency/clients/new · onboard orchestrator · SVC-UC-002",
        main=[
            [1, "AM xác nhận customer master /crm/hub hoặc /crm/customers"],
            [2, "Tạo service lifecycle stage Onboard SVC-UC-001"],
            [3, "Hoàn thành onboard checklist SVC-UC-002"],
            [4, "Onboard module theo HĐ: Meta META-UC-001, SEO SEO-UC-001, Email EM-UC-001"],
            [5, "Tracking verify webhook + CAPI META-UC-004/005"],
            [6, "AM tạo portal users PORTAL-UC-001"],
            [7, "Lifecycle → Deliver khi checklist pass"],
        ],
        alt=[
            ["E1", "Chỉ CRM chưa ads → defer Meta trong checklist"],
            ["E2", "Client từ chối portal → optional; báo cáo manual"],
        ],
        io_in="customer_id, service bundle, HĐ module list",
        io_out="client_id, module flags, checklist audit, portal map",
        rules=["BR-SYS-001", "BR-SVC-002"],
    ),
    "SYS-UC-002": uc_detail(
        "SYS-UC-002",
        "Closed-loop Spend → Lead → Revenue",
        screens="SCR-META-001, SCR-CRM-001, SCR-CRM-005",
        actor="GDKD / System",
        actor_secondary="Media Buyer, AM, Sales",
        goal="Attribution Spend → Lead → Revenue visible hub + portal",
        trigger="Campaign Meta chạy; CRM lead ingest hoạt động",
        pre="Ad account mapped; insights T-1 OK; CRM ingest OK",
        post="CPL/ROAS closed-loop trên hub và portal",
        priority="P0",
        wave="Wave R1",
        trace="SYS-002, TC-LOOP-01",
        api="Meta insights sync · CRM pipeline · hub KPI API",
        main=[
            [1, "Worker sync Meta spend T-1 META-UC-003"],
            [2, "Webhook lead form → CRM lead META-UC-004, CRM-UC-001"],
            [3, "Sales cập nhật pipeline → Won CRM-UC-009"],
            [4, "CAPI conversion events META-UC-005"],
            [5, "Hub tính CPL, ROAS (revenue CRM nếu có)"],
            [6, "AM review /meta/facebook-ads + báo cáo client SYS-UC-005"],
        ],
        alt=[
            ["E1", "Unmapped spend → CPL cảnh báo vàng; map campaign META-UC-002"],
            ["E2", "Không revenue data → ROAS ẩn; chỉ CPL"],
        ],
        io_in="spend sync, leads, deal revenue, campaign map",
        io_out="CPL, ROAS, attribution dashboard rows",
        rules=["BR-SYS-002", "BR-CRM-001", "BR-META-003"],
    ),
    "SYS-UC-003": uc_detail(
        "SYS-UC-003",
        "Launch campaign đa kênh có governance",
        screens="SCR-SVC-001, SCR-META-004, SCR-SVC-002",
        actor="AM / Media Buyer",
        actor_secondary="Creative Lead, Client Approver, Compliance",
        goal="Go-live campaign cross-channel với QA + approval audit",
        trigger="Yêu cầu go-live campaign mới",
        pre="Client onboard; creative sẵn sàng; Launch QA policy bật",
        post="Campaign live Meta; audit log đầy đủ",
        priority="P0",
        wave="Wave R1",
        trace="SYS-003",
        api="Launch QA · Ads Ops wizard · Campaign Write queue · Meta launch API",
        main=[
            [1, "Creative upload Creative Hub SVC-UC-006"],
            [2, "Launch QA checklist pass SVC-UC-005"],
            [3, "Buyer mở Ads Ops wizard META-UC-007"],
            [4, "Submit Campaign Write queue / Temporal SVC-UC-007"],
            [5, "Client approver portal PORTAL-UC-006 nếu policy yêu cầu"],
            [6, "Governance pass → launch API Meta"],
            [7, "Monitor hub + alerts META-UC-009"],
        ],
        alt=[
            ["E1", "Reject creative → quay bước 1 với comment"],
            ["E2", "Budget over threshold → thêm approver GDKD BR-SVC-007"],
        ],
        io_in="creative assets, campaign config, approval policy",
        io_out="campaign_id live, governance audit chain",
        rules=["BR-SYS-003", "BR-SVC-005", "BR-SVC-006", "BR-SVC-007"],
    ),
    "SYS-UC-004": uc_detail(
        "SYS-UC-004",
        "Client approval cross-module",
        screens="SCR-PORTAL-004, SCR-PORTAL-006, SCR-PORTAL-005",
        actor="Client Approver",
        actor_secondary="AM, Strategist (submitter)",
        goal="Client sign-off item cross-module với audit",
        trigger="Staff submit item pending_client_approval",
        pre="Portal approver active; item pending_client_approval",
        post="Audit ghi approver, timestamp, decision",
        priority="P0",
        wave="Wave R1",
        trace="SYS-004",
        api="Portal approvals API · Temporal signals · notify webhooks",
        main=[
            [1, "Staff submit Meta creative / SEO content / Email campaign"],
            [2, "System notify portal PORTAL-UC-006…008"],
            [3, "Approver login → inbox → preview"],
            [4, "Approve → status cập nhật → staff notification"],
            [5, "Staff tiếp tục launch/publish/send theo module"],
        ],
        alt=[
            ["E1", "Reject PORTAL-UC-009 — comment bắt buộc"],
            ["E2", "SLA quá 24h → AM escalate manual"],
        ],
        io_in="approval_item_id, module, preview payload",
        io_out="decision, comment, audit record, downstream unlock",
        rules=["BR-SYS-004", "BR-PORTAL-006", "BR-PORTAL-009", "BR-PLAT-008"],
    ),
    "SYS-UC-005": uc_detail(
        "SYS-UC-005",
        "Báo cáo định kỳ cho khách hàng",
        screens="SCR-PORTAL-001, SCR-PORTAL-003",
        actor="AM / System",
        actor_secondary="Client Viewer",
        goal="Deliver báo cáo weekly/monthly PDF hoặc portal view",
        trigger="Scheduler weekly/monthly hoặc on-demand",
        pre="Module sync OK; portal hoặc email recipient configured",
        post="Artifact stored; delivery log",
        priority="P0",
        wave="Wave R1",
        trace="SYS-005",
        api="Report scheduler · PDF worker · portal notification · email webhook",
        main=[
            [1, "Scheduler trigger Meta RPT, SEO PDF, Email schedule"],
            [2, "Worker aggregate KPI T-1 / period"],
            [3, "Generate PDF hoặc enable portal view"],
            [4, "Deliver email webhook hoặc portal notification"],
            [5, "AM confirm client đã nhận hypercare SYS-UC-012"],
        ],
        alt=[
            ["E1", "Sync fail → báo cáo partial + disclaimer yellow banner"],
        ],
        io_in="client_id, period, module list, recipient config",
        io_out="PDF/CSV artifact, delivery log, portal link",
        rules=["BR-SYS-005", "BR-META-013", "BR-SEO-013", "BR-PORTAL-003"],
    ),
    "SYS-UC-006": uc_detail(
        "SYS-UC-006",
        "Offboard client & thu hồi quyền",
        screens="SCR-AGENCY-001",
        actor="Admin",
        actor_secondary="AM, Tracking, DevOps",
        goal="Revoke access all modules; archive client",
        trigger="HĐ chấm dứt; lifecycle → Offboarding",
        pre="Offboard request approved; SVC-UC-012 initiated",
        post="Không active spend/send; tokens revoked; client Archived",
        priority="P1",
        wave="Wave R2",
        trace="SYS-006",
        api="Token revoke APIs · portal disable · module pause endpoints",
        main=[
            [1, "Lifecycle stage Offboarding SVC-UC-012"],
            [2, "Revoke Meta token / pause email send / archive SEO sync"],
            [3, "Disable portal users"],
            [4, "Export data theo HĐ nếu yêu cầu"],
            [5, "Archive client → Archived"],
        ],
        alt=[
            ["E1", "Outstanding legal hold → partial revoke with compliance ticket"],
        ],
        io_in="client_id, offboard checklist, export request",
        io_out="revoked tokens, archived status, export package",
        rules=["BR-SYS-006", "BR-SVC-012"],
    ),
    "SYS-UC-007": uc_detail(
        "SYS-UC-007",
        "Drill-down executive ≤3 clicks",
        screens="SCR-CRM-005, SCR-META-001",
        actor="GDKD",
        actor_secondary="AM, Head",
        goal="Trả lời client health trong ≤3 click từ hub tile",
        trigger="Review sáng hub executive",
        pre="Hub KPI tiles populated; user cap executive dashboard",
        post="Detail module reached ≤3 clicks; PO acceptance RNOS-46",
        priority="P1",
        wave="Wave R2",
        trace="RNOS-46",
        api="Hub drill-down routes · client workspace APIs",
        main=[
            [1, "Mở hub module SEO /email /meta"],
            [2, "Click client health row (click 1)"],
            [3, "Client workspace (click 2)"],
            [4, "Module detail contacts/issues/campaign (click 3)"],
        ],
        alt=[
            ["E1", "Missing module data → deep-link với stale banner not dead-end"],
        ],
        io_in="hub context, client_id filter",
        io_out="drill path ≤3 hops, detail view payload",
        rules=["BR-SYS-007", "BR-CRM-014", "BR-SEO-012"],
    ),
    "SYS-UC-008": uc_detail(
        "SYS-UC-008",
        "Incident P1 — webhook down",
        screens="SCR-AGENCY-004",
        actor="DevOps / Admin",
        actor_secondary="AM (comms client)",
        goal="Restore webhook ingest; log incident P1",
        trigger="Webhook error rate >1% hoặc zero ingest >15min",
        pre="Monitoring alert RPT-M7 red; ingest monitor visible",
        post="Ingest restored; incident log closed",
        priority="P0",
        wave="Wave R1",
        trace="SYS-008",
        api="Ingest monitor · replay dead letter · alert webhooks",
        main=[
            [1, "Alert monitoring red trên /agency/ingest"],
            [2, "DevOps verify nginx, Nest, signature, Meta app config"],
            [3, "Fix hoặc rollback env"],
            [4, "Replay failed events dead letter nếu có"],
            [5, "Post-mortem + client comms nếu mất lead"],
        ],
        alt=[
            ["E1", "Signature misconfig → rotate secret + replay window"],
        ],
        io_in="alert payload, failed event queue, runbook steps",
        io_out="incident ticket, restore timestamp, replay count",
        rules=["BR-SYS-008", "BR-PLAT-004", "BR-SVC-009"],
    ),
    "SYS-UC-009": uc_detail(
        "SYS-UC-009",
        "Staged prod cutover module flag",
        screens="SCR-ADMIN-002",
        actor="Super Admin",
        actor_secondary="DevOps, Tech Lead",
        goal="Bật module theo gate A/B/C/D với soak evidence",
        trigger="Gate A / module pilot ready",
        pre="Staging soak scripts available; feature flags configured",
        post="Module enabled per tenant; smoke UAT sign-off",
        priority="P1",
        wave="Wave R2",
        trace="SYS-009",
        api="Env flags PTT_* · ops-web NEXT_PUBLIC_* rebuild · gate scripts",
        main=[
            [1, "B1: PTT_EMAIL_ENABLED=1 send off"],
            [2, "Soak ≥3–7 ngày; gate scripts PASS"],
            [3, "B2/B3/B4: bật send, portal, journeys theo checklist"],
            [4, "Rebuild ops-web NEXT_PUBLIC_* flags"],
            [5, "Smoke UAT + sign-off PLAT-UC-010"],
        ],
        alt=[
            ["E1", "Gate fail → rollback flag + incident note"],
        ],
        io_in="module flag matrix, tenant list, gate script results",
        io_out="enabled modules per env, soak evidence artifacts",
        rules=["BR-SYS-009", "BR-PLAT-010"],
    ),
    "SYS-UC-010": uc_detail(
        "SYS-UC-010",
        "Audit trail tra cứu cross-module",
        screens="SCR-ADMIN-001",
        actor="Compliance / Admin",
        goal="Tra cứu audit governance cross-module theo client/date/actor",
        trigger="Compliance review hoặc dispute investigation",
        pre="Audit index populated từ EM, SEO, CRM, portal, AI",
        post="Query returns hits với export optional",
        priority="P1",
        wave="Wave R2",
        trace="AI-UC-009",
        api="GET /admin/audit · cross-module audit index",
        main=[
            [1, "Admin mở audit console SCR-ADMIN-001"],
            [2, "Filter client_id, date range, actor, module"],
            [3, "Search spans Email E-13, SEO S-14, CRM workflow, portal approvals"],
            [4, "View detail row immutable timestamp + payload hash"],
            [5, "Export CSV scoped compliance role"],
        ],
        alt=[
            ["E1", "Index lag → show last_sync_at warning"],
        ],
        io_in="filters: client_id, date, actor, module",
        io_out="audit rows[], export file",
        rules=["BR-SYS-010", "BR-AI-009", "BR-EM-012"],
    ),
    "SYS-UC-011": uc_detail(
        "SYS-UC-011",
        "Multi-client isolation verify",
        screens="SCR-AGENCY-001",
        actor="Admin / QA",
        actor_secondary="Security",
        goal="Verify không cross-tenant data leak portal + staff APIs",
        trigger="Pen test checklist hoặc release gate",
        pre="Multi-tenant data seeded TC-ISO-01",
        post="Pen test checklist pass; no cross-client leak",
        priority="P0",
        wave="Wave R1",
        trace="SYS-011, TC-ISO-01",
        api="All APIs filter client_id · portal JWT scope tests",
        main=[
            [1, "User client A login portal"],
            [2, "API không trả data client B — 403 hoặc empty"],
            [3, "Staff filter bắt buộc client_id Meta/SEO/Email APIs"],
            [4, "Automated TC-ISO-01 regression"],
            [5, "Document evidence cho nghiệm thu"],
        ],
        alt=[
            ["E1", "Leak detected → block release P0 hotfix"],
        ],
        io_in="tenant A/B credentials, probe endpoints",
        io_out="isolation test report pass/fail",
        rules=["BR-SYS-011", "BR-PLAT-003", "BR-PORTAL-001"],
    ),
    "SYS-UC-012": uc_detail(
        "SYS-UC-012",
        "Hypercare post go-live",
        screens="SCR-CRM-004, SCR-AGENCY-001",
        actor="AM / CSKH",
        actor_secondary="Tech Lead",
        goal="30-day hypercare SLA sau go-live với daily standup",
        trigger="Sign-off nghiệm thu; SVC-UC-003 deliver milestone",
        pre="Go-live date set; hypercare playbook configured",
        post="Hypercare exit report; steady-state SLA handoff",
        priority="P1",
        wave="Wave R2",
        trace="SYS-012",
        api="CSKH board SLA · hypercare tracker · soak scripts",
        main=[
            [1, "Start hypercare clock tại go-live Deliver"],
            [2, "Daily standup 2–4 tuần AM + Tech Lead"],
            [3, "P1 ack 30min; defect triage CRM-UC-008 board"],
            [4, "Run soak scripts; monitor ingest + reports SYS-UC-005"],
            [5, "Hypercare exit report → steady-state SLA"],
        ],
        alt=[
            ["E1", "Critical defect → extend hypercare với PO sign-off"],
        ],
        io_in="go_live_date, defect list, SLA config",
        io_out="hypercare exit report, SLA handoff doc",
        rules=["BR-SYS-012", "BR-CRM-008", "BR-SVC-003"],
    ),
}
