import {
  KPI_HUB_DEFAULT_WORKSPACE_ID,
  KPI_HUB_TENANT_ID,
  type HubAlertEvent,
  type HubDictionaryRow,
  type HubOwnerRef,
  type HubPeriodTargetRow,
  type HubQualityIssue,
  type HubQualityRule,
  type HubReportRow,
  type HubSourceConnection,
  type HubWorkspaceRow,
} from './kpi-hub.types';

const now = '2026-09-04T08:45:00+07:00';
const wsId = KPI_HUB_DEFAULT_WORKSPACE_ID;

const owners: Record<string, HubOwnerRef> = {
  perf: { id: 101, name: 'Performance MKT', email: 'perf.mkt@ptt.vn' },
  data: { id: 102, name: 'Nguyễn Thị Lan', email: 'data.steward@ptt.vn' },
  sales: { id: 103, name: 'Trần Văn Hùng', email: 'sales.mgr@ptt.vn' },
  finance: { id: 104, name: 'Lê Minh Tuấn', email: 'finance@ptt.vn' },
};

function kpi(
  id: string,
  code: string,
  name: string,
  group: string,
  color: string,
  direction: HubDictionaryRow['direction'],
  unit: string,
  calcKind: HubDictionaryRow['calc_kind'],
  source: string,
  status: HubDictionaryRow['status'],
  extra: Partial<HubDictionaryRow> = {},
): HubDictionaryRow {
  return {
    id,
    tenant_id: KPI_HUB_TENANT_ID,
    workspace_id: wsId,
    code,
    name,
    description: extra.description ?? null,
    kpi_group: group,
    kpi_group_color: color,
    kpi_type_id: null,
    direction,
    unit,
    decimal_places: extra.decimal_places ?? (unit.includes('%') ? 1 : 0),
    calc_kind: calcKind,
    formula_display: extra.formula_display ?? null,
    tech_preview: extra.tech_preview ?? null,
    business_formula: extra.business_formula ?? null,
    blank_if_zero: extra.blank_if_zero ?? false,
    non_additive_ratio: extra.non_additive_ratio ?? false,
    allow_manual: extra.allow_manual ?? false,
    numerator_code: extra.numerator_code ?? null,
    denominator_code: extra.denominator_code ?? null,
    primary_source: source,
    sync_frequency: 'Hàng ngày 08:00',
    kpi_owner: extra.kpi_owner ?? owners.perf,
    data_owner: extra.data_owner ?? owners.data,
    status,
    current_version: status === 'ACTIVE' ? 1 : 0,
    published_at: status === 'ACTIVE' ? '2026-08-15T10:00:00+07:00' : null,
    row_version: 1,
    created_at: '2026-08-01T09:00:00+07:00',
    updated_at: now,
    deleted_at: null,
    ...extra,
  };
}

/** 21 KPI catalog per SRS §29 */
export function buildDictionaryFixtures(): HubDictionaryRow[] {
  return [
    kpi('d001', 'MKT_001', 'Tổng Raw Leads', 'Acquisition', '#3B82F6', 'HIGHER_IS_BETTER', 'Lead', 'COUNT', 'SharePoint/CRM', 'ACTIVE', {
      formula_display: 'DISTINCTCOUNT(Leads[Lead_ID])',
      description: 'Tổng lead thô trước lọc valid.',
    }),
    kpi('d002', 'MKT_002', 'Tổng Valid Leads', 'Acquisition', '#3B82F6', 'HIGHER_IS_BETTER', 'Lead', 'COUNT', 'CRM', 'ACTIVE', {
      formula_display: 'DISTINCTCOUNT(Leads[Lead_ID]) WHERE Is_Valid=TRUE',
      description: 'Lead hợp lệ, không trùng, không test.',
    }),
    kpi('d003', 'MKT_003', 'Valid Lead Rate', 'Acquisition', '#3B82F6', 'HIGHER_IS_BETTER', '%', 'RATIO', 'CRM/SharePoint', 'ACTIVE', {
      calc_kind: 'RATIO',
      numerator_code: 'MKT_002',
      denominator_code: 'MKT_001',
      business_formula: 'Valid Lead Rate = MKT_002 ÷ MKT_001',
      tech_preview: 'DIVIDE([MKT_002], [MKT_001])',
      non_additive_ratio: true,
      blank_if_zero: true,
    }),
    kpi('d004', 'MKT_004', 'Tổng chi tiêu quảng cáo', 'Media Efficiency', '#10B981', 'LOWER_IS_BETTER', 'VND', 'SUM', 'Meta/Google/TikTok Ads', 'ACTIVE', {
      formula_display: 'SUM(AdInsights[Spend])',
      kpi_owner: owners.perf,
    }),
    kpi('d005', 'MKT_005', 'CPL Raw Lead', 'Media Efficiency', '#10B981', 'LOWER_IS_BETTER', 'VND/Lead', 'RATIO', 'Ads + SharePoint', 'ACTIVE', {
      numerator_code: 'MKT_004',
      denominator_code: 'MKT_001',
      business_formula: 'CPL Raw Lead = Chi tiêu quảng cáo ÷ Raw Leads',
      tech_preview: 'DIVIDE([MKT_004], [MKT_001])',
      non_additive_ratio: true,
      blank_if_zero: true,
    }),
    kpi('d006', 'MKT_006', 'CPL Valid Lead', 'Media Efficiency', '#10B981', 'LOWER_IS_BETTER', 'VND/Lead', 'RATIO', 'Ads + CRM', 'ACTIVE', {
      numerator_code: 'MKT_004',
      denominator_code: 'MKT_002',
      business_formula: 'CPL Valid Lead = Tổng chi tiêu quảng cáo ÷ Tổng Valid Leads',
      tech_preview: 'DIVIDE([MKT_004], [MKT_002])',
      formula_display: 'DIVIDE([Tổng chi tiêu quảng cáo], [Tổng Valid Leads])',
      non_additive_ratio: true,
      blank_if_zero: true,
      description: 'Chi phí trên mỗi Valid Lead từ các kênh quảng cáo trả phí.',
    }),
    kpi('d007', 'MKT_007', 'Tổng MQL', 'Funnel', '#8B5CF6', 'HIGHER_IS_BETTER', 'Lead', 'COUNT', 'CRM', 'ACTIVE', {
      formula_display: "DISTINCTCOUNT(Leads[Lead_ID]) WHERE status='MQL'",
    }),
    kpi('d008', 'MKT_008', 'MQL Rate', 'Funnel', '#8B5CF6', 'HIGHER_IS_BETTER', '%', 'RATIO', 'CRM', 'ACTIVE', {
      numerator_code: 'MKT_007',
      denominator_code: 'MKT_002',
      business_formula: 'MQL Rate = MKT_007 ÷ MKT_002',
      tech_preview: 'DIVIDE([MKT_007], [MKT_002])',
      non_additive_ratio: true,
      blank_if_zero: true,
    }),
    kpi('d009', 'MKT_009', 'ROAS', 'Media Efficiency', '#10B981', 'HIGHER_IS_BETTER', 'x', 'RATIO', 'Ads/CRM/ERP', 'ACTIVE', {
      numerator_code: 'SAL_008',
      denominator_code: 'MKT_004',
      business_formula: 'ROAS = Doanh thu ký mới ÷ Chi tiêu quảng cáo',
      tech_preview: 'DIVIDE([SAL_008], [MKT_004])',
      non_additive_ratio: true,
      blank_if_zero: true,
    }),
    kpi('d010', 'SAL_001', 'Tổng SQL', 'Funnel', '#8B5CF6', 'HIGHER_IS_BETTER', 'Lead', 'COUNT', 'CRM', 'ACTIVE', {
      formula_display: "DISTINCTCOUNT(Leads[Lead_ID]) WHERE status='SQL'",
      kpi_owner: owners.sales,
    }),
    kpi('d011', 'SAL_002', 'SQL Rate', 'Funnel', '#8B5CF6', 'HIGHER_IS_BETTER', '%', 'RATIO', 'CRM', 'ACTIVE', {
      numerator_code: 'SAL_001',
      denominator_code: 'MKT_007',
      non_additive_ratio: true,
      blank_if_zero: true,
    }),
    kpi('d012', 'SAL_003', 'Tổng cuộc hẹn', 'Funnel', '#8B5CF6', 'HIGHER_IS_BETTER', 'Cuộc hẹn', 'COUNT', 'CRM', 'ACTIVE'),
    kpi('d013', 'SAL_004', 'Show-up Rate', 'Funnel', '#8B5CF6', 'HIGHER_IS_BETTER', '%', 'RATIO', 'CRM', 'ACTIVE', {
      business_formula: 'Show-up Rate = Completed appointments ÷ Valid appointments',
      non_additive_ratio: true,
    }),
    kpi('d014', 'SAL_005', 'Pipeline Value', 'Sales Outcome', '#F59E0B', 'HIGHER_IS_BETTER', 'VND', 'SUM', 'CRM', 'ACTIVE', {
      formula_display: 'SUM(Deals[Amount]) WHERE status=Open',
      kpi_owner: owners.sales,
    }),
    kpi('d015', 'SAL_007', 'Win Rate', 'Sales Outcome', '#F59E0B', 'HIGHER_IS_BETTER', '%', 'RATIO', 'CRM', 'ACTIVE', {
      business_formula: 'Win Rate = Won ÷ (Won + Lost)',
      non_additive_ratio: true,
      kpi_owner: owners.sales,
    }),
    kpi('d016', 'SAL_008', 'Doanh thu ký mới', 'Sales Outcome', '#F59E0B', 'HIGHER_IS_BETTER', 'VND', 'SUM', 'CRM', 'ACTIVE', {
      formula_display: 'SUM(Contracts[Value]) WHERE status=Won/Signed',
      description: 'Doanh thu hợp đồng ký mới — khác FIN_001/FIN_002.',
      kpi_owner: owners.sales,
    }),
    kpi('d017', 'SAL_WON', 'Deal Won (count)', 'Sales Outcome', '#F59E0B', 'HIGHER_IS_BETTER', 'Deal', 'COUNT', 'CRM', 'ACTIVE'),
    kpi('d018', 'FIN_001', 'Doanh thu xuất hóa đơn', 'Finance', '#6366F1', 'HIGHER_IS_BETTER', 'VND', 'SUM', 'ERP', 'ACTIVE', {
      formula_display: 'SUM(Invoices[Amount]) WHERE valid=TRUE',
      kpi_owner: owners.finance,
      data_owner: owners.finance,
    }),
    kpi('d019', 'FIN_002', 'Doanh thu thu tiền', 'Finance', '#6366F1', 'HIGHER_IS_BETTER', 'VND', 'SUM', 'ERP/Bank', 'ACTIVE', {
      formula_display: 'SUM(Payments[Amount]) WHERE cleared=TRUE',
      kpi_owner: owners.finance,
    }),
    kpi('d020', 'FIN_003', 'CAC', 'Finance', '#6366F1', 'LOWER_IS_BETTER', 'VND/KH', 'RATIO', 'Ads/CRM/Finance', 'ACTIVE', {
      business_formula: 'CAC = (Marketing Cost + Sales Cost) ÷ New Customers',
      non_additive_ratio: true,
      kpi_owner: owners.finance,
    }),
    kpi('d021', 'OPS_001', 'Lead Response Time', 'Operations', '#64748B', 'LOWER_IS_BETTER', 'Phút', 'AVG', 'CRM/Call Center', 'ACTIVE'),
    kpi('d022', 'OPS_002', 'Lead Contact Rate', 'Operations', '#64748B', 'HIGHER_IS_BETTER', '%', 'RATIO', 'CRM/Call Center', 'NEED_REVIEW', {
      numerator_code: 'MKT_002',
      denominator_code: 'MKT_002',
      description: 'Contacted Valid Leads ÷ MKT_002 — cần rà soát mapping.',
    }),
  ];
}

export function buildWorkspaceFixture(): HubWorkspaceRow {
  return {
    id: wsId,
    tenant_id: KPI_HUB_TENANT_ID,
    name: 'KPI Hub - Marketing & Sales',
    company: 'PTT Digital',
    logo_url: null,
    timezone: 'Asia/Ho_Chi_Minh',
    locale: 'vi',
    currency: 'VND',
    week_start: 'MONDAY',
    default_period_grain: 'MONTH',
    close_day: 3,
    reconcile_day: 5,
    lock_closed_periods: true,
    allow_reopen: false,
    require_kpi_approval: true,
    auto_quality: true,
    alerts_enabled: true,
    maintenance_mode: false,
    row_version: 1,
    created_at: '2026-08-01T09:00:00+07:00',
    updated_at: now,
  };
}

export function buildSourceFixtures(): HubSourceConnection[] {
  return [
    {
      id: 'src-crm',
      workspace_id: wsId,
      system: 'CRM',
      name: 'CRM Leads & Deals',
      external_ref: 'crm-leads-prod',
      sla_minutes: 60,
      last_success_at: '2026-09-04T08:30:00+07:00',
      last_error: null,
      status: 'FRESH',
      entity_count: 12,
      quality_pct: 98,
      unmapped_count: 0,
    },
    {
      id: 'src-meta',
      workspace_id: wsId,
      system: 'META_ADS',
      name: 'Meta Ads Insights',
      external_ref: 'meta-ads-act_123',
      sla_minutes: 120,
      last_success_at: '2026-09-04T08:15:00+07:00',
      last_error: null,
      status: 'FRESH',
      entity_count: 8,
      quality_pct: 97,
      unmapped_count: 12,
    },
    {
      id: 'src-sharepoint',
      workspace_id: wsId,
      system: 'SHAREPOINT',
      name: 'SharePoint Campaign Mapping',
      external_ref: 'sp-campaign-lookup',
      sla_minutes: 60,
      last_success_at: '2026-09-04T06:30:00+07:00',
      last_error: null,
      status: 'DELAYED',
      entity_count: 3,
      quality_pct: 96,
      unmapped_count: 12,
    },
    {
      id: 'src-erp',
      workspace_id: wsId,
      system: 'ERP',
      name: 'ERP Finance',
      external_ref: 'erp-finance-prod',
      sla_minutes: 240,
      last_success_at: '2026-09-04T07:00:00+07:00',
      last_error: null,
      status: 'FRESH',
      entity_count: 6,
      quality_pct: 99,
      unmapped_count: 0,
    },
    {
      id: 'src-google',
      workspace_id: wsId,
      system: 'GOOGLE_ADS',
      name: 'Google Ads',
      external_ref: 'google-ads-prod',
      sla_minutes: 120,
      last_success_at: '2026-09-04T08:00:00+07:00',
      last_error: null,
      status: 'FRESH',
      entity_count: 5,
      quality_pct: 95,
      unmapped_count: 2,
    },
    {
      id: 'src-ga4',
      workspace_id: wsId,
      system: 'GA4',
      name: 'Google Analytics 4',
      external_ref: 'ga4-prod',
      sla_minutes: 180,
      last_success_at: null,
      last_error: 'Connector chưa kích hoạt',
      status: 'UNKNOWN',
      entity_count: 0,
      quality_pct: null,
      unmapped_count: null,
    },
    {
      id: 'src-tiktok',
      workspace_id: wsId,
      system: 'GOOGLE_ADS',
      name: 'TikTok Ads',
      external_ref: 'tiktok-ads-prod',
      sla_minutes: 120,
      last_success_at: '2026-09-04T07:45:00+07:00',
      last_error: null,
      status: 'FRESH',
      entity_count: 4,
      quality_pct: 94,
      unmapped_count: 1,
    },
  ];
}

export function buildTargetFixtures(dict: HubDictionaryRow[]): HubPeriodTargetRow[] {
  const find = (code: string) => dict.find((d) => d.code === code)!;
  const period = '2026-09';
  const mk = (
    id: string,
    code: string,
    target: number,
    warning: number | null,
    critical: number | null,
    actual: number | null,
    status: HubPeriodTargetRow['status'],
    trend: number | null,
  ): HubPeriodTargetRow => {
    const d = find(code);
    return {
      id,
      dictionary_id: d.id,
      dictionary_code: d.code,
      dictionary_name: d.name,
      period,
      period_start: '2026-09-01',
      period_end: '2026-09-30',
      grain: 'MONTH',
      scope_type: 'ORGANIZATION',
      scope_label: 'Toàn tổ chức',
      direction: d.direction,
      unit: d.unit,
      target_value: target,
      warning_value: warning,
      critical_value: critical,
      actual_value: actual,
      status,
      trend_pct: trend,
      alerts_enabled: true,
      row_version: 1,
      updated_at: now,
    };
  };
  return [
    mk('t001', 'MKT_006', 150000, 180000, 220000, 142000, 'ACHIEVED', -5.3),
    mk('t002', 'MKT_008', 30, 25, 20, 24.8, 'WARNING', -2.1),
    mk('t003', 'SAL_007', 20, 15, 12, 12.5, 'CRITICAL', -3.8),
    mk('t004', 'SAL_008', 1200000000, 1000000000, 800000000, 1240000000, 'ACHIEVED', 18.6),
    mk('t005', 'MKT_002', 1400, 1200, 1000, 1486, 'ACHIEVED', 12.4),
    mk('t006', 'MKT_004', 220000000, 250000000, 280000000, 210980000, 'ACHIEVED', -4.1),
    mk('t007', 'FIN_003', 5000000, 6000000, 7500000, 4800000, 'ACHIEVED', -2.0),
    mk('t008', 'MKT_009', 3.5, 2.5, 2.0, 3.8, 'ACHIEVED', 8.5),
  ];
}

export function buildAlertFixtures(): HubAlertEvent[] {
  return [
    {
      id: 'ae001',
      rule_id: 'ar001',
      dictionary_id: 'd015',
      dictionary_code: 'SAL_007',
      level: 'CRITICAL',
      title: 'Win Rate thấp hơn ngưỡng Critical',
      scope: 'Sales Team A',
      actual: 12.5,
      threshold: 20,
      status: 'OPEN',
      age: '8m',
      created_at: '2026-09-04T08:37:00+07:00',
      acknowledged_at: null,
      acknowledged_by: null,
    },
    {
      id: 'ae002',
      rule_id: 'ar002',
      dictionary_id: 'd008',
      dictionary_code: 'MKT_008',
      level: 'WARNING',
      title: 'MQL Rate chưa đạt target',
      scope: 'Campaign BĐS Q3',
      actual: 24.8,
      threshold: 30,
      status: 'OPEN',
      age: '2h',
      created_at: '2026-09-04T06:45:00+07:00',
      acknowledged_at: null,
      acknowledged_by: null,
    },
    {
      id: 'ae003',
      rule_id: 'ar003',
      dictionary_id: null,
      dictionary_code: null,
      level: 'INFO',
      title: 'SharePoint Mapping trễ 2 giờ',
      scope: 'Data Quality',
      actual: null,
      threshold: null,
      status: 'OPEN',
      age: '2h',
      created_at: '2026-09-04T06:45:00+07:00',
      acknowledged_at: null,
      acknowledged_by: null,
    },
    {
      id: 'ae004',
      rule_id: 'ar004',
      dictionary_id: 'd006',
      dictionary_code: 'MKT_006',
      level: 'SUCCESS',
      title: 'CPL Valid Lead đạt target',
      scope: 'Marketing',
      actual: 142000,
      threshold: 150000,
      status: 'RESOLVED',
      age: '1d',
      created_at: '2026-09-03T09:00:00+07:00',
      acknowledged_at: '2026-09-03T10:00:00+07:00',
      acknowledged_by: 101,
    },
  ];
}

export function buildQualityRules(): HubQualityRule[] {
  return [
    {
      id: 'qr001',
      name: 'Lead_ID không trùng',
      connection_id: 'src-crm',
      connection_name: 'CRM Leads & Deals',
      check_type: 'UNIQUENESS',
      severity: 'CRITICAL',
      enabled: true,
      last_run_at: now,
      pass_rate: 99.2,
      affected_count: 12,
    },
    {
      id: 'qr002',
      name: 'Completeness email/phone',
      connection_id: 'src-crm',
      connection_name: 'CRM Leads & Deals',
      check_type: 'COMPLETENESS',
      severity: 'WARNING',
      enabled: true,
      last_run_at: now,
      pass_rate: 94.5,
      affected_count: 86,
    },
    {
      id: 'qr003',
      name: 'Campaign mapping coverage',
      connection_id: 'src-sharepoint',
      connection_name: 'SharePoint Campaign Mapping',
      check_type: 'CONSISTENCY',
      severity: 'WARNING',
      enabled: true,
      last_run_at: now,
      pass_rate: 96.0,
      affected_count: 12,
    },
    {
      id: 'qr004',
      name: 'Spend currency = VND',
      connection_id: 'src-meta',
      connection_name: 'Meta Ads Insights',
      check_type: 'CONSISTENCY',
      severity: 'WARNING',
      enabled: true,
      last_run_at: now,
      pass_rate: 100,
      affected_count: 0,
    },
    {
      id: 'qr005',
      name: 'Invoice amount > 0',
      connection_id: 'src-erp',
      connection_name: 'ERP Finance',
      check_type: 'VALIDITY',
      severity: 'INFO',
      enabled: true,
      last_run_at: now,
      pass_rate: 100,
      affected_count: 0,
    },
    {
      id: 'qr006',
      name: 'Freshness CRM ≤ 60 phút',
      connection_id: 'src-crm',
      connection_name: 'CRM Leads & Deals',
      check_type: 'FRESHNESS',
      severity: 'INFO',
      enabled: true,
      last_run_at: now,
      pass_rate: 100,
      affected_count: 0,
    },
    {
      id: 'qr007',
      name: 'GA4 connector available',
      connection_id: 'src-ga4',
      connection_name: 'Google Analytics 4',
      check_type: 'AVAILABILITY',
      severity: 'INFO',
      enabled: false,
      last_run_at: null,
      pass_rate: null,
      affected_count: 0,
    },
  ];
}

export function buildQualityIssues(): HubQualityIssue[] {
  return [
    {
      id: 'qi001',
      rule_id: 'qr001',
      rule_name: 'Lead_ID không trùng',
      status: 'OPEN',
      severity: 'CRITICAL',
      title: 'Lead_ID trùng lặp',
      description: 'Phát hiện 12 bản ghi Lead_ID trùng trong CRM kỳ 09/2026.',
      affected_count: 12,
      assignee: null,
      sla_due: '2026-09-05T17:00:00+07:00',
      ticket_ref: null,
      sample_rows: [
        { lead_id: 'LD-202609-0042', duplicate_of: 'LD-202609-0018', source: 'Meta Ads' },
        { lead_id: 'LD-202609-0087', duplicate_of: 'LD-202609-0033', source: 'Google Ads' },
      ],
      created_at: '2026-09-04T08:00:00+07:00',
    },
    {
      id: 'qi002',
      rule_id: 'qr003',
      rule_name: 'Campaign mapping coverage',
      status: 'ASSIGNED',
      severity: 'WARNING',
      title: '12 campaign chưa được mapping',
      description: 'Campaign ID từ Meta Ads chưa có UTM tương ứng trong SharePoint.',
      affected_count: 12,
      assignee: owners.data,
      sla_due: '2026-09-06T17:00:00+07:00',
      ticket_ref: 'IWR-4521',
      sample_rows: [{ campaign_id: 'camp_8821', spend: 12500000 }],
      created_at: '2026-09-03T14:00:00+07:00',
    },
  ];
}

export function buildReportFixtures(): HubReportRow[] {
  return [
    {
      id: 'rp001',
      name: 'Báo cáo Marketing tuần',
      type: 'MARKETING_WEEKLY',
      scope: 'Marketing',
      status: 'ACTIVE',
      owner: owners.perf,
      last_generated_at: '2026-09-02T08:00:00+07:00',
      shared_count: 8,
      schedule_cron: '0 8 * * 1',
      next_run_at: '2026-09-08T08:00:00+07:00',
      row_version: 1,
      created_at: '2026-07-01T09:00:00+07:00',
      updated_at: now,
    },
    {
      id: 'rp002',
      name: 'Sales Pipeline Review',
      type: 'SALES_PIPELINE',
      scope: 'Sales',
      status: 'ACTIVE',
      owner: owners.sales,
      last_generated_at: '2026-09-03T17:00:00+07:00',
      shared_count: 5,
      schedule_cron: '0 17 * * 5',
      next_run_at: '2026-09-05T17:00:00+07:00',
      row_version: 1,
      created_at: '2026-07-15T09:00:00+07:00',
      updated_at: now,
    },
    {
      id: 'rp003',
      name: 'Finance KPI Snapshot',
      type: 'FINANCE',
      scope: 'Finance',
      status: 'DRAFT',
      owner: owners.finance,
      last_generated_at: null,
      shared_count: 0,
      schedule_cron: null,
      next_run_at: null,
      row_version: 1,
      created_at: '2026-08-20T09:00:00+07:00',
      updated_at: now,
    },
  ];
}

export function buildDashboardFixture() {
  return {
    period: { from: '2026-09-01', to: '2026-09-30', timezone: 'Asia/Ho_Chi_Minh' },
    freshness: {
      as_of: now,
      label: 'Dữ liệu cập nhật: Hôm nay, 08:45',
      sources: [
        { system: 'CRM', status: 'FRESH' as const, label: 'CRM Fresh' },
        { system: 'META_ADS', status: 'FRESH' as const, label: 'Meta Ads Fresh' },
        { system: 'SHAREPOINT', status: 'DELAYED' as const, label: 'SharePoint Delayed' },
      ],
    },
    cards: [
      {
        code: 'SAL_008',
        name: 'Doanh thu ký mới',
        value: 1240000000,
        formatted: '1,24 tỷ đ',
        target: 1200000000,
        status: 'ACHIEVED' as const,
        badge: 'Đạt target',
        delta_pct: 18.6,
      },
      {
        code: 'MKT_002',
        name: 'Tổng Valid Leads',
        value: 1486,
        formatted: '1.486',
        target: 1400,
        status: 'ACHIEVED' as const,
        badge: 'Đạt target',
        delta_pct: 12.4,
      },
      {
        code: 'MKT_006',
        name: 'CPL Valid Lead',
        value: 142000,
        formatted: '142.000 đ',
        target: 150000,
        status: 'ACHIEVED' as const,
        badge: 'Đạt target ≤ 150.000 đ',
        delta_pct: null,
      },
      {
        code: 'MKT_008',
        name: 'MQL Rate',
        value: 24.8,
        formatted: '24,8%',
        target: 30,
        status: 'WARNING' as const,
        badge: 'Thiếu 5,2% so target',
        delta_pct: -2.1,
      },
      {
        code: 'SAL_007',
        name: 'Win Rate',
        value: 12.5,
        formatted: '12,5%',
        target: 20,
        status: 'CRITICAL' as const,
        badge: 'Nguy cấp < 20%',
        delta_pct: -3.8,
      },
    ],
    funnel: {
      stages: [
        { code: 'MKT_001', name: 'Raw Leads', value: 2340, conversion_from_prev: null },
        { code: 'MKT_002', name: 'Valid Leads', value: 1486, conversion_from_prev: 0.635 },
        { code: 'MKT_007', name: 'MQL', value: 369, conversion_from_prev: 0.248 },
        { code: 'SAL_001', name: 'SQL', value: 152, conversion_from_prev: 0.412 },
        { code: 'SAL_003', name: 'Cuộc hẹn', value: 86, conversion_from_prev: 0.566 },
        { code: 'SAL_WON', name: 'Deal Won', value: 19, conversion_from_prev: 0.221 },
      ],
      bottleneck: { code: 'MKT_008', label: 'MQL Rate' },
    },
    target_progress: {
      overall_pct: 68,
      label: '68% Tổng thể',
      groups: [
        { code: 'ACQUISITION', label: 'Acquisition', pct: 92 },
        { code: 'MEDIA_EFFICIENCY', label: 'Media Efficiency', pct: 95 },
        { code: 'FUNNEL', label: 'Funnel', pct: 71 },
        { code: 'SALES_OUTCOME', label: 'Sales Outcome', pct: 46 },
      ],
    },
    channels: [
      { channel: 'META_ADS', label: 'Meta Ads', valid_leads: 820, revenue: 410000000 },
      { channel: 'GOOGLE_ADS', label: 'Google Ads', valid_leads: 310, revenue: 280000000 },
      { channel: 'ORGANIC', label: 'Organic', valid_leads: 240, revenue: 190000000 },
      { channel: 'REFERRAL', label: 'Referral', valid_leads: 116, revenue: 360000000 },
    ],
    alerts: [
      { level: 'CRITICAL', title: 'Win Rate thấp hơn ngưỡng Critical', scope: 'Sales Team A', age: '8m' },
      { level: 'WARNING', title: 'MQL Rate chưa đạt target', scope: 'Campaign BĐS Q3', age: '2h' },
      { level: 'INFO', title: 'SharePoint Mapping trễ 2 giờ', scope: 'Data Quality', age: '2h' },
      { level: 'SUCCESS', title: 'CPL Valid Lead đạt target', scope: 'Marketing', age: '1d' },
    ],
    top_sales: [
      { rank: 1, name: 'Nguyễn Minh Anh', revenue: 420000000, revenue_formatted: '420 triệu', win_rate: 0.187, win_rate_pct: '18,7%' },
      { rank: 2, name: 'Phạm Hoàng Long', revenue: 310000000, revenue_formatted: '310 triệu', win_rate: 0.152, win_rate_pct: '15,2%' },
      { rank: 3, name: 'Trần Thị Mai', revenue: 285000000, revenue_formatted: '285 triệu', win_rate: 0.141, win_rate_pct: '14,1%' },
    ],
  };
}

export function buildActivityFixtures() {
  return [
    {
      id: 'act001',
      action: 'PUBLISH',
      entity_type: 'dictionary',
      entity_label: 'MKT_006 — CPL Valid Lead',
      actor_name: 'Performance MKT',
      created_at: '2026-08-15T10:00:00+07:00',
    },
    {
      id: 'act002',
      action: 'UPDATE_TARGET',
      entity_type: 'target',
      entity_label: 'MKT_006 — Target 09/2026',
      actor_name: 'Performance MKT',
      created_at: '2026-09-01T09:30:00+07:00',
    },
    {
      id: 'act003',
      action: 'QUALITY_RUN',
      entity_type: 'quality',
      entity_label: 'Chạy kiểm tra DQ — 92/100',
      actor_name: 'Nguyễn Thị Lan',
      created_at: now,
    },
    {
      id: 'act004',
      action: 'REPORT_SEND',
      entity_type: 'report',
      entity_label: 'Báo cáo Marketing tuần',
      actor_name: 'Performance MKT',
      created_at: '2026-09-02T08:05:00+07:00',
    },
  ];
}
