-- Down for 2026-10-03-p13-05-quotes.sql. Does not drop crm_pricing_settings.discount_approval_threshold_pct.

DROP TABLE IF EXISTS crm_p13_quote_files;
DROP TABLE IF EXISTS crm_p13_settings;

ALTER TABLE crm_quote_line_item
  DROP COLUMN IF EXISTS pricing_source,
  DROP COLUMN IF EXISTS p13_line_type,
  DROP COLUMN IF EXISTS service_id,
  DROP COLUMN IF EXISTS level_code,
  DROP COLUMN IF EXISTS service_item_id,
  DROP COLUMN IF EXISTS item_qty_overrides_json,
  DROP COLUMN IF EXISTS list_unit_price,
  DROP COLUMN IF EXISTS unit_price_override_reason,
  DROP COLUMN IF EXISTS discount_pct,
  DROP COLUMN IF EXISTS hours_snapshot,
  DROP COLUMN IF EXISTS cost_snapshot,
  DROP COLUMN IF EXISTS passthrough_amount,
  DROP COLUMN IF EXISTS fee_pct_snapshot,
  DROP COLUMN IF EXISTS fee_min_snapshot,
  DROP COLUMN IF EXISTS fee_amount,
  DROP COLUMN IF EXISTS price_snapshot_json,
  DROP COLUMN IF EXISTS warnings_json,
  DROP COLUMN IF EXISTS description;

ALTER TABLE crm_proposals
  DROP COLUMN IF EXISTS pricing_source,
  DROP COLUMN IF EXISTS pricing_version_id,
  DROP COLUMN IF EXISTS pricing_params_version,
  DROP COLUMN IF EXISTS pricing_snapshot_json,
  DROP COLUMN IF EXISTS display_mode,
  DROP COLUMN IF EXISTS validity_days,
  DROP COLUMN IF EXISTS issued_at,
  DROP COLUMN IF EXISTS fee_subtotal,
  DROP COLUMN IF EXISTS extra_discount_pct,
  DROP COLUMN IF EXISTS extra_discount_amount,
  DROP COLUMN IF EXISTS fee_after_discount,
  DROP COLUMN IF EXISTS vat_pct,
  DROP COLUMN IF EXISTS fee_vat,
  DROP COLUMN IF EXISTS fee_total,
  DROP COLUMN IF EXISTS fee_vnd,
  DROP COLUMN IF EXISTS effective_discount_pct,
  DROP COLUMN IF EXISTS ad_budget_total,
  DROP COLUMN IF EXISTS ads_fee_total,
  DROP COLUMN IF EXISTS third_party_total,
  DROP COLUMN IF EXISTS booking_fee_total,
  DROP COLUMN IF EXISTS passthrough_vat,
  DROP COLUMN IF EXISTS passthrough_total,
  DROP COLUMN IF EXISTS grand_total,
  DROP COLUMN IF EXISTS list_fee_total,
  DROP COLUMN IF EXISTS cost_total,
  DROP COLUMN IF EXISTS margin_pct_effective,
  DROP COLUMN IF EXISTS gm_bps,
  DROP COLUMN IF EXISTS needs_approval,
  DROP COLUMN IF EXISTS p13_approval_status,
  DROP COLUMN IF EXISTS approval_reasons,
  DROP COLUMN IF EXISTS approval_requested_by,
  DROP COLUMN IF EXISTS approval_requested_at,
  DROP COLUMN IF EXISTS approved_by,
  DROP COLUMN IF EXISTS approved_at,
  DROP COLUMN IF EXISTS approval_note,
  DROP COLUMN IF EXISTS sent_channel,
  DROP COLUMN IF EXISTS sent_evidence_url,
  DROP COLUMN IF EXISTS accepted_evidence_url,
  DROP COLUMN IF EXISTS accepted_by_contact,
  DROP COLUMN IF EXISTS rejected_reason,
  DROP COLUMN IF EXISTS payment_terms_json,
  DROP COLUMN IF EXISTS is_test,
  DROP COLUMN IF EXISTS warnings_json,
  DROP COLUMN IF EXISTS p13_version_n,
  DROP COLUMN IF EXISTS shared_staff_ids;

DELETE FROM schema_migrations WHERE version = '2026-10-03-p13-05-quotes';
