import { NlQueryCatalogEntry } from './nl-query.types';

/** RNOS-22 / AI-UC-016 — curated whitelist (~25 intents v1; expand toward ~50). */
export const NL_QUERY_CATALOG: NlQueryCatalogEntry[] = [
  {
    id: 'leads_new_7d',
    label: 'Lead mới 7 ngày',
    aliases: ['lead 7 ngay', 'lead moi tuan', 'lead t-7'],
    category: 'leads',
    result_kind: 'table',
    description: 'Tổng lead mới (không trùng) 7 ngày gần nhất',
  },
  {
    id: 'leads_new_30d',
    label: 'Lead mới 30 ngày',
    aliases: ['lead 30 ngay', 'lead thang', 'lead t-30'],
    category: 'leads',
    result_kind: 'table',
    description: 'Tổng lead mới 30 ngày',
  },
  {
    id: 'leads_won_30d',
    label: 'Lead won 30 ngày',
    aliases: ['lead chot 30 ngay', 'lead won thang'],
    category: 'leads',
    result_kind: 'table',
    description: 'Lead chuyển trạng thái won trong 30 ngày',
  },
  {
    id: 'leads_by_channel_30d',
    label: 'Lead theo kênh 30 ngày',
    aliases: ['lead theo kenh', 'kenh lead 30 ngay'],
    category: 'leads',
    result_kind: 'table',
    description: 'Phân bổ lead theo kênh 30 ngày',
  },
  {
    id: 'leads_meta_30d',
    label: 'Lead Meta 30 ngày',
    aliases: ['lead meta ads', 'lead facebook 30 ngay'],
    category: 'leads',
    result_kind: 'table',
    description: 'Lead có campaign Meta/Facebook 30 ngày',
  },
  {
    id: 'cpl_meta_t30_overview',
    label: 'CPL Meta T-30 tổng quan',
    aliases: ['cpl meta t-30 theo client', 'cpl meta thang', 'cpl facebook 30 ngay'],
    category: 'revenue',
    result_kind: 'table',
    description: 'CPL ước tính = chi phí MKT tháng / lead Meta 30 ngày',
  },
  {
    id: 'revenue_received_7d',
    label: 'Doanh thu thu về 7 ngày',
    aliases: ['doanh thu 7 ngay', 'thu ve tuan'],
    category: 'revenue',
    result_kind: 'table',
    description: 'Tổng payment received 7 ngày',
  },
  {
    id: 'revenue_received_30d',
    label: 'Doanh thu thu về 30 ngày',
    aliases: ['doanh thu 30 ngay', 'doanh thu thang'],
    category: 'revenue',
    result_kind: 'table',
    description: 'Tổng payment received 30 ngày',
  },
  {
    id: 'revenue_trend_12w',
    label: 'Xu hướng doanh thu 12 tuần',
    aliases: ['doanh thu 12 tuan', 'trend revenue'],
    category: 'revenue',
    result_kind: 'chart',
    description: 'Doanh thu thu về theo tuần (12 tuần)',
  },
  {
    id: 'leads_trend_12w',
    label: 'Xu hướng lead 12 tuần',
    aliases: ['lead 12 tuan', 'trend lead'],
    category: 'leads',
    result_kind: 'chart',
    description: 'Lead mới theo tuần (12 tuần)',
  },
  {
    id: 'campaign_leads_top_month',
    label: 'Top campaign lead tháng này',
    aliases: ['campaign lead thang', 'top utm thang'],
    category: 'leads',
    result_kind: 'table',
    description: 'Campaign/UTM có nhiều lead nhất tháng hiện tại',
  },
  {
    id: 'open_deals_count',
    label: 'Deal đang mở',
    aliases: ['pipeline deal mo', 'so deal dang mo'],
    category: 'ops',
    result_kind: 'table',
    description: 'Số deal chưa terminal trong pipeline',
  },
  {
    id: 'sla_breach_summary',
    label: 'Tóm tắt SLA breach CSKH',
    aliases: ['sla breach', 'vi pham sla', 'sla cskh'],
    category: 'ops',
    result_kind: 'table',
    description: 'Breach / warning / ok trên CSKH board',
  },
  {
    id: 'sla_breach_top',
    label: 'Top lead SLA breach',
    aliases: ['lead sla breach', 'danh sach breach'],
    category: 'ops',
    result_kind: 'table',
    description: '20 lead vi phạm SLA gọi đầu tiên',
  },
  {
    id: 'pipeline_at_risk_count',
    label: 'Deal pipeline at-risk',
    aliases: ['pipeline risk', 'deal treo', 'deal at risk'],
    category: 'ai',
    result_kind: 'table',
    description: 'Số deal có cảnh báo pipeline risk (AI)',
  },
  {
    id: 'pipeline_at_risk_top',
    label: 'Top deal pipeline at-risk',
    aliases: ['top deal risk', 'deal canh bao'],
    category: 'ai',
    result_kind: 'table',
    description: '10 deal at-risk mới nhất',
  },
  {
    id: 'ai_acceptance_7d',
    label: 'AI acceptance 7 ngày',
    aliases: ['ty le chap nhan ai', 'ai acceptance tuan'],
    category: 'ai',
    result_kind: 'table',
    description: 'Tỷ lệ chấp nhận gợi ý AI 7 ngày',
  },
  {
    id: 'ai_dismiss_reasons_7d',
    label: 'Lý do dismiss AI 7 ngày',
    aliases: ['ly do bo ai', 'dismiss ai'],
    category: 'ai',
    result_kind: 'table',
    description: 'Top lý do bỏ qua gợi ý AI',
  },
  {
    id: 'forecast_month_summary',
    label: 'Forecast tháng hiện tại',
    aliases: ['du bao doanh thu', 'forecast thang'],
    category: 'forecast',
    result_kind: 'table',
    description: 'Snapshot forecast RNOS-17 (PG)',
  },
  {
    id: 'churn_health_top10',
    label: 'Top client churn risk',
    aliases: ['churn risk', 'client sap churn', 'health score'],
    category: 'health',
    result_kind: 'table',
    description: '10 client health score rủi ro cao nhất',
  },
  {
    id: 'renewal_candidates_90d',
    label: 'HĐ sắp hết hạn 90 ngày',
    aliases: ['renewal 90 ngay', 'hop dong sap het han'],
    category: 'health',
    result_kind: 'table',
    description: 'Hợp đồng active hết hạn trong 90 ngày',
  },
  {
    id: 'marketing_spend_current_month',
    label: 'Chi phí MKT tháng này',
    aliases: ['marketing spend', 'chi phi quang cao thang'],
    category: 'revenue',
    result_kind: 'table',
    description: 'Marketing spend nhập trên dashboard KD',
  },
  {
    id: 'duplicate_leads_30d',
    label: 'Lead trùng 30 ngày',
    aliases: ['lead trung', 'duplicate lead'],
    category: 'leads',
    result_kind: 'table',
    description: 'Lead đánh dấu duplicate 30 ngày',
  },
  {
    id: 'cskh_open_board',
    label: 'Lead mở trên CSKH board',
    aliases: ['cskh board mo', 'lead cho xu ly cskh'],
    category: 'ops',
    result_kind: 'table',
    description: 'Tổng lead đang trên CSKH board',
  },
  {
    id: 'qualified_leads_month',
    label: 'Lead qualified tháng này',
    aliases: ['lead qualified thang', 'lead dat chuan thang'],
    category: 'leads',
    result_kind: 'table',
    description: 'Lead qualified trong tháng hiện tại',
  },
  {
    id: 'cpl_by_client_30d',
    label: 'CPL theo client từ PG hub',
    aliases: ['cpl theo client', 'cpl client 30 ngay', 'cpl pg hub'],
    category: 'revenue',
    result_kind: 'table',
    description: 'CPL theo client từ daily performance PG trong 30 ngày',
  },
  {
    id: 'roas_overview_30d',
    label: 'ROAS tổng quan 30 ngày',
    aliases: ['roas tong quan', 'roas 30 ngay'],
    category: 'revenue',
    result_kind: 'table',
    description: 'ROAS gộp mọi kênh trong 30 ngày',
  },
  {
    id: 'roas_meta_30d',
    label: 'ROAS Meta 30 ngày',
    aliases: ['roas meta', 'roas facebook'],
    category: 'revenue',
    result_kind: 'table',
    description: 'ROAS Meta từ PG performance trong 30 ngày',
  },
  {
    id: 'roas_zalo_30d',
    label: 'ROAS Zalo 30 ngày',
    aliases: ['roas zalo', 'hieu qua zalo'],
    category: 'revenue',
    result_kind: 'table',
    description: 'ROAS Zalo từ PG performance trong 30 ngày',
  },
  {
    id: 'attribution_drill_paths',
    label: 'Attribution drill theo campaign',
    aliases: ['attribution drill', 'duong dan attribution', 'drill campaign'],
    category: 'leads',
    result_kind: 'table',
    description: 'Đường dẫn campaign → hub → lead mẫu',
  },
  {
    id: 'revenue_by_week_8w',
    label: 'Doanh thu theo tuần 8 tuần',
    aliases: ['doanh thu 8 tuan', 'revenue weekly'],
    category: 'revenue',
    result_kind: 'chart',
    description: 'Xu hướng doanh thu thu về 8 tuần',
  },
  {
    id: 'revenue_by_client_30d',
    label: 'Doanh thu theo client 30 ngày',
    aliases: ['doanh thu client', 'conversion value client'],
    category: 'revenue',
    result_kind: 'table',
    description: 'Conversion value theo client từ PG performance',
  },
  {
    id: 'revenue_forecast_gap',
    label: 'Khoảng cách forecast doanh thu',
    aliases: ['forecast gap', 'chenh lech forecast'],
    category: 'forecast',
    result_kind: 'table',
    description: 'Chênh lệch forecast và committed tháng hiện tại',
  },
  {
    id: 'leads_qualified_30d',
    label: 'Lead qualified 30 ngày',
    aliases: ['qualified 30 ngay', 'lead dat chuan 30 ngay'],
    category: 'leads',
    result_kind: 'table',
    description: 'Tổng lead qualified trong 30 ngày',
  },
  {
    id: 'leads_conversion_rate_30d',
    label: 'Tỷ lệ lead won 30 ngày',
    aliases: ['conversion lead', 'ty le chot lead'],
    category: 'leads',
    result_kind: 'table',
    description: 'Tỷ lệ won trên lead mới 30 ngày',
  },
  {
    id: 'leads_unassigned',
    label: 'Lead chưa phân công',
    aliases: ['lead chua assign', 'lead khong owner'],
    category: 'leads',
    result_kind: 'table',
    description: 'Lead mở chưa có owner',
  },
  {
    id: 'leads_stale_7d',
    label: 'Lead không cập nhật 7 ngày',
    aliases: ['lead stale', 'lead lau khong cap nhat'],
    category: 'leads',
    result_kind: 'table',
    description: 'Lead mở không cập nhật ít nhất 7 ngày',
  },
  {
    id: 'ops_sla_warning',
    label: 'Lead SLA warning',
    aliases: ['sla warning', 'canh bao sla'],
    category: 'ops',
    result_kind: 'table',
    description: 'Lead đang ở ngưỡng cảnh báo SLA',
  },
  {
    id: 'ops_deals_stalled_14d',
    label: 'Deal treo trên 14 ngày',
    aliases: ['deal stalled 14', 'deal treo 14 ngay'],
    category: 'ops',
    result_kind: 'table',
    description: 'Deal mở không cập nhật ít nhất 14 ngày',
  },
  {
    id: 'ops_payments_overdue',
    label: 'Thanh toán quá hạn',
    aliases: ['payment overdue', 'cong no qua han'],
    category: 'ops',
    result_kind: 'table',
    description: 'Tổng payment quá hạn chưa thu',
  },
  {
    id: 'ops_contracts_expiring_30d',
    label: 'Hợp đồng hết hạn 30 ngày',
    aliases: ['hop dong 30 ngay', 'contract expiring'],
    category: 'ops',
    result_kind: 'table',
    description: 'Hợp đồng active sắp hết hạn trong 30 ngày',
  },
  {
    id: 'forecast_pipeline_coverage',
    label: 'Độ phủ pipeline forecast',
    aliases: ['pipeline coverage', 'do phu forecast'],
    category: 'forecast',
    result_kind: 'table',
    description: 'Tỷ lệ forecast trên pipeline tháng hiện tại',
  },
  {
    id: 'forecast_committed_gap',
    label: 'Forecast so với committed',
    aliases: ['committed gap', 'forecast committed'],
    category: 'forecast',
    result_kind: 'table',
    description: 'Chênh lệch forecast và số GDKD committed',
  },
  {
    id: 'health_at_risk_count',
    label: 'Client health at-risk',
    aliases: ['health at risk count', 'client rui ro'],
    category: 'health',
    result_kind: 'table',
    description: 'Số client health ở mức at-risk hoặc critical',
  },
  {
    id: 'health_ticket_spike_count',
    label: 'Client có ticket spike',
    aliases: ['ticket spike client', 'client tang ticket'],
    category: 'health',
    result_kind: 'table',
    description: 'Số client được gắn cờ ticket spike',
  },
  {
    id: 'health_payment_overdue_count',
    label: 'Client có công nợ quá hạn',
    aliases: ['client overdue', 'health payment overdue'],
    category: 'health',
    result_kind: 'table',
    description: 'Số client có payment overdue',
  },
  {
    id: 'marketing_spend_by_channel_30d',
    label: 'Chi phí theo kênh 30 ngày',
    aliases: ['spend theo kenh', 'chi phi meta zalo'],
    category: 'revenue',
    result_kind: 'chart',
    description: 'Marketing spend theo kênh từ PG performance',
  },
  {
    id: 'cpl_trend_12w',
    label: 'Xu hướng CPL 12 tuần',
    aliases: ['cpl trend', 'cpl 12 tuan'],
    category: 'revenue',
    result_kind: 'chart',
    description: 'CPL gộp theo tuần từ PG performance',
  },
  {
    id: 'roas_trend_12w',
    label: 'Xu hướng ROAS 12 tuần',
    aliases: ['roas trend', 'roas 12 tuan'],
    category: 'revenue',
    result_kind: 'chart',
    description: 'ROAS gộp theo tuần từ PG performance',
  },
  {
    id: 'ai_recommendations_pending',
    label: 'Gợi ý AI đang chờ',
    aliases: ['ai pending', 'goi y ai chua xu ly'],
    category: 'ai',
    result_kind: 'table',
    description: 'Số recommendation AI trạng thái pending',
  },
];

export function listNlQueryCatalog(): NlQueryCatalogEntry[] {
  return [...NL_QUERY_CATALOG];
}
